### ISSUE TITLE
Nodejs: echo -n '{"name":"Bob"}' | fn run doesn't work

### ISSUE THREAD

**Issue by meyoungorcl** [fnproject/fn#1003]
I am using nodejs on fn version
Client version:  0.4.93
Server version:  0.3.445
When I run the command: echo -n '{"name":"Bob"}' | fn run
The result is: {"message":"Hello World"}
when it should be: {"message":"Hello Bob"}
This worked in previous fn versions.

**Comment by denismakogon** [comment]
You know, that's actually worked:
```
echo -n '{"name":"Bob"}' | fn run
Building image denismakogon/test:0.0.1 .......
{"message":"Hello Bob"}Deniss-MBP-2:test denismakogon$ fn version
Client version:  0.4.84
Server version:  0.3.433

```

**Comment by denismakogon** [comment]
`package.json` content
```js
{
	"name": "hellofn",
    "version": "1.0.0",
	"description": "example function",
	"main": "func.js",
	"author": "",
	"license": "Apache-2.0",
	"dependencies": {
		"@fnproject/fdk": "0.x"
	}
}
```

**Comment by denismakogon** [comment]
I see what's going on. With latest changes to CLI we remove default hard-coded content type.
In order to make it work you need to use the following command:
```
echo '{"name":"Bob"}' | fn run --content-type application/json
{"message":"Hello Bob"}
```

cc @rikgibson @michael-w-williams

**Comment by michael-w-williams** [comment]
Thanks Denis. I will start making the changes in the tutorials.

**Comment by rdallman** [comment]
fn run no longer exists
