### ISSUE TITLE
runner's `Status` return should indicate general runner health

### ISSUE THREAD

**Issue by jan-g** [fnproject/fn#1040]
This is potentially open-ended, but: there's scope in the "Status" return message for a runner to explicitly call out that it's in trouble. In particular, if the docker subsystem is having trouble the runner should definitely let the LB (or any other polling service) know that it's in difficulties.

There's space for this - for instance, the Status() call can explicitly return an error rather than a status. However, we require some detection in the runner for these kinds of conditions.

(Alternatively, the runner could just panic if its docker driver - or any other pertinent subsystem - gets into trouble; this'll show up as a grpc error since it'll stop talking!)

**Comment by kmjohansen** [comment]
Was discussing something similar with @skinowski yesterday.  We presently don't have any mechanism to recover container state if dockerd fails, so if we lose our docker connection or the ability to talk to the daemon either a panic or failure report seems appropriate.

There may be other deployment specific components that need to surface status to the LB about whether the host is healthy.  I don't have any brilliant proposals for this beyond a host-status type of plugin that can return Status information to the LB.

**Comment by skinowski** [comment]
Runner could poll docker (eg. docker-info(*)) if runner is idle for too long or simply respond OK based on any recent docker interaction (last docker-operation was OK or not). (Or just panic.) But this needs to be done by cherry-picking these operations in docker driver in runner. (eg. docker pull failures may or may not mean runner health failure.)

(*) docker-info doesn't mean much though. But shows docker up/running.

**Comment by kojustin** [comment]
Would this be the appropriate place to report information like "running low on memory" and non-fatal conditions? Is there a place to report metrics from the runner back to the load-balancer right now?

**Comment by skinowski** [comment]
So, in Status message, I'm planning to include some memory/slot/cpu info from agent's point of view. (not system memory/cpu utilization). Intended for LB to use the data as heuristics.

**Comment by skinowski** [comment]
Memory is particularly tricky as runner could be low (or out of) memory, but can have a lot of idle hot slots to handle many requests.

**Comment by kmjohansen** [comment]
@skinowski Fixed this so I'm closing it out.  If we run into specific health items that we'd like to add to the status, we can file new issues to pull them in.
