### ISSUE TITLE
Provide access to request body in models.Call interface

### ISSUE THREAD

**Issue by gviedma** [fnproject/fn#1054]
Listener extensions implementing the _CallListener_ interface have access to the _models.Call_ object but not the original request. This is problematic for listeners that need to consume the request body as part of their processing. We already expose URL and Headers in _models.Call_, so exposing the body would provide the missing access.

**Comment by skinowski** [comment]
When/if this happens, we can remove GetBody hacks in agent.call (see lb_agent.go and auth.go) which is currently an unsavory hack via call.RequestBody().

**Comment by skinowski** [comment]
This also have implications in gRPC between LB and runners. We need to be careful if we are going to send body in gRPC model as we can hit max msg sizes of gRPC. (runner client/server would probably need to strip the body off of model and pass it along using DataFrames like we do now.

Just spelling these out to make sure implementer covers these...

**Comment by rdallman** [comment]
think we're past this? re-open if wanted
