### ISSUE TITLE
[0.2] remove logs & calls APIs in favor of other solutions

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#1055]
currently, the logs and calls apis have a point lookup per call for call metrics and per log. in many respects, these are akin to metrics around just any http service, like an apache server. would you expect the apache server to keep a database with a request id for each http request, with the entire log, how long it took and status? there is a reason they do not have this abstraction set this way, as it's hard to scale. we need to adjust our data model here as well to fit what you would do in this situation, as its naturally what users expect anyway -- that is: we need a stream of logs across all requests (function logs) and we need metrics with efficient rollups so that users can see e.g. how many functions ran in the last hour? how many failed? how long does this function take on avg? p99? these are things we can't implement an API for that is easy to implement at scale, but we can provide flexible ways to get data into each of those systems (logging and metrics). https://github.com/fnproject/cli/issues/273 has enumerated a few of these kinds of use cases with information that users will want, however this is likely not something we can make an API for (as we found out). 

thus, we would like to remove the logs & calls APIs in favor of a combination system of #337 and #1047 on the basis that the current API is:

* extremely challenging to implement for larger scale installations of FN
* \> 99% of the data goes unread, signalling it's 'the wrong abstraction'

we expect that log & call data has prominent 2 use cases:

1) a user that is currently making a function and need to debug why it's not working (i.e. a dev needs a quick feedback loop of logs at a very low rate)
2) a user's function that is deployed and in use is failing, they need logs to see why that is and metrics to see function runtime, count, statuses, etc. (there are reasons like billing as well, to have runtime)

solutions:

1) #1047 a user may invoke a function in 'debug' mode to have the logs returned
2) * #337 users may set up a syslog url on their apps to have all container's logs from a function sent to a given syslog url - we may want additional ways to configure this, against an fn server instead of per app maybe (no ticket atm for this). 
    * we can add additional log lines for metrics, too, possibly, or something else shy of our current opencensus function status metrics to configure per function (?)

additional context around syslog flexibility:

* we expect that an implementer of fn-as-a-service at the cloud level will have a logging system to integrate with (e.g. AWS CloudWatch) to provide logging APIs through there
* we expect that users of functions on an fn-as-a-service platform would like a way to exfiltrate all of their function logs from the service into their own logging system (ELK, et al)
* we expect that an on premises style installation will have something like ELK, papertrail
* local users could configure a local syslog daemon to put logs into (also they could just turn on debugging logs for all functions with `FN_LOG_LEVEL=debug` at least for now)

work left to be done before pulling the plug:

* sort out the metrics story here for each of the levels of installation as listed above
* document each of the above installations with tutorials of how we envision this working
  * e.g. a demo of Fn working with something like ELK/syslog

**Comment by rdallman** [comment]
closes: #946 #483 #360 #587 #1027 (and maybe some i missed)

**Comment by shaunsmith** [comment]
Looks good but I think we need to consider how we can easily enable a non-prod log capture solution for local developers other than using debug-mode.   Is there something containerized we can suggest users run locally like https://github.com/deviantony/docker-elk ?

**Comment by rdallman** [comment]
docker-elk looks pretty good. i think we need to test out and doc examples for each of the 4 scenarios. out of the box we can probably say 'use debug mode' or as has been discussed maybe `fn call` defaults to debug mode to make this straightforward for users.

**Comment by shaunsmith** [comment]
Agree the solution is to test things out and document recommendations.  I just want to make sure the local dev experience is good and that logs are easily available.  But I don't think `fn call` should default to debug mode--it'll be too much console output 95% of the time.  You only want to see function stderr when things aren't working.
