### ISSUE TITLE
Sensitive information should be logged with DEBUG level?

### ISSUE THREAD

**Issue by andytruong** [fnproject/fn#1071]
When starting the server, the connection credential is written with "INFO" level. Should the level be "DEBUG"?

```
time="2018-06-19T04:14:04Z" level=info msg="Connecting to DB" url="root:root@tcp(mysql:3306)/fn"
```

**Comment by zootalures** [comment]
my mistake - this should be masked or not logged, will fix asap.

**Comment by andytruong** [comment]
I think the PR will be soon merged. Thanks.
