### ISSUE TITLE
fn run using special dockerfile

### ISSUE THREAD

**Issue by loopmocker** [fnproject/fn#1073]
can we use a special dockerfile when we call "fn run"? seems it use a dockerfile with a random number postfix

**Comment by zootalures** [comment]
We have some basic docs on this here: https://github.com/fnproject/fn/blob/795f37f1bd6aa77a5b561485d6fe5b206c61d518/docs/developers/packaging.md

**Comment by loopmocker** [comment]
thanks, I read the fn/cli source code and found that too, thanks anymore!!!

**Comment by zootalures** [comment]
Thanks for trying Fn!
