### ISSUE TITLE
use mysql

### ISSUE THREAD

**Issue by xycloud** [fnproject/fn#1078]
i see the doc of using mysql, the doc told us:

```
docker run --rm --privileged --link "func-mysql:mysql" \
    -e "FN_DB_URL=mysql://func:funcpass@tcp(mysql:3306)/funcs" \
    -it -p 8080:8080 fnproject/fnserver
```

but what's the relation about fn start. how can we start fn server with mysql as backend storage by using command fn start

**Comment by zootalures** [comment]
Fn start is primaily there for testing so this isn't fully supported right now - however you can make this work if you run mysql on a port on your host network : 

e.g (: 

```
docker run --rm  --name func-mysql-test -p 3306:3306 -e MYSQL_DATABASE=funcs -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7.22
MYSQL_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' func-mysql-test)

echo FN_DB_URL="mysql://root:root@tcp($MYSQL_IP:3306)/funcs" > fn.env

fn start --env-file fn.env 
```

**Comment by rdallman** [comment]
closing? re-open with improvement suggestions, we don't want 'real' installations using `fn start` -- maybe we need to make this more clear. thanks for filing an issue.
