### ISSUE TITLE
How to perform syncronous validation on asyncrounous function

### ISSUE THREAD

**Issue by c094728** [fnproject/fn#1084]
Async functions return response immediately.   I would like to perform input validation and return an error for bad input but otherwise return as normal and allow the long running async function to run.  Is this possible?

**Comment by denismakogon** [comment]
Hi! Consider my following recommendation as a starting point to investigate cases which suites you best. I recommend to setup a sync validation function that does validation and returns an HTTP redirect to an async function in case if the content is fine or HTTP 400 if it’s bad.

**Comment by rdallman** [comment]
it's possible to validate for an async function input with this extension handler: https://github.com/fnproject/fn/blob/master/fnext/listeners.go#L95 just check the `Payload` field.
