### ISSUE TITLE
Error in python tutorial

### ISSUE THREAD

**Issue by scottz1** [fnproject/fn#1100]
Here is the screen capture of running the python tutorial. fn --version works, and the Ubuntu guest in VirtualBox is able to browse to http://deb.debian.org, but it redirects the url to https.

-----
scott@scott-VirtualBox:~$ cd pythonfn
scott@scott-VirtualBox:~/pythonfn$ fn --verbose run
Building image pythonfn:0.0.1 
Sending build context to Docker daemon  7.168kB
Step 1/8 : FROM python:3.6-slim-stretch
 ---> b31cb11e68a1
Step 2/8 : WORKDIR /function
 ---> Using cache
 ---> bcc9d59a78c3
Step 3/8 : RUN apt-get update && apt-get install --no-install-recommends -qy build-essential gcc
 ---> Running in 346c6a4b01a3
Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package build-essential
E: Unable to locate package gcc
The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -qy build-essential gcc' returned a non-zero code: 100

**Comment by denismakogon** [comment]
How to debug this? You may try trace route to apt repos from inside docker
container manually.

However, you may try assigning custom docker image in func.yml
(build_image: ....) that does have all necessary packages (gcc, etc.)
installed.

**Comment by zootalures** [comment]
It seems off that we’re doing an apt-get install during fn build here, I think the base requirements should be bundled into the respective containers we provide

**Comment by rdallman** [comment]
> It seems off that we’re doing an apt-get install during fn build here, I think the base requirements should be bundled into the respective containers we provide

this seems to be the case now
