### ISSUE TITLE
Use a process supervisor on all functions by default 

### ISSUE THREAD

**Issue by zootalures** [fnproject/fn#1101]
**Description**

Currently we invoke functions directly via the equivalent of docker run,  this invokes the entrypoint as PID 1 within the container. 

This can cause problems for languages/code that do not set up the appropriate signal handling for a pid1 process which in turn can cause zombie processes to leak, eventually exhausting the resources of the sever. 

https://hackernoon.com/my-process-became-pid-1-and-now-signals-behave-strangely-b05c52cc551c?gi=9eddcdf48d16

**Describe the results you received:**
Not tested directly but certain that this could catch people out when using many FDKs (python, node) or using arbitrary binaries. 

Spawning child processes via exec will not be reaped, resulting in zombies

**Describe the results you expected:**

Child processes are reaped. 

**What to do** ? 

I think a simple solution here is to always run functions with the default `docker-init` wrapper  in all environments, this provides consistency   of experience and provides the most protection against accidental process leaks. 

As of recent versions of docker this binary is installed as part of the docker distribution

within the docker agent we'd need to add InitBinary calls to the container construction call, sadly this also means reving our docker API dependency.

**Comment by rdallman** [comment]
docs link: https://docs.docker.com/engine/reference/run/#specify-an-init-process

we may want to cross test this on OSX and Windows systems as well, it may be something arch-specific we have to do on linux and we could end up in a situation where a user may be running their container slightly differently with `fn run` on their mac vs. `fn call` on some linux-hosted `fn` server. this seems like something we can try and if it causes issues we may be able to remove it -- though maybe that cuts both ways, we could also potentially add an option to disable it if the user knows their process handles signals fine and has issues with `tini` for whatever reason.

upgrading the fsouza client should be relatively easy.

**Comment by rdallman** [comment]
we've updated the fsouza client lately... testing. not cleaning out my flagged mail has paid dividends
