### ISSUE TITLE
Unable to use S3 compatible log store with '/' in secret access key

### ISSUE THREAD

**Issue by abhirockzz** [fnproject/fn#1124]
**Description**

When using a S3 based log store, Fn server does not start when the S3 store secret access key contains a '/' (forward slash) - S3 URL is not parsed properly

**Steps to reproduce the issue:**

start Fn server with env variable FN_LOGSTORE_URL pointing to external S3 store e.g. docker run --privileged -e "FN_LOGSTORE_URL=s3://myaccesskey:mysec/retkey@s3host/us-east-1/fn-log-bucket?ssl=true" fnproject/fnserver:latest

(notice the '/' in the the secret access key 'mysec/retkey')

**Describe the results you received:**

Fn server logs

```
level=info msg="checking / creating s3 bucket" access_key_id= bucketName=us-east-1/fn-log-bucket endpoint="myaccesskey:mysec" region=retkey@s3host useSSL=true

level=fatal msg="Error during server opt initialization." error="failed to create bucket us-east-1/fn-log-bucket: static credentials are empty"
```

**Describe the results you expected:**

Although the above mentioned secret access key is a dummy one, a valid secret access key with a '/' to should work. 

**Additional information you deem important (e.g. issue happens only occasionally):**

the same secret access key (with the '/') worked with standalone AWS S3 as well as Minio client

**Output of `fn version` (CLI command):**

```
Client version:  0.4.66
Server version:  ?
```

**Additional environment details (OSX, Linux, flags, etc.):**

**Comment by zootalures** [comment]
I’m not 100% sure it will work but can you try using a url-escaped version of the password?
