### ISSUE TITLE
Can't push private localhost repository in Example

### ISSUE THREAD

**Issue by komuro-hiraku** [fnproject/fn#1135]
**Description**

I tried `fn deploy` to private localhost repository. But error occur and can't deploy function. 
I referred to the following link.

https://github.com/fnproject/fn/blob/master/docs/operating/private_registries.md#example-of-a-private-registry-on-localhost

Something wrong?

**Steps to reproduce the issue:**
1. Start docker repository in localhost. `$ docker run -d -p 5000:5000 --name registry registry:2`
2. Create sample app. `$ fn init --runtime go dummy`
3. Execute deploy command with `--registry` option. `$ fn deploy --app myapp --registry localhost:5000/some/path`

**Describe the results you received:**

```
$ fn deploy --app myapp --registry localhost:5000/some/path
Deploying dummy to app: myapp at path: /dummy
Bumped to version 0.0.11
Building image dummy:0.0.11 ...........................................

Fn: image name must have a dockerhub owner or private registry. Be sure to set FN_REGISTRY env var, pass in --registry or configure your context file

See 'fn <command> --help' for more information. Client version: 0.4.133
```

**Describe the results you expected:**

```
$ fn deploy --app myapp --registry localhost:5000/some/path
Deploying dummy to app: myapp at path: /dummy
Bumped to version 0.0.11
Building image localhost:5000/some/path/dummy:0.0.11 ..
Pushing localhost:5000/some/path/dummy:0.0.11 to docker registry...The push refers to a repository [localhost:5000/some/path/dummy]
5fcef0dbce8b: Pushed
ce4a1aad8bd7: Pushed
88229188f6e3: Pushed
d82c387bddae: Pushed
0.0.2: digest: sha256:xxxxxxxxxxx 
size: xxxx
Updating route /dummy using image localhost:5000/some/path/dummy:0.0.11...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker insecure registries settings is below screenshot.

![2018-07-25 0 33 06](https://user-images.githubusercontent.com/2126669/43149443-5fc545d8-8fa2-11e8-8b7a-a2bc285bb702.jpg)

**Output of `fn version` (CLI command):**

```
$ fn --version
fn version 0.4.133
```

**Additional environment details (OSX, Linux, flags, etc.):**

- OS: macOS Sierra 10.12.6
- Docker version 18.03.1-ce, build 9ee9f40

**Comment by denismakogon** [comment]
Hi! It seems like Fn can’t reach out your registry. Just ordinary
networking issue. It depends on how you’ve started Fn server if that was
`fn start` then you need to link your Fn to your registry container.

**Comment by komuro-hiraku** [comment]
@denismakogon Thank you advice! 
I tried export environment variable `FN_REGISTRY` and retry it.

```
$ export FN_REGISTRY=localhost:5000
```

result

```
$ fn deploy --app myapp --registry localhost:5000/some/path
Deploying dummy to app: myapp at path: /dummy
Bumped to version 0.0.15
Building image localhost:5000/dummy:0.0.15 .....
Pushing localhost:5000/dummy:0.0.15 to docker registry...The push refers to repository [localhost:5000/dummy]
906d64187b57: Pushed
7b7733e65573: Pushed
97dedccb7128: Pushed
c9e8b5c053a2: Pushed
0.0.15: digest: sha256:750d8e43e27b4d44901ca50a37d9e11acdee15ed5092452c4589fc024d4ff2a1 size: 1156
Updating route /dummy using image localhost:5000/dummy:0.0.15...

Fn: Put http://localhost:8080/v1/apps/myapp/routes/dummy: EOF

See 'fn <command> --help' for more information. Client version: 0.4.133
```

Deployment succeeded!
Thank you great advice!
