### ISSUE TITLE
lb: small features

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#115]
In gitlab by @rdallman on Jul 13, 2017, 11:48

* [ ] re-route requests that error to a different backend. this may require buffering bodies which isn't great, we need to take care that an attacker couldn't easily OOM us; but it shouldn't add much response latency [in normal path]. for now, probably only re-route guys that didn't run.
* [ ] enable SSL / h2. this is just simple plumbing since go does this out of the box.
* [x] investigate adding k8's backend [in addition to db's]
* [ ] integrate with a real stats backend (statsd/prom), get charts from that
* [ ] ping/version endpoints

i guess it would also be nice to list the [not missing] features somewhere, too. anyone is welcome to add, I think we may be able to finagle out of trying to integrate with vulcand/traefik and have something we can control that is pretty light (thanks to Go, mostly)

**Comment by treeder** [comment]
Still want this open?
