### ISSUE TITLE
Ability to execute custom logic before 'hot' function termination

### ISSUE THREAD

**Issue by abhirockzz** [fnproject/fn#1161]
Provide the ability to plugin custom code which should get (automatically) invoked just before a hot function terminates.

One of the use cases is to be able to close remote connections (e.g. database, API handles etc.) which should ideally not be killed after every invocation of the function in order to make use of hot functions. Rather than abandoning them (e.g. leaving it to the DB server to kill hanging connections after certain timeout) it would be ideal if the developer can provide the logic and hand-it-over to Fn to call it

I am assuming this would be a FDK specific feature

**Comment by rdallman** [comment]
this sounds like a good thing to have, the interplay between the server and container may be challenging given the current protocol as there's multiple conditions where a container may be terminated (idle_timeout, eviction when resources are full, docker crashes, maybe more in future). 

in my mind, a user could theoretically hook this up as follows (go):

```go
func main() {
    fdk.Handle(myHandler)
    myExitHandler()
}
```

the above would require no additional interface for the FDK to implement, it's just simply a user-defined function they add to the call stack after the handle loop exits. 

every FDK at the moment is structured this way and in theory we could do this if we handled OS signals inside of `fdk.Handle` and bailed without adding anything onto the byte protocol itself. the above would not work currently because we aren't handling signals and exiting `fdk.Handle` in the FDK, we're terminating the entire container via docker (i.e. the fdk/code doesn't handle the shutdown). it would also be possible to add an additional protocol method onto our FDK contract to bail on `fdk.Handle`, or maybe something else, the OS signal thing seems a lot cleaner and potentially easier to hook up server side. it would be possible to add an additional method onto the FDK to make this explicit, I just fear bloat there and would like the FDK to be as minimal as possible, if anything, for ease of maintenance but also to make it look easy to use. wdyt of this proposal @abhirockzz ?

**Comment by zootalures** [comment]
I'm against having this as a design principle : 

Right now we make no promises about what happens to your function after a call is completed - including offering any sort of graceful shutdown - this simplifies the lifecycle and allows Fn to more effectively use resources on a shared resource pool.

If we added this hook we'd either have to make best efforts to handle it (making function shutdown more complex and reducing our ability to quickly free resources for new functions) - or sometimes not honour it (which is confusing for users as they were expecting it to work) .  In the case where somebody is billing for a function that also becomes more complex here. 

When we shut down your function I think  fn /docker should cause all existing TCP connections  -Most DB servers can be configured to correctly honour that and release resources.

**Comment by rdallman** [comment]
that's true, and it complicates the freeze significantly (thaw, run the thing), along with billing.

**Comment by zootalures** [comment]
I think my mental model here is: Functions are "conceptually stateless" things that should also engage with similarly conceptually stateless services - 

In practice hot functions may keep some transient state between calls and this is beneficial for performance (HTTP connections, JDBC connections) , but the contract for that state is that it should not materially impact subsequent interactions (can't tell the difference functionally between the first and second interaction) and that the state should be discardable without action. 

Doing connection-state based things like JDBC connections is possible so long as it works but I think the onus is on the user to make sure that the downstream services are tolerant to disconnects and discards, not fn.

**Comment by skinowski** [comment]
I like this and mentioned it in the past, but to do this, I think we'd need to amend the protocols to handle an early return of data to client while holding the container/token (and making it sure that time/cpu is accounted.) We can perhaps look at it after cloud events (which I think simplifies the flow) and see if it can be handled easily.

**Comment by sachin-pikle** [comment]
I would like to understand what is our recommendation to folks that want to use functions to talk to (less scalable) traditional backends like databases, message queues. How should folks deal with connections? What is the best place to close them?

**Comment by skinowski** [comment]
I apologize, I misunderstood this issue, I was talking about a post handler that gets executed at every invocation, where users can execute code without impacting request latency.

But an exit handler is problematic for us, like @zootalures said we shouldn't gracefully wait for user code to clean up.

**Comment by skinowski** [comment]
I'd like to understand more about the original problem however. When hot functions terminate, such backends should receive FIN/RST, so the backend should have the opportunity to notice and clean up these connections upon termination.

I wonder, if @abhirockzz is actually referring to idle connections on live (but idle) hot containers. In other words, hot containers that hasn't exceeded their idle timeout, but not handling a request and holding on to such connections.

**Comment by abhirockzz** [comment]
> I wonder, if @abhirockzz is actually referring to idle connections on live (but idle) hot containers. In other words, hot containers that haven't exceeded their idle timeout, but not handling a request and holding on to such connections.

@skinowski no that's not the case. The use case is related to hot containers and the point of impact is just before they terminate.

> When we shut down your function I think fn /docker should cause all existing TCP connections to be reset - Most DB servers can be configured to correctly honour that and release resources.

@zootalures The problem is generic in nature - DB was just an example. It is not about stateful or stateless either (although the DB specific example is a stateful one). 

`System.getRuntime().addShutdownHook()` does not work - I understand why since @rdallman confirmed 

> in the FDK, we're terminating the entire container via docker (i.e. the fdk/code doesn't handle the shutdown)

There should be some way for the user to plugin this logic before the container exits - at the bare minimum, it should handle SIGTERM. 

I see that there is a [listener concept](https://github.com/fnproject/fdk-java/blob/854cfb49b3e47f67873756b62d941e20a648b508/api/src/main/java/com/fnproject/fn/api/InvocationListener.java) in the Java FDK (per invocation based)

**Comment by hmpurwar** [comment]
There should be some way to gracefully shutdown the fn-container after Its life cycle is over.
Some of the scenarios 
1. cleaning up open DB-connections
2. storing fn states to some persistent storage, so that once fn is invoked again, It can read from that persistent store

**Comment by zootalures** [comment]
I’m closing this as won’t fix for now, per discussion above there isn’t a way we can guarantee that these hooks will happen so if you rely on  them for things like DB disconnections would cause problems when that didn’t happen
