### ISSUE TITLE
extensions: no data store provider found for storage url sqlite3

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1163]
**Description**
Certain problems appear while building an extended fnserver.

**Steps to reproduce the issue:**
1. Use fn-ext-example tutorial and build
2. Build a server
3. Launch a server

**Describe the results you received:**
```
INFO[2018-08-08T13:55:00+03:00] Setting log level to                          level=info
FATA[2018-08-08T13:55:00+03:00] Error during server opt initialization.       error="no data store provider found for storage url sqlite3:///Users/denismakogon/Documents/oracle/go/src/github.com/fnproject/fn-ext-example/data/fn.db"

```

**Describe the results you expected:**

I expected to get a working fnserver as if i'd build and start ordinary fnserver.

**Additional information you deem important (e.g. issue happens only occasionally):**

fnserver version: 0.3.58
OS env is clear, nothing interfer with Fn-related env vars.

**Comment by zootalures** [comment]
Default storage extensions need to be added to the extension main

**Comment by denismakogon** [comment]
Ok, more problems appeared:
once again, deps, fn 0.3.58 becomes a problem as a dependency.
```
go build
# github.com/fnproject/fn-ext-example/vendor/github.com/docker/docker/opts
vendor/github.com/docker/docker/opts/address_pools.go:15:12: undefined: ipamutils.NetworkToSplit

```
the problem is in docker dep with a:
`revision = "f57f260b49b6142366e6bc1274204ee0a1205945"`
so, it needs to be manually reverted to exact version Fn has:
`revision = "29fc64b590badcb1c3f5beff7563ffd31eb58974"`

**Comment by zootalures** [comment]
huh - that should be happing by virtue of it being  a constraint in dep shouldn't it?

**Comment by rdallman** [comment]
I've seen `dep` barf on transitive dependency version constraints like this, it usually fusses about the mismatch if you've specified a different version (say, master) or revision in the `Gopkg.yaml` file, they make you solve it yourself and bail.

**Comment by zootalures** [comment]
Could it be the version of dep in the build container ?

**Comment by rdallman** [comment]
closing since there's an example that fixed this now
