### ISSUE TITLE
FNs in v2 do not match from swagger to impl.

### ISSUE THREAD

**Issue by hibooboo2** [fnproject/fn#1182]
**Description**
Swagger model Fn has mem with mem for the json. Api returns memory...
**Steps to reproduce the issue:**
1.Use swagger client to make a fn.. Memory will never return as non zero with v2 client. Memory will be 128 but no mem field.

**Describe the results you received:**
Made fn got no mem field had memory field.

**Describe the results you expected:**
Get mem field not memory...

name = "github.com/fnproject/fn_go"
  version = "0.2.11"

**Comment by zootalures** [comment]
Ugh Suggest just fixing the swagger here “memory” is better

**Comment by zootalures** [comment]
This will require a rev of the SDK and CLI
