### ISSUE TITLE
Unable to create async function with the timeout longer than 300 seconds.

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1198]
**Description**

Unable to create async function (v2) with timeout longer than 300 seconds:

func.yaml:
```yaml
schema_version: 20180708
name: bucket-cleaner
version: 0.0.7
runtime: go
entrypoint: ./func
format: json
type: async
memory: 258
timeout: 360
triggers:
- name: bucket-cleaner
  type: http
  source: /bucket-cleaner

```

**Steps to reproduce the issue:**
1. init a function
2. set it to async mode with an timeout greater than 300 secs.
3. deploy

**Describe the results you received:**

Deploy log:
```
Deploying bucket-cleaner to app: videbox
Bumped to version 0.0.7
Building image denismakogon/bucket-cleaner:0.0.7 
FN_REGISTRY:  denismakogon
Current Context:  default
Sending build context to Docker daemon  88.75MB
Step 1/8 : FROM fnproject/go:dev as build-stage
 ---> fac877f7d14d
Step 2/8 : WORKDIR /function
 ---> Using cache
 ---> 1980b829219e
Step 3/8 : ADD . /go/src/func/
 ---> 2a4fef34b60d
Step 4/8 : RUN cd /go/src/func/ && go build -o func
 ---> Running in 7c5b674ab042
Removing intermediate container 7c5b674ab042
 ---> 9e8475e2f224
Step 5/8 : FROM fnproject/go
 ---> 76aed4489768
Step 6/8 : WORKDIR /function
 ---> Using cache
 ---> 63179d25b899
Step 7/8 : COPY --from=build-stage /go/src/func/func /function/
 ---> Using cache
 ---> 517ee1e48507
Step 8/8 : ENTRYPOINT ["./func"]
 ---> Using cache
 ---> 8c535700ceff
Successfully built 8c535700ceff
Successfully tagged denismakogon/bucket-cleaner:0.0.7

Updating function bucket-cleaner using image denismakogon/bucket-cleaner:0.0.7...

Fn: timeout value is out of range, must be between 0 and 300


```

**Describe the results you expected:**

Success is expected. The max timeout for an async functions suppose to be 3600.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `fn version` (CLI command):**

```
Client version is latest version: 0.4.155
Server version:  0.3.548
```

**Comment by denismakogon** [comment]
@rdallman @skinowski @ostrain

**Comment by denismakogon** [comment]
This is what makes all our demos broken apart.

Server's code only accepts 300 seconds as max no matter if a function is async and requires a longer timeout.

API v1 still works, but UX changed, which doesn't really make things easy.

**Comment by rdallman** [comment]
you may not have noticed, but `type: ` is no longer a valid field in v2 http://petstore.swagger.io/?url=https://raw.githubusercontent.com/fnproject/fn/master/docs/swagger_v2.yml#/Fns/CreateFn -- as it stands, async is to be implemented via triggers -- this hasn't been well fleshed out yet. there have been some discussions around prioritizing async recently, but that's the issue here really.

**Comment by denismakogon** [comment]
I do know that type now lives in a trigger model, that's what `fn migration` gives me, so, posted as it was. There is a way to make it work:
 - define a function with the timeout (constraint: 3600s)
 - create a trigger: 
    * if sync - say that timeout must be shorter if function's timeout greater than 300 seconds
    * if async - check if the upper limit is not reached.

**Comment by rdallman** [comment]
`type: async` isn't a thing anymore, to be clear, in func or trigger

**Comment by denismakogon** [comment]
I do know that, `fn migrate` is buggy, that’s why type attribute is still there, but that’s not the case here.

**Comment by rdallman** [comment]
ok, i'm not understanding your previous comment then -- the only supported trigger type atm in fn is `type: http` triggers, which use the old `type: sync` that was on routes, and afaik there is no way to set the [old style] type to async in either invoke or in http triggers for a function, the only way to get this behavior is to use route (which is deprecated) or add a new trigger type to fn completely (as was implied may happen but does not exist today) that sets the call's `type: "async"`. hopefully that makes more sense or i'm still confused ?

**Comment by rdallman** [comment]
no worries. to date we were thinking the answer to that question was 'if you need the previous API for any reason, use an old version of fn'. it's an answer, at least. is that ok? it's possible we start discussing async in the next couple of weeks, it's come up as a priority but no promises. if you have any ideas about how it might should work, it would be useful. we could maybe make a really hacky way to get at the old async behavior with a new trigger meanwhile, as well (I am a bit uneasy to hastily do this, but it's an idea anyway)
