### ISSUE TITLE
Unclear error message for the misconfigured syslog URL during app update

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1240]
**Description**

I'm seeing a problem with the error message that comes from the server during an application update procedure:

```
fn update app testapp --syslog-url "tls://logsXYZ.papertrailapp.com:00000"

Fn: invalid syslog url: "tls://logsXYZ.papertrailapp.com:00000"

```
However, the URL itself is [valid](https://play.golang.org/p/oZQdw8PkYp5).

**Steps to reproduce the issue:**
1. create an application
2. create the papertrail endpoint
3. update an app using the command from above.

**Describe the results you received:**

```
fn update app testapp --syslog-url "tls://logsXYZ.papertrailapp.com:00000"

Fn: invalid syslog url: "tls://logsXYZ.papertrailapp.com:00000"
```

**Describe the results you expected:**

Actuall Fn requires extended schema: `tcp+tls://logsXYZ.papertrailapp.com:00000`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `fn version` (CLI command):**

```
Client version is latest version: 0.5.6
Server version:  0.3.579
```

**Comment by denismakogon** [comment]
Our docs saying that `tls://...` is enough (https://github.com/fnproject/docs/blob/master/fn/operate/logging.md) as well as post on HN (https://hackernoon.com/collecting-logs-from-serverless-fn-functions-a3bc6a7d8ec9)

**Comment by rdallman** [comment]
fixings docs/adding tests and better error...
