### ISSUE TITLE
Router error in deploy command

### ISSUE THREAD

**Issue by klebermagno** [fnproject/fn#1256]
I'm in Mac OS X 10.14 with  0.5.12 when I run the follow command I got this error:

`fn deploy --app javafn --local`                                                                                                                                                                                      Mon Oct  1 15:51:48 2018

Fn: routes are no longer supported, please use the migrate command to update your metadata

See 'fn <command> --help' for more information. Client version: 0.5.12

Project 
https://github.com/panga/fn-native-java

**Comment by zootalures** [comment]
We've updated the func.yaml format, and you need to run `fn migrate` to update existing files, can you try that?

**Comment by klebermagno** [comment]
yes, it's working now.
thank you!
