### ISSUE TITLE
FN UI is broken

### ISSUE THREAD

**Issue by luigisaetta** [fnproject/fn#1258]
**Description**

I have cloned the Github repo this morning, for an important demo we're setting up in Dubai.
If I start using the docker-compose, as soon as I access to the UI (port 4000)
I see a msg "Error: An error ocurred." on the top right side.

Then, I'm not able to create application from UI

**Steps to reproduce the issue:**
1. clone git repo
2. start entire env with docker-compose
3. access to UI 

**Describe the results you received:**
I access to the UI (port 4000)
I see a msg "Error: An error ocurred." on the top right side.

and UI seems no more working.
funtion and applications create through CLI are not seen on UI

**Additional information you deem important (e.g. issue happens only occasionally):**

Happen always

**Output of `fn version` (CLI command):**

```
(paste your output here)
```

**Additional environment details (OSX, Linux, flags, etc.):**
Tested on Linux (Ubuntu and MacOS

**Comment by denismakogon** [comment]
Unfortunately, UI needs some love. At this moment it’s unmaintained. If you can help with that, it would be awesome.

**Comment by swiftrs** [comment]
A notice on the fn or fnproject/ui page would have been welcome. So we wasted some time trying to get it run.

**Comment by rdallman** [comment]
yea, that is a good idea, sorry about that

**Comment by rdallman** [comment]
https://github.com/fnproject/ui/pull/53

**Comment by rdallman** [comment]
going to leave this open for triage reasons

**Comment by vzDevelopment** [comment]
Once the PR above is merged the main issue in this ticket will have been resolved. There are still some other things that I want to tidy up which I will continue with in fnproject/ui#52.
