### ISSUE TITLE
Python tutorial not working with FN docker-compose environment

### ISSUE THREAD

**Issue by luigisaetta** [fnproject/fn#1259]
The FN Python tutorial contained at http://fnproject.io/tutorials/python/intro/
is not working inside the FN docker environment

I have tried to port some Python code, developed in a previous FN version, inside the
new env obtained through git clone done this morning.
It doesn't work.

Therefore, to test, I have tried to reproduce the Python tutorial.

All steps goes OK till the final one: when you invoke the function.

The result is that invoke blocks with the command line and with the URL (HTTP) call

**Steps to reproduce the issue:**
1. Create an FN env doing a git clone
2. Start the FN env with docker-compose
3. Build the function as described in Python tutorial (http://fnproject.io/tutorials/python/intro/)
4. Invoke the function

**Describe the results you received:**
The call is blocked. No answer

**Describe the results you expected:**
As described in the tutorial

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `fn version` (CLI command):**

```
(paste your output here)
```

**Additional environment details (OSX, Linux, flags, etc.):**

**Comment by denismakogon** [comment]
Hi, we need more input about the way you run Fn, with the latest changes Fn needs more configuration options. See my comments here: https://fnproject.slack.com/archives/C6FL02Q02/p1538516988000100

**Comment by luigisaetta** [comment]
As I wrote, I have used the docker-compose environment, with docker-compose.yaml contained in the cloned repo.

cd fn directory

sudo docker-compose up -d

**Comment by denismakogon** [comment]
that may not work properly, the only way is to run Fn using `fn start`. I'd investigate an issue with the compose file, but it'll take more time.

**Comment by vzDevelopment** [comment]
I followed the python tutorial on Friday using `fn start` and it all seemed to work ok.

The `docker-compose.yml` file was removed in 5fce7082ef3 as part of #1358 so don't think this issue is applicable any more and can be closed.

Please correct me if I am wrong.

**Comment by carimura** [comment]
ya compose is likely out of date and no plans for support (for now). thanks for the ticket.

**Comment by denismakogon** [comment]
Compose file has gone for good, please use helm charts if you need somewhat different from `fn start`.
