### ISSUE TITLE
Headers are never set

### ISSUE THREAD

**Issue by cfsilence** [fnproject/fn#1263]
**Description**

When I try to add headers to my func.yml file they are stripped automatically every time I do `fn deploy` - in fact, no method that I'm trying will add an Access-Control-Allow-Origin header to the response. I've tried FN_API_CORS_ORIGINS, I've even tried setting the headers directly on the OutputEvent with Headers.fromMap() in the function call itself. I simply can not get a function call to set a response header. Trying on fn version 0.5.8.

I even see this in the startup output:

```time="2018-10-05T19:24:47Z" level=info msg="CORS enabled for domains: [*]"```

But no header is ever set on any response

**Steps to reproduce the issue:**
1. attempt to enable CORS
2. deploy function
3. test function

**Describe the results you received:**
Did not receive any headers.

**Describe the results you expected:**
Expected to see an Access-Control-Allow-Origin (or any header when I try custom ones via the function call) to be set on the response.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `fn version` (CLI command):**

```
fn version 0.5.8
```

**Additional environment details (OSX, Linux, flags, etc.):**
OSX High Sierra

**Comment by rdallman** [comment]
headers can no longer be set on func.yaml and are removed from the API now (previously via the removed routes API). for setting from the function itself, this should be fixed, see: https://github.com/fnproject/fn/issues/311 - which documents how to do this from java. the same facilities are available in every fdk now - if this isn't working please re-open with details about fdk and some logs. thanks for filing, sorry for delayed response here.
