### ISSUE TITLE
AckSync with FN configured in LB mode

### ISSUE THREAD

**Issue by reclaro** [fnproject/fn#1266]
It would be nice to have a kind of fire-and-forget scenario available, a user wants to have a response back from the server as soon as the server has placed the call on a runner.
In the first version of this change we want to implement an mechanism to send a 202 response from the server as soon as the execution of the function starts.

In this version the user doesn't have a way to check if the function has terminated, if the function failed or succeeded.
In this version we are going to allow those kind of calls only if the server is configured in the LB mode (using the lb_agent.go).

Please note that this is NOT an async call, in this scenario we don't put a request of execution in any kind of queue, the server will try to execute it as soon as it can and it will respect the function timeout.

The new contract can define a specific timeout for the server to send an ack back, if the timeout expires it means that the server was unable to place a call in time and the execution never started.

**Comment by abhirockzz** [comment]
Is there supporting documentation for this ?

**Comment by reclaro** [comment]
@abhirockzz not yet, good point we need to document this feature.

**Comment by rdallman** [comment]
closing, need to doc maybe
