### ISSUE TITLE
[Invoke/Trigger API] Inconsistent HTTP headers

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1270]
**Description**

So, here's the thing. When a developer uses Trigger API to call a function he gets the following headers:
```go
map[
    Content-Type:[application/json] 
    Fn-Call-Id:[01CSHDGH16NG8G00GZJ0000013] 
    Fn-Deadline:[2018-10-11T11:17:45Z] 
    Fn-Http-H-Accept:[*/*] 
    Fn-Http-H-Content-Length:[17] 
    Fn_call_id:[01CSHDGH16NG8G00GZJ0000013] 
    Fn_deadline:[2018-10-11T11:17:45Z] 
    Accept-Encoding:[gzip] 
    Fn-Http-Request-Url:[http://localhost:8080/t/testapp/azure]
    Fn-Http-Method:[POST] User-Agent:[Go-http-client/1.1] 
    Fn-Intent:[httprequest] Fn-Http-H-User-Agent:[curl/7.54.0]
] 
```

but for Invoke API headers are:
```go
map[
    Content-Type:[application/json]
    Fn-Call-Id:[01CSHEY1VZNG8G00GZJ0000020]
    Fn_call_id:[01CSHEY1VZNG8G00GZJ0000020]
    Accept:[*/*]
    Accept-Encoding:[gzip]
    User-Agent:[curl/7.54.0]
    Fn-Deadline:[2018-10-11T11:42:34Z]
    Fn_deadline:[2018-10-11T11:42:34Z]
]
```
As you may see, a number of headers is not consistent (not talking about format-specific headers, but in general). One of the key differences is the content length, in Invoke headers it doesn not exist for some reason. 

**Steps to reproduce the issue:**
1. Deploy hello-world application with any of FDKs.
2. Add a piece of code that logs incoming headers.
3. See logs.

**Describe the results you received:**

With an outgoing heades:
```
> POST /t/testapp/azure HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 17
```

the incoming headers are not consistent within the existing API methods.

**Describe the results you expected:**

Well, i expect to have them consistent, no matter if that is prefixed with `Fn-Http-H-` or not.

**Output of `fn version` (CLI command):**

```
Client version is latest version: 0.5.15
Server version:  0.3.591
```

**Comment by rdallman** [comment]
well, this was part of the design, and this behavior is documented, and we are using the fdks to resolve this to appear the same to users. I'm just getting through email I apologize for my brevity, but this is intentional as far as I understand from the issue description...

**Comment by denismakogon** [comment]
Content-Length header must be there because basically I cannot proxy the request to another service without actually inspecting the size of the data and manually injecing that.

**Comment by zootalures** [comment]
Content length is optional and laregely unnecessary when you use the HTTP1.1 chunked encoding you won’t get it a lot of the time anyway

**Comment by zootalures** [comment]
Closing this as I don't believe it is a bug - 

If you need to proxy requests you should use chunked encoding on the downstream system. If you need the content length then you need to buffer the input.

**Comment by delabassee** [comment]
What's the point of having 2 times the call ID, i.e. `Fn-Call-Id`and `Fn_call_id`?

eg. 
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 2
Content-Type: application/json
Date: Tue, 16 Oct 2018 16:36:26 GMT
Fn-Call-Id: 01CSYVRKZDNG8G00GZJ000007R
Fn_call_id: 01CSYVRKZDNG8G00GZJ000007R
```

**Comment by rdallman** [comment]
compatibility is the only reason. we can remove once fdks are ready probably (this may well be the case already, I haven't looked in detail though)
