### ISSUE TITLE
Discrepancy between Swagger Fn Model and Fn_go Fn Model

### ISSUE THREAD

**Issue by SamTS** [fnproject/fn#1335]
**Description**
In order to pass information between the Fn server and the Fn CLI, an API over HTTP is used. When using this API to add a new function to an Fn app (POST /v2/fns), there is a discrepancy between the swagger documentation and the actual HTTP commands that the CLI uses. The property 'format:"http-stream"' needs to be part of the JSON data that is passed to the FN server. Formation is, as best as I can tell, the method information is passed between a Fn Function and the Fn Server. Without that 'format' specified, 'format' will default to 'default' and then the function will not be able to be invoked and 'http-stream' is currently the only supported option. As long as one is using the Fn CLI this is fine, but if one wants to the HTTP API directly then this can cause some problems.

On a more exact level, the Swagger documentation for the Fn Model [here](https://github.com/fnproject/fn/blob/master/docs/swagger_v2.yml#L533) and the definition of the Fn Model in Fn Go [here](https://github.com/fnproject/fn_go/blob/master/modelsv2/fn.go#L20) are different.

The simplest fix would be adding to the Swagger file (line 563ish) ``      idle_timeout:
        type: string
        default: "http-steam"
        description: "Payload format sent into function."``

**Comment by rdallman** [comment]
@SamTS thanks for the issue. `format` field is no longer required and has been removed from swagger, per https://github.com/fnproject/fn/pull/1281 - are you on the latest version of fn? the cli may still be defaulting to that format, but fn no longer has the field at all and from fn_go even it should be ignored. we do need to update fn_go, a good reminder! 

can you paste version information and logs please if this is happening on a relatively recent (last week or two) version of fn after checking?

**Comment by rdallman** [comment]
going to close, please re-open with details if this issue persists, thank you!

**Comment by SamTS** [comment]
Ah thanks, just downloaded the new fnServer image from docker and it it worked like a charm with no `format` field needed.
