### ISSUE TITLE
Plugins to extend supported runtimes

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#135]
In gitlab by @mhaji on Jul 18, 2017, 09:35

cc: @ssmith @treeder 

Currently, the supported runtimes are hardcoded into the fn cli. There is some support for adding another runtime, but this involves supplying your own Dockerfile and goes against the goal of abstracting Docker as much as possible (I believe this is a goal).

I'm creating this issue to discuss possibilities for how support for a runtime can be plugged in to fn rather than be built in. The issue now is that changes to a runtime means rolling out a new version of the cli.

**Comment by zootalures** [comment]
See also https://github.com/fnproject/cli/issues/51
https://github.com/fnproject/cli/pull/52

**Comment by rdallman** [comment]
https://github.com/fnproject/cli/pull/369 done?!
