### ISSUE TITLE
AfterFnCreate does not receive the newly created function as argument

### ISSUE THREAD

**Issue by ArtunSubasi** [fnproject/fn#1386]
Extensions can keep track of inserted functions by listening to the FnListener event `AfterFnCreate`. The function AfterFnCreate is called in `datastore.go` within the function `InsertFn`. Before `AfterFnCreate` is called in the line 159, the function is inserted using the datastore in the line 154. 
https://github.com/fnproject/fn/blob/6b8268e19ba5344d7a19a0ebef29282a14e7dd52/fnext/datastore.go#L154

The new function is assigned to the variable `f`. However, `AfterFnCreate` is not called with the new `f`, but with the old variable `fn`:
https://github.com/fnproject/fn/blob/6b8268e19ba5344d7a19a0ebef29282a14e7dd52/fnext/datastore.go#L159

The main problem is that the extensions can not have access to the newly generated function ID, because the ID is not set in the old `fn`: https://github.com/fnproject/fn/blob/6b8268e19ba5344d7a19a0ebef29282a14e7dd52/api/datastore/sql/sql.go#L527

Resolution: The line 154 can be changed so that AfterFnCreate is called with the new `f`. This would be similar to the implementation of the the InsertApp function (line 93). Or copy the new generated ID of the function from `f` to `fn`.

```
fn version
Client version: 0.5.40 is not latest: 0.5.42
Server version:  0.3.648
```

**Comment by denismakogon** [comment]
there's one more similar thing in `AfterFnUpdate`.

**Comment by denismakogon** [comment]
@ArtunSubasi thanks for finding this, fix merged.
