### ISSUE TITLE
[UX] Confusing error messages on various FDK status codes (except 200, 500).

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#1403]
**Description**

Fn returns confusing error message when developers attempt to return various status codes except 200 and 500.
Fn says it's `invalid function response`, however, response from an FDK is valid, but Fn doesn't any allow status code except 200 and 500.

**Steps to reproduce the issue:**
1. Write a function that returns HTTP 400
2. Deploy it
3. Call it

**Describe the results you received:**
```
time="2019-02-14T09:22:52Z" level=info msg="hot function terminating" app_id=01CWSGC5YGNG8G00RZJ0000015 cpus= error="FDK Error, invalid status code 400" fn_id=01CWSGC5Z8NG8G00RZJ0000016 id=01D3NN1P8PNG8G00GZJ0000002 idle_timeout=30 image="denismakogon/test:0.0.1" memory=256
time="2019-02-14T09:22:52Z" level=error msg="api error" action="server.handleFnInvokeCall)-fm" code=502 error="invalid function response" fn_id=01CWSGC5Z8NG8G00RZJ0000016
```

**Describe the results you expected:**
I expect better error message rather than `invalid function response`.

This type of behaviour limits use of Fn for the following use case:
1. user used invalid data - function wants to abort the request with HTTP 400
2. user wants to get some data throught the function, but function found nothing - return HTTP 404.
3. a function wasn't able to authorize to a 3rd party service - return HTTP 401
4. function will return the HTTP 302 Redirect.

and so on.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Output of `fn version` (CLI command):**

```
Client version is latest version: 0.5.51
Server version:  0.3.661
```

**Additional environment details (OSX, Linux, flags, etc.):**

**Comment by denismakogon** [comment]
Sorry, that's really related to an FDK. Closing.

**Comment by rdallman** [comment]
we could maybe make this error more useful when it's just a wrong code (to say `invalid function response: 400 code is invalid` or so), but aside from that yeah it's FDK bug - thanks
