### ISSUE TITLE
fn_linux from releases works fine but issues with shell script CLI

### ISSUE THREAD

**Issue by fadams** [fnproject/fn#1405]
Hello. I'm a total n00b just starting out with fn. Starting with the Quickstart on https://github.com/fnproject/fn after downloading fn_linux 0.5.51 from https://github.com/fnproject/cli/releases and I could get things to run as the QS suggests.

I tried to explore a little more and have come unstuck. One of the things I've wanted to try was starting up the server "directly" as opposed to via the CLI. I ran it with:
```
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8080:8080 \
    --name fns \
    -v ${PWD}/data:/app/data \
    fnproject/fnserver
```
The server appeared to start fine and reports v0.3.661 and running fn version reports
```
Client version is latest version: 0.5.51
Server version:  0.3.661
```
However when I run through the QS instructions again, still using the CLI from release but this time using the server started as above (which is using the same image as previously) I again see "Successfully created app:  myapp" and  fn deploy "appears" to build the hello image fine, however when I get to
```
fn invoke myapp hello
```
It barfs with:
```
{"message":"Container initialization timed out, please ensure you are using the latest fdk / format and check the logs"}

Fn: Error calling function: status 504

See 'fn <command> --help' for more information. Client version: 0.5.51
```
So something is clearly wrong. As I say the server is using the same image as when run with fn start, but I can't really see what I might be missing in my docker run?? As far as I can see it looks essentially the same as the example in https://github.com/fnproject/docs/blob/master/fn/operate/options.md that mounts the Docker socket and I don't have SELinux or apparmor in the equation.

A different problem I'm seeing is with the CLI from the shell script option (QS option 2) which says
```
curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
```
With that when I run through the process of creating my first function (in this case still using fn start to start the server) it all looks good until I get to
```
fn invoke myapp hello
```
where it errors again, but if I use the release version CLI just to run the invoke that works, so it looks like everything apart from the invoke is working fine?

I'm wondering if this is because "latest" is currently broken - the script appears to be using
```
https://api.github.com/repos/fnproject/cli/releases/latest
```
rather than a versioned release so that is plausible but as I say I'm a new user so not sure if it's something I've done or an issue.

If it is a glitch because latest is being used it might be worth putting a warning in the documentation that the script is using a potentially unstable version.

Many thanks and best regards.

**Comment by denismakogon** [comment]
Hi! Let me answer your questions.

First of all, 
> docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8080:8080 \
    --name fns \
    -v ${PWD}/data:/app/data \
    fnproject/fnserver

that's not how Fn started and would not work at all, with this command you're going to get a dead server. There are a lot more configuration required, unfortunately i'm not sure if that's documented well.

That's why you get this:

> {"message":"Container initialization timed out, please ensure you are using the latest fdk / format and check the logs"}

All of this problems would go away if you'd start using Fn with `fn start`, there it a lot logic being hidden behind that command, trust me.

If you'd like to learn how to run Fn in distributed way I recommend to start with Fn helm chart for Kubernetes.

**Comment by rdallman** [comment]
Hey @fadams thanks for trying this out and writing up. It looks like we need to update the documentation on running the server without the cli, there are a few things that we hand off to fn to start it now: https://github.com/fnproject/cli/blob/master/commands/start.go#L57-L67

**Comment by fadams** [comment]
Thanks @rdallman and @denismakogon for the quick reply. Yeah I realise that `fn start` is kind of the recommended way, I guess I've just got a bit of an aversion to "here the magic happens" or "trust me" especially with Docker where you're basically running root equivalent and TBH I see a lot of "unfortunate" images hanging out on Dockerhub, so I tend to like having a bit of an understanding with the intent of reducing privileges where I can.

I'm all for ease of use, but hopefully you can understand the motivation.

It'd definitely be good to have updated documentation for running the server without the CLI, especially if what is currently there is incorrect as it seems to be (I also tried simply copy+paste from the docs https://github.com/fnproject/docs/blob/master/fn/operate/options.md in case my own docker run had finger trouble, but no dice).

I've previously looked at IronFunctions where the server started fine from docker run, so I had assumed fn would work in that way too.

@rdallman thanks for the link I'll take a look through, though TBH --priviliged makes me a little sad. I can appreciate it as the most general thing for container execution, but starting from the point of fewest privileges and working up feels safer than privileged by default, it'd be good if that were on your roadmap or there were other ways to have more control over the privileges of the server.

I don't suppose that you have a response to the other part of my query. As I mentioned previously running the release binary of fn_linux was fine, but using the shell approach to get it
```
`curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh`
```
failed at the `fn invoke` even when I used `fn start` to start the server. Obviously "use the release binary" is a good solution, but it's still niggling me a little why the other approach isn't working, my guess is 'cause the shell approach is pulling "latest", but it'd be good to know, and if that is the case it might make sense either to document that that approach is pulling latest or to have the script pull the latest versioned release.

Hope I don't come across too picky - these comments are intended to be constructive. FWIW this project looks really good and it's on the short list of FaaS projects we're looking to use, so I'm keen to kick the tyres a little.

Many thanks again for the replies, cheers!

**Comment by rdallman** [comment]
the script should be downloading latest but of course, computers happen. i didn't see a version posted related to the error around invoking the release install, I assume you checked this, but double checking here that they match? the install script should download the exact same binary though if that's the source of confusion. hope this helps.

**Comment by fadams** [comment]
Hi again, sorry I'm afraid that issue with the script was my bad. I checked and it **is** grokking for the **latest version** and then using the releases. The issue that I was **actually** running into was the one I referred to https://github.com/fnproject/fn/issues/1408.

Thanks so much for the link you previously sent on start.go I was able to start up the server with this
```
docker run --rm -i \
    --name fnserver \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8080:8080 \
    -v ${PWD}/data:/app/data \
    -v ${PWD}/iofs:/iofs \
    -e FN_IOFS_DOCKER_PATH=${PWD}/iofs \
    -e FN_IOFS_PATH=/iofs \
    --entrypoint=./fnserver \
    fnproject/fnserver
```
I was previously missing the iofs stuff, which doesn't seem to be documented anywhere yet, so I'm assuming it's a fairly new thing? Even googling for "FN_IOFS_DOCKER_PATH" and the only hit seems to be the start.go so I guess I shouldn't feel bad for missing that :-) BTW I'm not criticising the docs, they are really good in general, I think I'm just unlucky/stupid for not following the instructions blindly - my learning style tends to be a little non-linear.

The entrypoint flag above is interesting if I omit it and use the default entrypoint it actually seems to work OK but I get a lot of additional warnings on startup. My guess is that the default entrypoint is for the Docker-in-Docker way of doing things and the ./fnserver is the one to use when using the host's Docker socket.

Anyway thanks again for that tip-off, _really_ helpful.


I'm also interested to know what the thoughts of the project team are on my comment "starting from the point of fewest privileges and working up feels safer than privileged by default," I guess for a system interacting with Docker there is always likely to be a need to at least be a member of the docker group which implies elevated privileges in the container, but I am a bit concerned that --privileged is the default rather than an option. It doesn't seem to be required at least for the basic use cases from the tutorial and as `fn start` seems to be mounting the host's Docker socket rather than using DnD it doesn't seem necessary to keep --privileged.

Call me paranoid, but these are the sort of things that can often get sticky on corporate IT when negotiating to pull a system through to production - I can practically hear my lot sucking air through their teeth and muttering "--privileged???, computer says no!"

**Comment by carimura** [comment]
@fadams thanks for the detailed writeups.

@denismakogon -- let's make sure our docs get updated before closing this issue.

CC @michael-w-williams

**Comment by rdallman** [comment]
> Call me paranoid, but these are the sort of things that can often get sticky on corporate IT when negotiating to pull a system through to production - I can practically hear my lot sucking air through their teeth and muttering "--privileged???, computer says no!"

for production installs we don't recommend using `fn start` at all, which allows the possibility of not even using docker in docker at all or configuring docker more securely in other fashions. however, for the getting started experience, the most appealing option is docker in docker to get cross platform something working, which requires `--privileged` -- it's expected that fn start is only run on laptops, to be clear, while of course laptops should be secured as well, we're not talking production in that case. if there's a clear path to having something more secure that works as well across all platforms for getting users started, we're of course open to ideas and PRs - I hope that clarifies the stance on privileged and production however.

**Comment by rdallman** [comment]
can we open separate docs PR @carimura ? - most of this issue is unrelated to us needing to add more flags to running fn outside of fn start

**Comment by rdallman** [comment]
https://github.com/fnproject/docs/pull/46
