### ISSUE TITLE
No logging recorded (sometimes) for a function call

### ISSUE THREAD

**Issue by paulfelix** [fnproject/fn#1406]
When invoking my Python function, sometimes I get the logging output with `fn get logs app func last`, but many times I don't. I *always* see the logged output from my function in the fnserver debug logging output, so that tells me the function itself is behaving properly.

Steps:
1. Invoke a Python function.
2. Check the logs: `fn get logs app func last`
3. Repeat

FN version:
Client version: 0.5.45 is not latest: 0.5.51
Server version:  0.3.661

Platform: OSX
Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

Docker version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by paulfelix** [comment]
Here are some more findings:

When I invoke a function and see the expected logging output with `fn get logs app func last`, I see the following in fnserver debug log:

```
time="2019-02-14T19:34:00Z" level=info msg="starting call" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 container_id=01D3PR0PWFNG8G00GZJ000000A fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWENG8G00GZJ0000009
time="2019-02-14T19:34:00Z" level=debug msg="Log to stdout\n" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR0PWENG8G00GZJ0000009 fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWENG8G00GZJ0000009 image="iad.ocir.io/renesysinternetintelligence/hello:latest" user_log=true
time="2019-02-14T19:34:00Z" level=debug msg="Log to stderr\n" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR0PWENG8G00GZJ0000009 fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWENG8G00GZJ0000009 image="iad.ocir.io/renesysinternetintelligence/hello:latest" user_log=true
time="2019-02-14T19:34:00Z" level=debug msg="2019-02-14 19:34:00,322 - root - INFO -  [14/Feb/2019:19:34:00 +0000] \"POST /call HTTP/1.1\" 200 188 \"-\" \"Go-http-client/1.1\"\n" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR0PWENG8G00GZJ0000009 fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWENG8G00GZJ0000009 image="iad.ocir.io/renesysinternetintelligence/hello:latest" user_log=true
time="2019-02-14T19:34:00Z" level=debug msg="Got resp from UDS socket" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWENG8G00GZJ0000009 resp="&{200 OK 200 HTTP/1.1 1 1 map[Content-Type:[application/json] Content-Length:[25] Date:[Thu, 14 Feb 2019 19:34:00 GMT] Server:[Python/3.6 aiohttp/3.4.4] Fn-Http-Status:[200]] 0xc42018e240 25 [] false false map[] 0xc420429900 <nil>}"
time="2019-02-14T19:34:00Z" level=debug msg="docker pause" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR0PWFNG8G00GZJ000000A cpus= fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR0PWFNG8G00GZJ000000A idle_timeout=30 image="iad.ocir.io/renesysinternetintelligence/hello:latest" memory=256 stack=Freeze
```

When I don't see the logged output, I see the following in the fnserver debug log:

```
time="2019-02-14T19:35:22Z" level=info msg="starting call" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 container_id=01D3PR2V3BNG8G00GZJ000000D fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR387KNG8G00GZJ000000F
time="2019-02-14T19:35:22Z" level=debug msg="docker unpause" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR2V3BNG8G00GZJ000000D cpus= fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR2V3BNG8G00GZJ000000D idle_timeout=30 image="iad.ocir.io/renesysinternetintelligence/hello:latest" memory=256 stack=Unfreeze
time="2019-02-14T19:35:22Z" level=debug msg="Got resp from UDS socket" action="server.handleFnInvokeCall)-fm" app_id=01D39Y96VVNG8G00GZJ0000001 fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR387KNG8G00GZJ000000F resp="&{200 OK 200 HTTP/1.1 1 1 map[Fn-Http-Status:[200] Content-Type:[application/json] Content-Length:[25] Date:[Thu, 14 Feb 2019 19:35:22 GMT] Server:[Python/3.6 aiohttp/3.4.4]] 0xc420352e40 25 [] false false map[] 0xc420429300 <nil>}"
time="2019-02-14T19:35:22Z" level=debug msg="Log to stdout\n" app_id=01D39Y96VVNG8G00GZJ0000001 container_id=01D3PR2V3BNG8G00GZJ000000D fn_id=01D39Y96XBNG8G00GZJ0000002 image="iad.ocir.io/renesysinternetintelligence/hello:latest" tag=stderr
time="2019-02-14T19:35:22Z" level=debug msg="Log to stderr\n" app_id=01D39Y96VVNG8G00GZJ0000001 container_id=01D3PR2V3BNG8G00GZJ000000D fn_id=01D39Y96XBNG8G00GZJ0000002 image="iad.ocir.io/renesysinternetintelligence/hello:latest" tag=stderr
time="2019-02-14T19:35:22Z" level=debug msg="2019-02-14 19:35:22,115 - root - INFO -  [14/Feb/2019:19:35:22 +0000] \"POST /call HTTP/1.1\" 200 188 \"-\" \"Go-http-client/1.1\"\n" app_id=01D39Y96VVNG8G00GZJ0000001 container_id=01D3PR2V3BNG8G00GZJ000000D fn_id=01D39Y96XBNG8G00GZJ0000002 image="iad.ocir.io/renesysinternetintelligence/hello:latest" tag=stderr
time="2019-02-14T19:35:22Z" level=debug msg="docker pause" app_id=01D39Y96VVNG8G00GZJ0000001 call_id=01D3PR2V3BNG8G00GZJ000000D cpus= fn_id=01D39Y96XBNG8G00GZJ0000002 id=01D3PR2V3BNG8G00GZJ000000D idle_timeout=30 image="iad.ocir.io/renesysinternetintelligence/hello:latest" memory=256 stack=Freeze
```

I notice two things here:
1. When the logging works, the fnserver debug output attaches `user_log=true` to the function log messages, and they are recorded *before* the message "Got resp from UDS socket" 
2. When the logging does not work, the fnserver debug output attaches `tag=stderr` to the function log messages, and they appear *after* the message "Got resp from UDS socket"

**Comment by denismakogon** [comment]
Thanks for filing an issue. One thing I'd like to note, if you do logging inside of a Python function you'd need to flush your messages ASAP, i.e., `print("blah", flush=True, file=sys.stderr)`.

**Comment by paulfelix** [comment]
Yes, the function flushes the messages.

**Comment by rdallman** [comment]
@paulfelix logs API itself is scheduled for deprecation, we recommend using debug logs as you are now or using a syslog url https://github.com/fnproject/docs/blob/master/fn/operate/logging.md#remote-syslog-for-functions - sorry for the hitch, been meaning to get around to this removal

**Comment by paulfelix** [comment]
I tried to use the syslog url approach with no luck. Is there a way to set that up on OSX?

I'm also not convinced that the problem goes away if one uses the syslog url, which I'm guessing is further down the pipeline. Thus, log messages might get lost either way.  @carimura mentioned missing logs using papertrail.

**Comment by rdallman** [comment]
we're using the docker logging drivers, I'd expect this to work on OSX, configuration is no different. it's certainly possible that syslog can miss logs, though I think there's quite a lower probability provided a stable connection, we're attaching to the container and not swapping out each task as we are with the current logging API stuff, which I suspect is likely responsible for some of the missing logs on that end (at least, I'd surmise that the source of the problem for missing logs with either one is different than the other).

**Comment by rdallman** [comment]
gonna close since logs are gone, let us know if we can help getting logs hooked up!
