### ISSUE TITLE
fn invoke doesn't seem to flush stdout

### ISSUE THREAD

**Issue by fadams** [fnproject/fn#1408]
This is related to what I observed in https://github.com/fnproject/fn/issues/1405

Perhaps slightly obtusely I thought it'd be fun to create a Dockerised version of the fn CLI the Dockerfile is:
```
FROM debian:stretch-slim

# Install fnproject/fn CLI note that this can exec Docker commands
# so install docker-ce and bind-mount Docker socket in run command.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    curl ca-certificates apt-transport-https gnupg2 software-properties-common && \
    # See Quickstart/CLI tool from https://github.com/fnproject/cli
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    apt-key fingerprint 0EBFCD88 && \
    apt-add-repository "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable" && \
    apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y docker-ce-cli && \
    curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh && \
    # Remove the packages used for installation
    apt-get clean && \
    apt-get purge -y \
    curl ca-certificates apt-transport-https gnupg2 software-properties-common \
    tzdata readline-common pinentry-curses && \
    apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/bin/fn"]
```
It's basically just installing docker-ce-cli and using the script based install of the fn CLI.

I created a launch script called fn and put it in my path as follows:
```
mkdir -p $HOME/.fn
docker run --rm -i \
    -e FN_API_URL=http://$(hostname -I | awk '{print $1}'):8080 \
    --group-add $(cut -d: -f3 < <(getent group docker)) \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -u $(id -u):$(id -g) \
    -v /etc/passwd:/etc/passwd:ro \
    -v $PWD:$PWD:rw \
    -v $HOME/.fn:$HOME/.fn:rw \
    -w $PWD \
    fn $@
```
I'm finding that everything seems to be working perfectly running through the Quickstart with this except when I do:
```
fn invoke myapp hello
```
Which just hangs.

It was driving me a bit nuts for a while but then I tried a few variations, for example:
```
echo '{"name":"Johnny"}' | fn invoke myapp hello
```
returns 
```
{"message":"Hello Johnny"}
```
exactly as expected and
```
echo | fn invoke myapp hello
```
returns
```
{"message":"Hello World"}
```
again as expected, and if I modify the first line of my docker run to
```
docker run --rm -it \
```
that is with -it instead of -i so I have a TTY then
```
fn invoke myapp hello
```
returns
```
{"message":"Hello World"}
```
but with -it I then can't pipe from stdin.

With those symptoms it looks very likely then that fn invoke isn't flushing stdout.

I appreciate it might be a bit wacky, as the CLI is easy enough to download and Dockerising it is probably overkill, but hey docker native and all that :-)

I'd appreciate any thoughts on this observation.
Many thanks.

**Comment by rdallman** [comment]
as far as I know, go's exposed stdout that we're using is not buffered and shouldn't need flushing -- we're not doing any shenanigans either. the code is https://github.com/fnproject/cli/blob/master/client/invoke.go#L107 you might add a flush there to stdout https://golang.org/pkg/os/#File.Sync to check somewhere around https://github.com/fnproject/cli/blob/master/commands/invoke.go#L119 

the outlined issues seem more related to the docker command's handling of stdin, `-i` exists to allow stdin, so am confused why it's not working, perhaps we could read it differently, we're only reading if it's in pipe mode, that could easily be broken by running the cli in docker I imagine, code is here if you would like to tinker: https://github.com/fnproject/cli/blob/master/commands/invoke_others.go

**Comment by fadams** [comment]
Oh this definitely isn't a unique thing to fn, if you google for "docker flush stdout" there are quite a few hits along the lines of this https://www.google.co.uk/search?q=docker+flush+stdout&ei=qQlnXJClIKaU1fAPyfaq0Ac&start=0&sa=N&ved=0ahUKEwjQnbzZs77gAhUmShUIHUm7Cno4PBDy0wMIdg&biw=1429&bih=1050 and http://www.pixelbeat.org/programming/stdio_buffering/ in short stdout is buffered (line buffered if connected to a terminal).

For many use cases allocating a TTY with -t is enough and you see lots of usage of -it flags in docker run, and as I mention above that works fine with the basic
```
fn invoke myapp hello
```
but when you allocate a TTY you can no longer pipe from stdin so
```
echo '{"name":"Johnny"}' | fn invoke myapp hello
```
stops working.

I could probably fiddle with my launch script to use different flags depending on stdin, but the reason I posted this was in case there was perhaps a missing "\n" somewhere in the fn invoke path which would (I think) force a flush.

If you have any time it'd be good if you could try out the Dockerised stuff I posted in case I've missed something obvious/stupid. It's kind of an interesting edge case.

**Comment by rdallman** [comment]
@fadams this should now be fixed https://github.com/fnproject/cli/pull/538 - thanks, this helps ux
