### ISSUE TITLE
DB password written to log 

### ISSUE THREAD

**Issue by cdraper-CS** [fnproject/fn#1419]
**Description**

The password in the database URL is put in the log at info level, which is problematic for sensitive data. 

This only happens for one log message (`Connecting to DB`) - in others the password is masked.

Issue #1071 previously identified this issue and PR #1072 was intended to fix the problem by masking the user/password, but missed this log message.

**Steps to reproduce the issue:**
1. Start up server using FN_DB_URL with a user:password in it, then look in logs

**Describe the results you received:**

```
time="2019-02-24T20:19:15Z" level=info msg="Connecting to DB" url="postgres://USER:PASSWORD@postgres:5432/functions?sslmode=disable"
time="2019-02-24T20:19:26Z" level=error msg="couldn't ping db" error="dial tcp: lookup postgres on 127.0.0.11:53: no such host" url="postgres://USER:***@postgres:5432/functions?sslmode=disable"
```

**Describe the results you expected:**

Password (and ideally user name too) is masked.

**Output of `fn version` (CLI command):**

Using fnproject/fnserver:0.3.665

**Comment by rdallman** [comment]
d'oh! thank you!
