### ISSUE TITLE
Can't install on Digital Ocean Ubuntu Droplet

### ISSUE THREAD

**Issue by locohost** [fnproject/fn#1491]
**Description**

Trying to use the curl install command on a new Digital Ocean Ubuntu droplet use the web console. Pasting in the curl command does nothing.

**Steps to reproduce the issue:**
1. Create a new DO Droplet, Ubuntu
2. Open a web console from your DO droplet dashboard
3. Install Docker
4. Cut/paste the fn install command from instructions at this site.

**Describe the results you received:**

Install command does not install fn. Nothing happens in console

**Describe the results you expected:**

fn should install and show version as instructions state

**Additional information you deem important (e.g. issue happens only occasionally):**

After trying to run curl installer I see...

Either your platform is not easily detectable or is not supported by this installer script (yet - PRs welcome! [fn install]).

Please visit the following url for more detailed installation instructions:

https://github.com/fnproject/fn

**Output of `fn version` (CLI command):**

```
fn: command not found
```

**Additional environment details (OSX, Linux, flags, etc.):**

**Comment by locohost** [comment]
I'm on a Windows 10 laptop. I have Git bash installed. I had to use that, ssh to the DO droplet and do the install in bash. This appears to be working. The DO web console does not.

**Comment by carimura** [comment]
thanks for the report and follow up. let us know if you need any help along the way. also find us in slack.fnproject.io
