### ISSUE TITLE
Node FDK

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#15]
In gitlab by @treeder on May 11, 2017, 17:11

* [ ] our common syntax
* [ ] support for lambda syntax too (probably move our current lambda support into the FDK)
* [ ] both default and hot JSON functions

For Lambda, could use mostly the same code, but create a `handleLambda` function to handle AWS specific syntax. Then we don't have two Node libs hanging around.

**Comment by treeder** [comment]
curious what @rdallman 's comments were on here... ;)

**Comment by rdallman** [comment]
https://github.com/fnproject/fdk-node
