### ISSUE TITLE
Duplicate agent_submit spans in agent and lb_agent

### ISSUE THREAD

**Issue by bharadwr** [fnproject/fn#1517]
There's two spans with the same name, namely in agent.go and lb_agent.go. 

https://github.com/fnproject/fn/blob/4ccd8fa0c63e65aa4b35c1f76cbd7db919f59c7c/api/agent/agent.go#L250
https://github.com/fnproject/fn/blob/1fb78ed8362693105aee48a506129e6776d1a3a8/api/agent/lb_agent.go#L200

Should this be renamed? Someone might find a span on jaeger and go down the wrong rabbit hole if theyre debugging (I certainly did)

**Comment by rdallman** [comment]
yes, please - lb_agent likely has a few duplicates from agent, `lb_agent_submit` is probably sufficient?

**Comment by bharadwr** [comment]
Yep, I'll make that change. Lemme see if there's a few more duplicate traces, and I'll add them all to one ticket.

**Comment by bharadwr** [comment]
![Screen Shot 2019-06-27 at 11 00 22 AM](https://user-images.githubusercontent.com/25177182/60289336-03243b80-98cb-11e9-805c-2bdd3cf5a3f6.png)
It's gonna look like this, added some more span attributes that are probably useful
