### ISSUE TITLE
Path prefix matching for routes

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#170]
It'd be great to be able to treat a route as a prefix when matching, rather than having to match exactly.  For example:

```
  /r/my_app/some-path-prefix/<anything>/<at>/<all>  ->  myfn
```

This doesn't mandate that path params to be evaluated by the fn platform, as long as the entire request URL is passed into the function we can do that ourselves.

This request would be especially useful for https://github.com/bbilger/jrestlesss - we can define an application with a base-url and many sub-resources hosted in a single function.  This is hard work at the moment as we need to create a lot of routes in the fn platform, and are not able to dynamically add a route at runtime.

**Comment by Empty2k12** [comment]
One example of a use case for this is a function that serves a static file: You'd expect the filepath to look something like `domain.local/static/main.css` but this is currently not possible with `fn`. Instead I have to resort to hacky file serving aka `domain.local/static?file=main.css` which works but is semantically bad.

Another example is a function serving a Single Page Application that works with client-side routing á la React Router. I want the `root` function to be able to read the path and respond based on that (e.g. `domain.local/show/all` or `domain.local/show/1` handled by JavaScript and not server side)
