### ISSUE TITLE
Simple per function monitoring/metrics

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#19]
In gitlab by @treeder on May 11, 2017, 17:25

- CPU
- memory

**Comment by rdallman** [comment]
we're gonna do this, dk why it got closed

**Comment by denismakogon** [comment]
@rdallman Probably better include CPU, RAM into `/calls` response?

**Comment by rdallman** [comment]
yea, not clear from description but I agree, they're also getting spurted to prometheus now too.
