### ISSUE TITLE
Release management support for external users (and platform providers)

### ISSUE THREAD

**Issue by jan-g** [fnproject/fn#201]
Let's say I'm a client using FooLang to develop my own functions. The platform is vibrant and undergoing near-constant revision.

For many customers, constant API churn of the FooLang platform is going to be a turn-off. As a customer, I'd like to be able to pin my released functions to a particular version of a language runtime; as a runtime supplier, I'd like to be able to ship a :1-latest, :2-latest alongside :1.0.1, :1.1.0, etc.

Possibly one simple way to do this is to add versions (or image) pegging to the func.yaml. For instance, possibly something like:

```
name: mystuff/myfunc
version: 0.0.1
timeout: 30s
format: http
# ... etc ...
runtime: java
runtime-run-version: 1-stable
```

Maybe these keys (`runtime-build-image`, `runtime-run-image`, etc.) could be omitted from the standard `fn init` output, but a savvy customer who cares about backwards API compatibility can set them if required.

(Incidentally this'd also offer a simple avenue for runtime maintainers to set up simple integration tests for new versions of their runtimes.)

This'd also be a pretty trivial mechanism for extending `fn build` to support a "package-only" mode, where it injects pre-built stuff into a docker image of the end user's choosing.

**Comment by treeder** [comment]
I think this was already done with build_image and run_image.
