### ISSUE TITLE
Support HTTP-over-TCP protocol for hot functions

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#208]
At this moment each hot function accepts requests through http-over-stdin protocol.
This means that each function should implement http-over-stdin parser (it's native for go only AFAIK).
In order to simplify developer experience and choice of http frameworks (to build http servers) we might consider to support HTTP-over-TCP protocol.

How it's different?
------------------
For HTTP protocol each time user submits a request its body being used to form HTTP request that would be dumped to STDIN

For HTTP-over-TCP each request would be written to a TCP socket, function (basically http server) will recognise it as regular HTTP request accepted through network

Impacts to COE orchestration?
-------------------------------
Each container must expose port (random) internally in order to establish TCP connection between FN server and function.

**Comment by rdallman** [comment]
@denismakogon json fixes the crux of this issue? there's also some work on #713
