### ISSUE TITLE
Functions pipeline

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#25]
In gitlab by @denismakogon on May 17, 2017, 17:31

For now we can create pipeline through webhooks (i.e. do HTTP call to another webhook from function). But the problem is that each time function called request goes through control plane (few hops expected), better to have an ability to let function to talk through internal Docker network (maybe define specific network for N functions?), that would allow to reduce networking load.

**Comment by treeder** [comment]
Closing because flow.
