### ISSUE TITLE
figure out timeout & launch policy for hot & cold functions

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#274]
at present we have:

cold
-----
* wait up to the call timeout to launch a container (and don't run if `> timeout / 2` elapsed)

hot
-----
* wait 100ms for a free container
* launch a container & wait for any free container up to the call timeout (and don't run if `> timeout / 2` elapsed

this policy requires synthesizing 2 things:

one is, under what conditions should we even launch hot containers? 

with the current policy if nothing is free in 100ms (hot), we attempt to launch unconditionally. this can lead to launching a lot of containers for a route, but eventually there is an equilibrium with the offered load to where there are free slots when requests come in and it's no longer necessary to launch containers. 100ms is just a magic number to apply some back pressure.

the other thing is, how long should we wait for ram to become available / for a slot to become free? since we are stopping things from executing if `> timeout / 2` has elapsed, it seems like we should probably at most only wait this long to begin with. when a machine is at capacity ram-wise, there are likely hot containers up for certain routes, so immediately timing out all tasks that can't find a slot immediately seems wrong, too (there's at least some point in time where it would be faster to wait than to retry against another fn server).

and another thing to keep in mind is that as alluded to, we want to timeout as quickly as possible if we have a good approximation that we aren't going to be able to run a certain call within a certain time window, so that the call could run on another fn server as quickly as possible.

not necessarily digging for code here, think we should discuss the policy at a high level and then go implement it after we all/mostly agree.

**Comment by skinowski** [comment]
Should we close this? The wait policy was changed to the following in the last few weeks:

- 100 ms is removed
- Now we aggressively launch hot containers based on slots.isNewContainerNeeded(), but this
aggressiveness is dampened by LIFO queue which times out (IdleTimeout) idle (AKA unnecessary) containers.

isNewContainerNeeded() potentially needs more work and fine tuning going forward. Currently it considers a few metrics to decide if a new container is needed:

1) num of waiters
2) num of "starting" containers to avoid starting too many in parallel
3) num of currently running containers
4) wait latency
5) wait latency compared to estimated run latency given running container count
5) container start latency

Maybe there needs to be a optimization towards low latency versus optimization towards low consumption. Today, this is geared more towards low latency, but if a user is choosing hot containers, that implicitly means low latency. So, this policy may be OK.

NOTE: isNewContainerNeeded() is run by one go routine per slot.

**Comment by rdallman** [comment]
i'm sure users that run into policy issues will open new issues instead of adding comments here, we could likely link all those tickets to this and close them. I imagine this will be an ongoing issue as people use this thing for various use cases and we likely won't ever satisfy everyone. the discussion of the policy over time is likely informative to users that are running into such issues, and for us too in amending it. anyway, i'm willing to leave it open for that reason, even if there isn't any immediate work related to this at any given point in time. but for the latter reason, we can close it if we want to and refer back to this when issues arise instead. up to... us? I'd vote leave open.
