### ISSUE TITLE
make async robust

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#281]
there are 2 levels to this, really, that could be taken care of in one fell swoop.

level 1: the current reserve-delete semantics are such that there exists a point in time where a task could not be run to completion or stored in the db at all and at the same time there is no message on the mq to ensure that this task runs at least once.

level 2: the way the queues are designed we are bottlenecked on 1 queue, which ultimately will not scale for larger deployments + redis will also not work for large deployments. we need at least 1 level of sharding, and likely we want each route to have its own queue so we can do things like process hot functions on that queue really fast. we are also currently storing an entire json serialized `*models.Call` in there which is huge and message queues don't tend to do well with large things. we could probably just store the id in the mq.

i.e. not only is the way that we have the queues set up insufficient, but so are our semantics around using them in fn.

level 1, we need to store a task in the db upon receiving it (with status=queued) and then re-work when we get to delete a message for good. ultimately, it would be nice to have ran once semantics, which we should be able to do by using the db and updating the status. i can think of various ways to design this, so omitting the details.

level 2, maybe we need to play with kafka? unfortunately, it's not ideal for timestamp based job processing like it appears we want to offer (delay / timeout based). or ya know, build our own queue.

another issue with async is that if there's some kind of error like 'image not found' right now we try to run that call forever even though we may never be able to, need to clean stuff like this up too (add to `call.Start`)

**Comment by treeder** [comment]
This still an issue?

**Comment by denismakogon** [comment]
One more thing. With the current implementation, the async call reaches `success` status just in a matter of milliseconds, but the actual execution may still be in progress. So, calls API is consistent only for sync calls (can be a source of truth, you can get an actual execution status). For async functions,  calls API can state that request was accepted, but not completed.

Side note. Call object can't be a proof of execution even if sync function really makes each call can be represented as function's execution state. So, i think we need to split current calls into at least two relative APIs:
 - execution requests API as proof of execution acceptance
 - execution state API as a source of function's lifecycle state

thoughts?
