### ISSUE TITLE
differentiate timeout-while-running vs timeout-before-running

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#286]
if there's no output, and a call times out, it's impossible to discern from the response alone whether the call was started or not. it would be nice if we used a different status code or something so that users could quickly know that it didn't run and they should run it elsewhere, instead of just assuming every function is idempotent.

**Comment by skinowski** [comment]
Now, we have 503 for requests that time out before start (#518), may I close this ticket?

**Comment by rdallman** [comment]
thanks
