### ISSUE TITLE
How should we handle CORS?

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#311]
Kind of thinking we should just wildcard enable it by default, seems like almost all modern apps do this now. 

And perhaps have a way for user to restrict it if they like, but default is open. 

Some info on Lambda's handling of it: https://stackoverflow.com/questions/31911898/configure-cors-response-headers-on-aws-lambda

**Comment by DrewRay** [comment]
ideally you would want to echo back the whitelisted set of domains for CORS.  returning a * prevents you from using authorization in many browsers. 

FROM https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS 

> **Credentialed requests and wildcards**
> 
> When responding to a credentialed request, the server must specify an origin in the value of the Access-Control-Allow-Origin header, instead of specifying the "*" wildcard.
> 
> Because the request headers in the above example include a Cookie header, the request would fail if the value of the Access-Control-Allow-Origin header were "*". But it does not fail: Because the value of the Access-Control-Allow-Origin header is "http://foo.example" (an actual origin) rather than the "*" wildcard, the credential-cognizant content is returned to the invoking web content.
> 
> Note that the Set-Cookie response header in the example above also sets a further cookie. In case of failure, an exception—depending on the API used—is raised.
> 

is this something we could configure in the YAML for each function? would it just be an array of allowed options defaulting to *.

**Comment by zootalures** [comment]
Repoening this as the change above doesn't impact routes, only the API - I think we need to deal with this more elegantly for function calls

**Comment by johndevs** [comment]
I've also tried everything @cfsilence tried, also not getting the access control headers through.

My expectation was that:
```
 OutputEvent.fromBytes(response.bytes, status, contentType, Headers.fromMap([ 
     'Access-Control-Allow-Origin' : '*'
     'x-foo' : 'bar' 
]))
```
would do the trick, but somehow the headers get lost.

How are one supposed to use a) customer headers b) access control headers?

**Comment by rdallman** [comment]
Thanks for the bug report, that should work as outlined: users should be able to set headers on the response from a function. There are some tests that verify this is possible and I have some confidence that works at the fn level - it smells like this issue is at the fdk or function level. can dig into this to debug, some questions that may help though: the code above is using an fdk to do this? an http trigger? which version of the fdk is being used?

**Comment by johndevs** [comment]
@rdallman Tested with a  http trigger and the java fdk 1.0.72

**Comment by zootalures** [comment]
Ah if your using triggers you need to set the HTTP headers slightly differently now pull in a HTTPContext as a parameter and set CORS  the headers there

**Comment by abhirockzz** [comment]
I think @zootalures was referring to `com.fnproject.fn.api.httpgateway.HTTPGatewayContext`. Documentation - https://github.com/fnproject/fdk-java/blob/master/docs/HTTPGatewayFunctions.md

**Comment by johndevs** [comment]
Yes, I can confirm updating the headers in HTTPGatewayContext works.

**Comment by rdallman** [comment]
@johndevs excellent, thanks. I think we can document this issue in our docs and then close it?
