### ISSUE TITLE
Issue with new streaming responses

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#326]
I have a function that failed halfway through, my browser got half the response then it crapped out. Then an error json halfway through:

```html
<!DOCTYPE html>
--
  | <html>
  | <head>
  | <meta charset="UTF-8">
  | <title>My page</title>
  | </head>
  | <body>
  | <h1>My page</h1>
  | <p>This is my app. It may not be the best app, but it&#39;s my app.&lt;br/&gt;&lt;br/&gt;And it&#39;s multilingual!</p>
  | <div>
  | <div><a href="{"error":{"message":"container exit code 1"}}
```

It should have 50X'd back to the user rather than return anything at all. 

```
ERRO[2712] api error                                     action="server.handleRunnerRequest)-fm" app=helloapp code=502 error="container exit code 1"
```

Also, there's no call_id in that log line to pull up the container logs. 

 This should return:

- [ ] 500 internal server error
- [ ] error JSON only

**Comment by treeder** [comment]
Still see this, pretty ugly (and unusable) when a function errors halfway through.

**Comment by treeder** [comment]
![screen shot 2018-01-05 at 1 05 41 pm](https://user-images.githubusercontent.com/75826/34628465-514d166a-f219-11e7-85c4-6e74260e1e2a.png)

**Comment by rdallman** [comment]
that one specifically i think the fix is separate [from buffering], we need to watch to see if bytes have been written and not write the error if they have. even if we have buffering we need that.

**Comment by treeder** [comment]
To be clear here, the problem is that a failed function returns a `200` status and a garbage response. If a function fails at any point, it should be a 500 and return a JSON error response.

**Comment by skinowski** [comment]
Aside from the 200/500 issue above, I'll probably end up a adding a configurable system wide setting (eg. buffer size of 1-10MB) along with stream of/on option per route.
