### ISSUE TITLE
Better docs for main CLI commands

### ISSUE THREAD

**Issue by carimura** [fnproject/fn#328]
fn init, run, deploy, call

**Comment by treeder** [comment]
this still an issue?

**Comment by carimura** [comment]
not that I can easily find. I think I'll do a full sweep of the docs in the next week, stand by.

**Comment by rdallman** [comment]
now it's part of the cli itself, `--help` on any command (https://github.com/fnproject/cli/blob/master/commands/deploy.go#L27), and more holistic experience in various getting started... so gonna close
