### ISSUE TITLE
Malformed HTTP headers for async hot functions

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#329]
1. When logging incoming request headers in async hot function content length defined as `Fn_header_content_length` instead of `Content-Length`. Moreover all HTTP 1.0 spec headers are prefixed with `FN_`:
```
Fn_header_accept
Fn_header_content_type
Fn_header_content_length
```
2. App config included into headers
App info:
```
{
	"config": {
		"pg_db": "emokognition",
		"pg_host": "10.0.2.15",
		"pg_port": "5432",
		"pg_pswd": "postgres",
		"pg_user": "postgres"
	},
	"name": "emokognition"
}
```
http headers logged inside hot func
```
Pg_host: [10.0.2.15]
Pg_user
Pg_db: [emokognition]
Pg_port: [5432]
```

If this meant to be expected behaviour it doesn't look like documented.
When running same hot function but sync everything works okay.

**Comment by rdallman** [comment]
sure @denismakogon ? did you test? i think the casing is still inconsistent for async but I haven't tested

**Comment by denismakogon** [comment]
At first, it looked like it worked as expected, but it appeared that FDK does all messy work for cleaning up headers.

**Comment by rdallman** [comment]
#370 fixes but haven't gotten around to updating it for some time
