### ISSUE TITLE
Test and update all the lambda stuff

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#39]
In gitlab by @treeder on May 24, 2017, 15:32

The Node Lambda stuff was updated to follow the new workflow, but not Python or Java. Those should be converted to the new style which is essentially just this:

```
fn init --runtime lambda-node <DOCKER_HUB_USERNAME>/lambda-node
```

Then they'd follow the regular workflow from that point on. 

Also, need to test and ensure the `fn import` command works still.

**Comment by treeder** [comment]
Will be doing this as part of node fdk, s
