### ISSUE TITLE
Docs recommending `brew` for MacOS install result in outdated version

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#391]
This is already catching people out and causing support load.  The version installed by brew is extremely out of date and doesn't even work for the basic tutorials.

**Comment by msgodf** [comment]
Agreed, until there is a working and stable version in homebrew, we shouldn't tell people to use it.

**Comment by fxcoudert** [comment]
_“extremely out of date”_ = released 23 days ago 😭

**Comment by rdallman** [comment]
thanks! resolved now.
