### ISSUE TITLE
strive for go lint 100%

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#400]
https://goreportcard.com/report/github.com/fnproject/fn is pretty useful for running an OSS project

we should probably go through and make go lint perfectly happy because it's the 'right' thing to do ultimately; enforcing comments for exported methods, mostly, so our GoDoc will be purrty. after we do this we can go lint our CI builds and it will enforce contributors to document their code, as well, without us having to ask (i.e. it's a requirement). should just be a day exercise, lots missing atm :)

**Comment by skinowski** [comment]
Minor improvements: https://github.com/fnproject/fn/pull/475

**Comment by rdallman** [comment]
oops, searched `golint` and didn't find this, closing for #1064
