### ISSUE TITLE
Does not work with docker-toolbox

### ISSUE THREAD

**Issue by rogergl** [fnproject/fn#404]
Is it expected that it does not work with the latest docker-toolbox release on Mac OS X ?

The output I get, as soon as I execute fn start is:

```mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
time="2017-10-07T07:31:43Z" level=info msg="datastore dialed" datastore=sqlite3 max_idle_connections=256
time="2017-10-07T07:31:43Z" level=error msg="Could not open BoltDB file for MQ" dir=/app/data error="invalid argument" mq=bolt
time="2017-10-07T07:31:43Z" level=fatal msg="Error initializing message queue." error="invalid argument"
2017/10/07 09:31:43 error: processed finished with error exit status 1
```

**Comment by denismakogon** [comment]
Recently tried, worked.
Docker version:
Version 17.09.0-ce-mac35 (19611)
Channel: stable
```
LOG_LEVEL=ERROR PORT=9000 ./functions 

        ______
       / ____/___
      / /_  / __ \
     / __/ / / / /
    /_/   /_/ /_/
        v0.3.141
```

May i wonder how you start Fn?

**Comment by rogergl** [comment]
Just ```fn start``` inside the docker-quickstart-terminal

**Comment by rogergl** [comment]
Just one strange thing: It works if  start it from the root dir ```/``` but not if I start it from my home dir ?

**Comment by rogergl** [comment]
One other problem: since docker-machine uses 192.168.99.100 and ```fn deploy``` deploys to localhost  it fails. Any ides how to specify the fn server ip  address ?

**Comment by denismakogon** [comment]
This should help you https://github.com/fnproject/fn/blob/master/docs/operating/options.md

**Comment by rogergl** [comment]
> @rogergl were you able to fix the problem at yours end?
> 
Yes an  no. Starting the fn server from the root dir helped but after upgrading fn the deployment stoped working and I had no time to investigate this problem further. Will have a closer look during the christmas holidays.

**Comment by denismakogon** [comment]
I opened an issue https://github.com/fnproject/cli/issues/122, `fn start` is not ideal. Meanwhile, I'd recommend taking a look at the docker-compose file for simpler deployment.

**Comment by rdallman** [comment]
closing, confirmed this does work on relatively up to date docker on mac osx, this looks a configuration issue. feel free to re-open / debug on slack with us, thanks!

**Comment by willjstevens** [comment]
I am still getting this, with a brand new Docker for Mac installation. Version 18.03.0-ce

No non-standard customizations. `fn start` fails with the same error of this issue.  

Will this be fixed? Thanks

**Comment by willjstevens** [comment]
**Permissions issue.** 

When you run with `sudo` - it works in any directory. Without sudo, it fails. 

Try:

`$ sudo fn start`

I looked at the source code printing this error; I think the line above it has too restrictive or demanding permissions on the file. This should be loosened somehow. 


db, err := bolt.Open(url.Path, **0655**, &bolt.Options{Timeout: 1 * time.Second})
   if err != nil {
		log.WithError(err).Errorln("Could not open BoltDB file for MQ")
		return nil, err
  }

So sudo raises the privileges level. Too bad this bolt.go file is in a different "iron-io" project.

**Comment by rdallman** [comment]
thanks for report @willjstevens , this should be easy to resolve the permissions.

> So sudo raises the privileges level. Too bad this bolt.go file is in a different "iron-io" project.

? i don't see any `iron-io` imports here. details?

**Comment by willjstevens** [comment]
Yw. 

I just Googled it, and found it .... actually, in two repos.:

- https://github.com/**iron-io**/functions/blob/master/api/mqs/bolt.go
- https://github.com/**fnproject**/fn/blob/master/api/mqs/bolt.go

But if the second one belongs to fnproject (a fork?) , you could probably change it here.

**Comment by rdallman** [comment]
@willjstevens fixed(?) https://github.com/fnproject/fn/pull/910 - yea, we don't use iron-io lib.
