### ISSUE TITLE
separate api from workers

### ISSUE THREAD

**Issue by matti** [fnproject/fn#406]
I'd want to have fn deployed as follows:

```
          lb
fn-api   fn-api  fn-api
        db   mq
```

and then separate "workers" in another datacenter(s) that is(/are) completely isolated from the internet. workers would poll the `mq` for jobs (and maybe write to the `db`, not sure how fn works internally). maybe workers could poll jobs from the lb also?

fnlb (https://github.com/fnproject/fn/tree/master/fnlb) requires access from the lb to the nodes.

**Comment by rdallman** [comment]
i guess i follow here, I think it would be easy to add an extension to run on your 'api' nodes that would halt the current thread from running tasks (https://github.com/fnproject/fn/blob/master/docs/operating/extending.md need slight updating, but it's `FireBeforeDispatch`)  but I don't know for sure (certainly, a panic would do, which could be caught and silenced, but it's less than ideal). the worker nodes would just conveniently never receive api requests. so i'm not sure this is impossible atm if you want to do entirely async calls. i don't think we will make separate binaries for the api and worker nodes, would prefer to have this mode available through extensions. open to feedback on making this easier.

**Comment by treeder** [comment]
We could perhaps add a flag to disable async, then those nodes would be sync only. The ones aren't behind the LB would be able to do both, but since they'd never get sync calls, it would implicitly be async only.

**Comment by carimura** [comment]
@matti this has come up a few times now.

Anyone have any ideas on how to make this work for sync calls as well? Would be really awesome.

**Comment by matti** [comment]
@carimura Just by doing the simplest thing? Wait?

**Comment by treeder** [comment]
@matti going to close this in favor of this: https://github.com/fnproject/fn/issues/531
