### ISSUE TITLE
Docs refer to "Iron-f(x)" 

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/fn#408]
This page: 
https://github.com/fnproject/fn/blob/master/docs/operating/production.md

Contains a diagram which has several references to "Iron-f(x)" 

![architecture](https://user-images.githubusercontent.com/6053562/31345831-e3a6cbdc-ad0e-11e7-9a2e-bf2dcd8d9403.png)

**Comment by treeder** [comment]
fixed.
