### ISSUE TITLE
Support for Crystal Language

### ISSUE THREAD

**Issue by ansarizafar** [fnproject/fn#419]
Please provide support for Crystal Language https://crystal-lang.org

**Comment by rdallman** [comment]
You should be able to run with crystal lang now, simply use a docker image with the crystal lang tools required installed inside of it.

that being said, we do not have fdk support, cli support, examples, etc for crystal lang -- though none of that is required for things to work, it makes things a little easier. can leave open for that reason, but don't let that stop you!
