### ISSUE TITLE
Exec format error (arm64)

### ISSUE THREAD

**Issue by DQvsRA** [fnproject/fn#431]
I'm trying to run Fn on my arm64 board (Odroid c2). And that's what I've got.

![image](https://user-images.githubusercontent.com/442111/31658905-b2abc26a-b332-11e7-80a1-cdae98c256e0.png)

**Comment by hibooboo2** [comment]
I would try installing from source. That would suit arm better. As right now our precompiled bins are not for arm64.

**Comment by hibooboo2** [comment]
However you will run into other issues with arm. Such as the fact that the lang images by default are not arm.

**Comment by denismakogon** [comment]
Closing this issue, because the problem is related to CLI, see referenced PR. If you think that you would like to have fn server binaries for ARM-based chips please reopen this issue.
