### ISSUE TITLE
Store real memory consumption in Call model

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#436]
At this moment we store timestamps that can be used to calculate duration, but we do not store actual memory consumption.

This would let users know their real memory consumption and let them decide whether increase/decrease amount of RAM for particular function.

**Comment by rdallman** [comment]
we have this stuff mostly hooked up https://github.com/fnproject/fn/issues/19 and it's a histogram, so it's easy to find max and such (for ui/with tools). just need to wire it in to store in the call model, waiting on migrations to add fields to models.

agree this is useful. close for dupe or this isn't what you had in mind?

**Comment by denismakogon** [comment]
I'm fine. Closing as dup.
