### ISSUE TITLE
Running fn in VirtualBox Ubuntu image fails with Permission denied - Could not mount /sys/kernel/security

### ISSUE THREAD

**Issue by lucasjellema** [fnproject/fn#437]
Running fn (0.4.11) in a Virtual Box Ubuntu 16 VM with Docker 17.09 (created and managed through Vagrant on Windows 10).

When I either try to run fn directly:
`fn start`
or use the indirect way of running:
`docker run --rm --name functions -it -v /var/run/docker.sock:/var/run/docker.sock -v $PWD/data:/app/data -p 8080:8080 fnproject/functions`

I run into the error messages shown below:

mount: mounting none on /sys/kernel/security failed: Permission denied
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: mounting none on /tmp failed: Permission denied
INFO[0000] datastore dialed                              datastore=sqlite3 max_idle_connections=256
INFO[0000] no docker auths from config files found (this is fine)  error="open /root/.dockercfg: no such file or directory"
FATA[0000] Cannot get the proper memory information to size server. You must specify the maximum available memory by passing the -m command with docker run when starting the server via docker, eg:  `docker run -m 2G ...`  error="Didn't find MemAvailable in /proc/meminfo, kernel is probably < 3.14"

Do any special prerequisites apply to the user as which fn is executed? 
Is running fn inside an Ubuntu VirtualBox in anyway special (and perhaps unsupported?)?

**Comment by rdallman** [comment]
it's possibly just a small parsing error as I don't think our memory parser was tested on too many platforms and likely isn't very robust. if you don't mind, it would be very helpful if you could paste the contents of your `/proc/meminfo` as well as a kernel version (`lsb_release` on ubuntu should do). sorry for the issue, and thanks for filing a bug. fwiw I run `fn` inside of a debian VM without issue, I'm betting it's a parser issue.

**Comment by lucasjellema** [comment]
Here is the contents of /proc/meminfo:
vagrant@vagrant-ubuntu-trusty-64:/proc$ **cat meminfo**
MemTotal:        4048172 kB
MemFree:         1775300 kB
Buffers:           72468 kB
Cached:          1588960 kB
SwapCached:            0 kB
Active:           946420 kB
Inactive:        1122812 kB
Active(anon):     408136 kB
Inactive(anon):     1268 kB
Active(file):     538284 kB
Inactive(file):  1121544 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:        407800 kB
Mapped:            62656 kB
Shmem:              1604 kB
Slab:             159324 kB
SReclaimable:     136188 kB
SUnreclaim:        23136 kB
KernelStack:        1664 kB
PageTables:         5884 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2024084 kB
Committed_AS:    1024728 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       54968 kB
VmallocChunk:   34359638232 kB
HardwareCorrupted:     0 kB
AnonHugePages:    245760 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       44992 kB
DirectMap2M:     4149248 kB

The **Ubuntu version**:
vagrant@vagrant-ubuntu-trusty-64:/proc$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

Thanks for your quick response. Maybe I will try Debian as alternative to Ubuntu for now.

**Comment by rdallman** [comment]
thanks for your help. ubuntu 16 should do the trick, as well. the kernel in 14.04 is too old to have the value we're looking for. we might could change the parser to calculate MemAvailable from the old values to fix this :)

**Comment by lucasjellema** [comment]
If we can decide that:
- Ubuntu 14.04 is not supported
- Ubuntu 16 will work
- Debian 8 certainly works (as I have experienced)

I believe we can close this issue. Is that how this works?
Or should it remain open because for example you want to fix the parse error for Ubuntu 14.04?

**Comment by rdallman** [comment]
> I believe we can close this issue. Is that how this works?

👍 that works for me. if more issues over 14.04 pop up can look into the parser, will keep it in mind. thanks for filing this issue and glad you got it working.

**Comment by treeder** [comment]
You can't deduce MemAvailable from a version that doesn't have it. The solution is pretty clear in the message, ie: pass in the `-m` flag.

**Comment by glockenstein** [comment]
But the "Could not mount /sys/kernel/security" issue is still there in ubuntu 16.04.

# fn start
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
time="2017-11-17T09:20:08Z" level=info msg="datastore dialed" datastore=sqlite3 max_idle_connections=256
time="2017-11-17T09:20:09Z" level=info msg="started tracer" url=
time="2017-11-17T09:20:09Z" level=info msg="no docker auths from config files found (this is fine)" error="open /root/.dockercfg: no such file or directory"
time="2017-11-17T09:20:09Z" level=info msg="available memory" ram=13428609024
...  v0.3.186 ...
time="2017-11-17T09:20:09Z" level=info msg="Serving Functions API on address `:8080`"
