### ISSUE TITLE
Name does not modify route.

### ISSUE THREAD

**Issue by garthy** [fnproject/fn#438]
In the documents for func.yml name is defined as

```name is the name and tag to which this function will be pushed to and the route updated to use it.```

To me this implies that the route will be updated to use the name instead of the current directory name.

If I set name and deploy the route still has the directory name in the route

**Comment by treeder** [comment]
Just FYI before closing this:

- name (optional) is the name used for the image, defaults to directory name. 
- path (optional) is the path/route, defaults to directory name.
