### ISSUE TITLE
Error in errorMessage handling in Lambda function

### ISSUE THREAD

**Issue by itayher** [fnproject/fn#445]
After running phantomjs command: ./phantomjs/phantomjs_linux-x86_64 --debug=no --ignore-ssl-errors=true ./phantomjs/screenshot.js http://www.google.com /tmp/ed646a3334ca891fd3467db131372140.png 1280 1024 30000

The error message is unhandled:

/function/lambda-bootstrap.js:395
        oldlog(JSON.stringify({"errorMessage": errstr }))
                                               ^

ReferenceError: errstr is not defined
    at functionCallback (/function/lambda-bootstrap.js:395:48)
    at /function/index.js:53:7

**Comment by rdallman** [comment]
no longer supporting these at this time
