### ISSUE TITLE
DNS example for app namespacing by domain

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#454]
An example to show how to create an extension for using custom domains. 

Eg 1: namespaced by user:

appname.username.customdomain.com/path/to/function (points to same thing as => host/r/appname/path/to/function)

Eg 2: globally unique app names (like s3, heroku, google cloud functions, lambda with api gateway), 

appname-12345.customdomain.com 

If you were running a service, you'd offer up domains like: appname-12345.my-fn-service.com

**Comment by carimura** [comment]
@derekschultz is this [related to] what you're working on?

**Comment by derekschultz** [comment]
@carimura Yes, it is somewhat related.

1. I'm a bit confused by the title of this issue, specifically w/r/t namespacing via /etc/hosts. I must be missing some context from recent discussions.
2. Related to above, I'm not working on namespacing. That's another issue (see GitLab service repo) separate from what I had been working on before Fn + OKE took up all of my time.
3. I am working on the second bullet point, globally unique app names, i.e `myapp.fnservice.io`.

**Comment by treeder** [comment]
This is coming together here: https://github.com/treeder/fn-ext-dns
