### ISSUE TITLE
Users can install Fn to K8s via Helm 

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#467]

**Comment by zootalures** [comment]
Needs to include flow, and clustering etc.

**Comment by carimura** [comment]
including hybrid arch. might be diff ticket.

**Comment by derekschultz** [comment]
Shouldn't hybrid arch support be a diff ticket? It was my understanding that the OSS Helm chart for Fn would allow the user to run anywhere, so a hybrid approach here would only add more complexity. Are we confusing internal (hybrid) needs with OSS needs?

**Comment by zootalures** [comment]
yeah, let's make this "Helm chart for customers"

Needs some docs

**Comment by zootalures** [comment]
Current plan: 

- [ ] helm chart with fn, flow, ui? flowui? prometheus?, can demo on naked k8s cluster 
- [ ] docs/tutorial in fn/docs? 
- [ ] blog post/outline

**Comment by derekschultz** [comment]
not sure about prometheus, but otherwise yeah that looks like a good plan. we can debate about prometheus, or add it if we have the time.

**Comment by carimura** [comment]
@derekschultz right thanks for clarifying... that list looks good. FYI @denismakogon has a docker compose file that brings all/most of that up as well. could maybe put together somewhere under an operator section. 

Re: prom I believe that'll be an extension per @nigeldeakin's work so we can leave that out for now and include different stats implementations later. Or maybe use prom as "example".

**Comment by derekschultz** [comment]
@carimura cool, +1 on adding a docker compose example to operating docs. 

Note: I pushed my old helm chart to a branch for @zootalures to have a start point and he'll assist with the flow service. I'll swoop in next week after the break and we'll complete the helm chart, leaving out prometheus.

**Comment by derekschultz** [comment]
Can close now that the chart is released - https://github.com/fnproject/fn-helm
