### ISSUE TITLE
remove DELETE /v1/apps/:app/calls/:call/log

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#481]
If we expose the ability for users to delete logs then it makes auditing relatively challenging in cases where some user actually used it (without us getting them to admit to it!). I could see the value in e.g. some sensitive data slipped into the log and I want to get rid of it, fwiw we don't have a call delete API and there should likely be some symmetry there. if we leave this then we could have cases where... a call happened, it had a log, the user deleted the log, so there's a call record laying around that indicates it should probably have a log (and definitely the call ran), and it kind of looks like a bug to the user if they don't remember deleting it or they're using fn with peers and don't audit every action.

I think if we have a cleaner for old logs and calls baked into fn then we don't really need to expose this at the api level -- users can just turn on the cleaner with some duration (e.g. `--cleaner 7d`). we should likely default to retain forever for the OSS one, just because people might be working on it over the course of a few weeks[/months/years] on their laptop, but different thread. it's also possible to clean out from the db / log store directly and is at least an option, albeit a bad one.

not really challenging to do, just need consensus.

**Comment by rdallman** [comment]
@denismakogon any reason for adding initially / others, thoughts ?

**Comment by denismakogon** [comment]
The reason was to delegate all responsibility for cleaning up calls/logs up to developers, but that was before we decided to delete all route-related stuff when deleting one. So, +1 to get rid of that.
