### ISSUE TITLE
app deploy returns invalid app name if capital letters in name

### ISSUE THREAD

**Issue by carimura** [fnproject/fn#490]
```
name: Vista
```

returned `ERROR: deploy error on /Users/chad/workspace/vista/services/alert/func.yaml: Invalid app name`

I had to guess it was the capital. Probably better to detect the reason for the error and return that rather than trying to support capital letters.

**Comment by rdallman** [comment]
Cli issue it looks

**Comment by rdallman** [comment]
yep, closing for https://github.com/fnproject/fn/issues/490
