### ISSUE TITLE
The fn-ui won't work in the kubernetes deployment from the documentation

### ISSUE THREAD

**Issue by Templum** [fnproject/fn#491]
## Enviroment Infos:
Kubernetes Version: v1.7.0
Minikube Version: v0.23.0

## Issue Description:
I followed the instruction given in the kubernetes [documentation](https://github.com/fnproject/fn/blob/master/docs/operating/kubernetes/README.md) and deployed the fnproject to my local minikube kubernetes cluster. I was able to use curl, from my host system, to generate an app and also set up the route. However, when I tried the same using the UI it failed [Error Message: _Something went terribly wrong (Status Code: 0)_]. I was able to visit the UI site, but at that point, my previously created app was not shown, further when I created a new app using the formula it failed. My investigation showed that, at least for my setup. The UI could not connect correctly to the fn-service.

## Fix: 
I went ahead and created and fork with the modification to `fn-service.yaml`.  Which can be viewed [here](https://github.com/Templum/fn/commit/6edb3f2cc9c1512fa6dd6003e911dce42f9254bd). If it's fine by you, I will fill out the CLA and setup up an pull request after updating the [documentation](https://github.com/fnproject/fn/blob/master/docs/operating/kubernetes/README.md) to make sure it reflects the namespace.

Best regards Simon

p.s. Thanks for the awesome work!

**Comment by reiz** [comment]
I have the same issue. Would be great if this fix finds his way into the master brunch.

**Comment by derekschultz** [comment]
Thanks for raising the issue. Apparently, the provided yaml needed some tweaking for the UI to work with minikube (at least with the DaemonSet service type). Probably something related to kube-dns, but didn't really dig into it. Submitting a quick fix (#499). 

Note, we'll have a Helm chart coming soon, which should alleviate some of the madness around k8s configs.

**Comment by Templum** [comment]
@derekschultz thx :) I also could have submitted the pull request
