### ISSUE TITLE
Add FN_ prefix to config options (ie API_URL --> FN_API_URL)

### ISSUE THREAD

**Issue by carimura** [fnproject/fn#492]
Doesn't everything else prefix with FN? This ones hidden and already causing confusion.

Other ones that'll need FN_ :

```
| DB_URL | The database URL to use in URL format. See [Databases](databases/README.md) for more information. | sqlite3:///app/data/fn.db |
| MQ_URL | The message queue to use in URL format. See [Message Queues](mqs/README.md) for more information. | bolt:///app/data/worker_mq.db |
| API_URL | The primary Fn API URL to that this instance will talk to. In a production environment, this would be your load balancer URL. | N/A |
| API_CORS | A comma seperated list of domains to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for | None |
| PORT | Sets the port to run on | 8080 |
| LOG_LEVEL | Set to DEBUG to enable debugging | INFO |
| DOCKER_HOST | Docker remote API URL | /var/run/docker.sock:/var/run/docker.sock |
```

Can we vote and if passed change these before people get used to the way they are now?

Related tickets that also discussed/implemented FN_ prefix:

https://github.com/fnproject/fn/issues/329
https://github.com/fnproject/fn/pull/299
https://github.com/fnproject/fn/pull/5

**Comment by nigeldeakin** [comment]
Extensions may need additional environment variables (in the same namespace). For example the metrics API extension requires something like `PROM_URL`. Should this be `FN_PROM_URL` or  `FN_EXT_METRICS_PROM_URL`?

**Comment by skinowski** [comment]
DOCKER_HOST will need care as this is used by docker in env. But we can take this as FN_DOCKER_HOST and set DOCKER_HOST env ourselves in that fn server to isolate it.

**Comment by rdallman** [comment]
DOCKER_HOST makes sense to leave raw, and in any case it's easy enough for a user that wants to complicate things and run 2 docker daemons on the same host to set this variable at runtime or in a config instead of exporting env vars. the rest seem like what every other config with env vars project seems to do.
