### ISSUE TITLE
Port to Azure Container Instance for Managed FaaS with True Pay Per Use

### ISSUE THREAD

**Issue by fmunz** [fnproject/fn#494]
After using Fn Project on EC2 I looked into running Fn on the container services offered by the clouds I am working with...

Oracle's OCCS is not serverless, but Azure has a service preview of [Container Instances](https://azure.microsoft.com/en-us/services/container-instances/) that allows to start containers for €0.0022 per instance created. Currently this is only possible using the Azure command line with custom commands IMHO.

Not sure how Fn is starting deployed functions at the moment (I guess it must be via "docker run ..." ), but I could imagine that creating a connector for Container Instances (using "az container create --image ... " instead of docker run image) could almost be a quick win.

- Fn API server could be easily started as a container on Azure CI (or even somewhere else?).
- effort in porting the function/container invocation inside Fn to be compatible Azure CI would be low
- Doing this, first time in history we had an open source serverless framework running 1:1 in a public cloud but still offering serverless characteristics of fully managed FaaS like Lambda, such as true pay per function invocation.

tempting?

**Comment by treeder** [comment]
If you're saying that the fn server could run it's function containers using Azure CI, that might be possible, but I there's a lot of things to figure out. How fast can it spin up containers?  How would you do routing? And probably a bunch of other things, not sure it would be worth the effort. 

That said, I think it would be interesting to support a container instances type of functionality on Fn.
