### ISSUE TITLE
docker-machine and `fn init` (eg not using docker-in-docker)

### ISSUE THREAD

**Issue by josephwinston** [fnproject/fn#496]
I set up my docker-machine with `docker-machine create --virtualbox-memory 12288 fnproject`, added the environment variables using ```eval `docker-machine env fnproject` ``` and then ran `docker run --rm --name functions -it -v /var/run/docker.sock:/var/run/docker.sock -v ${pwd}/data:/app/data -p 8080:8080 fnproject/functions`

My question is on running the `fn` actions like `fn init` in another shell where I added the required environment.

If I build from <https://github.com/fnproject/fn> using `make all && make install` then `fn init` returns:

```
INFO[0000] datastore dialed                              datastore=sqlite3 max_idle_connections=256
INFO[0000] started tracer                                url=
FATA[0000] couldn't connect to docker daemon             error="Get https://192.168.99.100:2376/_ping: x509: certificate signed by unknown authority"
```

What is the correct way to run all the required `fn` actions is you are not using docker-in-docker?

**Comment by denismakogon** [comment]
That docker remote URL that I'm seeing here is kinda weird. Are you able to talk to that docker instance outside of Fn container using given URL `https://192.168.99.100:2376` ?

**Comment by josephwinston** [comment]
I'm running on `fn` OS X (High Serra) 10.13.1 using `docker-machine` and not docker-in-docker.  

Version info for `docker`:

```
$ docker --version
Docker version 17.04.0-ce, build 23cf638
$ docker-machine --version
docker-machine version 0.10.0, build
```

Here's the `docker-machine` startup:

```
$ docker-machine start fnproject
Starting "fnproject"...
(fnproject) Check network to re-create if needed...
(fnproject) Waiting for an IP...
Machine "fnproject" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
$ eval `docker-machine env fnproject`
$ docker-machine ls
NAME        ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default     -        virtualbox   Stopped                                       Unknown
fnproject   *        virtualbox   Running   tcp://192.168.99.100:2376           v17.10.0-ce
$ docker --version
Docker version 17.04.0-ce, build 23cf638
```

The images on the `docker-machine`:

```
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
fnproject/functions   latest              9d9b531533e1        3 hours ago         143MB
golang                alpine              9e3f14138abd        8 days ago          269MB
fnproject/dind        latest              4a101e567b2a        4 weeks ago         106MB
```
The startup of `fnproject/functions`

```
$ docker run --rm --name functions -it -v /var/run/docker.sock:/var/run/docker.sock -v ${pwd}/data:/app/data -p 8080:8080 fnproject/functions:latest
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
INFO[0000] datastore dialed                              datastore=sqlite3 max_idle_connections=256
INFO[0000] started tracer                                url=
INFO[0000] no docker auths from config files found (this is fine)  error="open /root/.dockercfg: no such file or directory"
INFO[0000] available memory                              ram=12182159360

        ______
       / ____/___
      / /_  / __ \
     / __/ / / / /
    /_/   /_/ /_/
        v0.3.173

INFO[0000] Serving Functions API on address `:8080`
```

**Comment by denismakogon** [comment]
From your last comment, everything looks okay, Fn started. So the problem was in Docker remote API URL.

**Comment by josephwinston** [comment]
I'm confused.  What do I use then to run the commands like `fn init` and `fn run` when I am not running docker-in-docker?  Because when I try to invoke these commands, I'm receiving the same error:

```
INFO[0000] datastore dialed                              datastore=sqlite3 max_idle_connections=256
INFO[0000] started tracer                                url=
FATA[0000] couldn't connect to docker daemon             error="Get https://192.168.99.100:2376/_ping: x509: certificate signed by unknown authority"
```

**Comment by denismakogon** [comment]
So, only fn start will actually start a fn server, fn run related to a specific function. According to code, fn start does not let you pass docker host to fn server. The only thing you can de, build it from source and start one.

**Comment by josephwinston** [comment]
Any suggestions on what code or documentation that I can read to see how to execute all the steps that happen automatically when I am running docker-in-docker?

**Comment by treeder** [comment]
@josephwinston you should upgrade to Docker for Mac, docker-machine is obsolete. https://www.docker.com/docker-mac

**Comment by treeder** [comment]
@josephwinston can you give full output of those commands?  `fn init` and `fn run` don't connect to any server so it seems odd you'd see that output for those commands.

**Comment by denismakogon** [comment]
@treeder there been quite a few reports from people using docker-machine with `fn start`.  But it definitely goes away with docker for mac (can confirm that).

**Comment by josephwinston** [comment]
I switched to Docker for Mac and everything works. Close the ticket.  

When I have the time, I’ll reinstall Docker machine and work through the issue again.
