### ISSUE TITLE
calls to /api/stats in k8s deployment are not consistent between cluster members

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#503]
After deploying as per this: https://github.com/fnproject/fn/blob/master/docs/operating/kubernetes/fn-service.yaml we have 3 fn server instances. It seems that the /api/stats endpoint is load-balanced between them but that they don't synchronise data accurately:

```shell
## 4x curl http://<fn-api>/api/stats
{"Queue":0,"Running":0,"Complete":1,"Failed":0,"FunctionStatsMap":{"/hot-hello":{"Queue":0,"Running":0,"Complete":1,"Failed":0}}}
{"Queue":0,"Running":0,"Complete":1,"Failed":0,"FunctionStatsMap":{"/hot-hello":{"Queue":0,"Running":0,"Complete":1,"Failed":0}}}
{"Queue":0,"Running":0,"Complete":0,"Failed":0,"FunctionStatsMap":{}}
{"Queue":0,"Running":0,"Complete":1,"Failed":0,"FunctionStatsMap":{"/hot-hello":{"Queue":0,"Running":0,"Complete":1,"Failed":0}}}
```

**Comment by rdallman** [comment]
this is intentional, they are per server. there is a task force assembling now for implementing some kind of stats api for the UI to use that will be cluster-wide, could leave this as a marker for that if you wish.

**Comment by nigeldeakin** [comment]
The same information is available as Prometheus counter or gauge metrics, so one could configure a Prometheus server to scrape metrics from all the Fn servers and provide combined data to a tool such as Grafana. Single-server example at https://github.com/fnproject/fn/tree/master/examples/grafana.

**Comment by denismakogon** [comment]
I don't think that we should expose /stats at all through any kind of load balancers to the end users. At this particular moment. This is very per-server-specific information that should go to Prometheus as @nigeldeakin pointed.
/stats is the only one API that is here for operators, so I'm kinda considering to get Fn API split to endpoints that user has an access to and those ones that have to be available internally (no matter via Prometheus and/or API endpoint)
