### ISSUE TITLE
API extension to provide access to aggregated call stats  

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/fn#514]
This is a proposal to create an extension to the Fn API to access various statistics about function calls.  

### Purpose
Its purpose is to allow new UI tools to obtain these statistics and display then as graphs.

### A Fn API
* The new API will be available on any Fn server, using the the same host and port as the rest of the Fn API.
* The API will provide data for the entire cluster, not just the Fn server which is handling the API request,

### An extension
* The new API would be an extension to the Fn API, implemented as an optional extension to the Fn core. This means that it would be possible to build the Fn server with this extension API, without this extension API, or with a different implementation of the extension API.
* The implementation will have its own GitHub repo under `fnproject`

### Metrics 
* Initially the following metrics would be available
** `calls` - count of completed function calls (since server startup). 
** `errors` - count of function calls which failed due to an application error (other than timeout)
** `timedout` - count of function calls which failed due to timeout 
** `duration` - the rolling mean length of time taken to perform function calls
These metrics would be available per cluster, per-application or per-route (path). Information will not be available for individual function calls.

### Style of API
* The API will be designed to return an entire graph's worth of data, returning a historical set of values over a defined time range (e.g. the past 10 minutes) rather than just the current value. An initial suggestion is
```
input: app, route, time range, time buckets (eg: hourly, daily)
output:
{
  "time": [ ms_since_epoch start time of bucket ],
  "calls": [ array of buckets with number of calls],
  "errors": [ array of buckets with number of errors],
  "duration": [ array of buckets with durations ],
}
```
### Implementation
The extension will use Prometheus and will require a Prometheus server to be running. The Fn server will make appropriate metrics available to Prometheus, which will aggregate information from all Fn servers. When an call is made to the proposed API, the extension will fetch the required data from Prometheus and return it to the caller.

The use of Prometheus serves several purposes, including
* Aggregating metrics from all the Fn servers in the cluster
* Storing historical values of these metrics (whatever historical time range is supported by the API)
* Performing the heavy lifting for the calculation of rolling means (and other statistical functions in the future)

**Comment by treeder** [comment]
Regarding errors for timedout, I wonder if errors should include timeouts? If I were looking at a graph of errors, I would probably expect to see all errors including time outs or anything else. If I didn't, I might look at it and think everything is OK, but then later find out there's a ton of timeouts.

**Comment by nigeldeakin** [comment]
Currently the "errors" counter that is sent to Prometheus does indeed include timeouts. So if errors includes timeouts, do we need timeouts as a separate metric well? (I'll assume yes)

**Comment by rdallman** [comment]
fwiw all the mentioned data points could be generated from a map-reduce like query on our raw call data (and that would likely be cached / indexed) -- without prometheus -- though this is easier if they are in an rdbms or some db that supports this operation, and that may not be the case if #482 goes through. anyway, $.02. on #482 since it seems like all the call data we really want is going to be in prom anyway per this issue, maybe we should reconsider storing calls at all in object store / db if this goes through.

**Comment by nigeldeakin** [comment]
An initial implementation is now available in the `ext-metrics` repo. See https://github.com/fnproject/ext-metrics for more information, initial documentation, and links to examples. Issues can be logged in https://github.com/fnproject/ext-metrics/issues

**Comment by nigeldeakin** [comment]
This is now implemented. For details see https://github.com/fnproject/ext-statsapi/blob/master/README.md

The stats API returns the metrics: `calls`, `errors`, `timedout`,`completed` and `durations`.

In addition, the metric `failed` (which is  `errors` + `timedout`) is also returned but this is deprecated and may be removed in the future.
