### ISSUE TITLE
Kubernetes deployment fails due to missing public fnserver image

### ISSUE THREAD

**Issue by Lawouach** [fnproject/fn#519]
Hi there,

I wanted to deploy fn to a minikube instance today, as per https://github.com/fnproject/fn/tree/master/docs/operating/kubernetes, but that failed pulling the fnserver image:

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----			-------------			--------	------			-------
  3m		3m		1	kubelet, minikube					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-4jjn9" 
  3m		18s		10	kubelet, minikube	spec.containers{fn-service}	Normal		BackOff			Back-off pulling image "fnproject/fnserver:latest"
  3m		4s		5	kubelet, minikube	spec.containers{fn-service}	Normal		Pulling			pulling image "fnproject/fnserver:latest"
  3m		0s		5	kubelet, minikube	spec.containers{fn-service}	Warning		Failed			Failed to pull image "fnproject/fnserver:latest": rpc error: code = 2 desc = Tag latest not found in repository docker.io/fnproject/fnserver
  3m		0s		15	kubelet, minikube					Warning		FailedSync		Error syncing pod
```

Indeed there is nothing to see at https://hub.docker.com/r/fnproject/fnserver/

Am I missing something obvious? :)

Thanks,

**Comment by denismakogon** [comment]
This is caused by #516. @treeder can you update fn image on dockehub.
Reasonable fix here - change fnserver to functions in cluster config.

**Comment by treeder** [comment]
Try that again, sorry, doing some image name changes :|
 https://hub.docker.com/r/fnproject/fnserver/tags/

**Comment by Lawouach** [comment]
Thanks, Kube picked it up automatically :)
