### ISSUE TITLE
Support function supplied by URL

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#52]
In gitlab by @denismakogon on May 29, 2017, 11:49

Support function supplied by URL.

Docker supports image importing through URL, the same can be done at fn layer.

CLI:
`fn routes create <app> <route> --container-url`
where `container-url` is a storage URL where image (provided by docker CLI [2]) is stored.

[1] https://docs.docker.com/engine/reference/commandline/import/

[2] https://docs.docker.com/engine/reference/commandline/save/

**Comment by treeder** [comment]
@denismakogon can we close this?

**Comment by denismakogon** [comment]
Yes since it didn't find anyone interested in it.
