### ISSUE TITLE
JSON protocol writes HTTP path and query instead of full request URL

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#535]
`request.URL.RequestURI()` return path and query of the request URL, i.e. `/r/app/route?something=something&etc=etc`, but has to return full request URL, i.e. `fnhost.io/r/app/route?something=something&etc=etc`

**Comment by skinowski** [comment]
I see the issue in api/agent/protocol. I'll fix this.

**Comment by skinowski** [comment]
Closed with #657
