### ISSUE TITLE
cache images used in circleci tests

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#540]
getting build failures when quay or docker hub fart. also, it takes time to pull these, so we could probably speed up builds a bit. if the tests fail because they rely on updated image behavior it is really easy to invalidate the cache and have it be updated, but 99.99% of the time this probably isn't the case. 

there are a few of these:
* fnproject/error
* fnproject/sleeper
* fnproject/hello
* quay.io/goswagger/swagger
* mysql
* minio/minio
* postgres

possibly others?

**Comment by denismakogon** [comment]
Circle CI 2.0 allows to cache images as long as your credit card if full with cash. Image cache is the premium feature, unfortunately.

**Comment by rdallman** [comment]
ah ha. i was just going to cache the /var/lib/docker/image directory. will look into cost... for now, i'll probably end up making the problem child a bit smaller but some images like swagger do take a while to pull and almost never change.

**Comment by denismakogon** [comment]
Indeed. Here's link. They say "additional fee", so "contact us, because we need your cash". https://circleci.com/docs/2.0/docker-layer-caching/#nav-button

**Comment by rdallman** [comment]
it looks like that is for caching layers that were built in previous builds, primarily (maybe in addition to entire images that need to be used). I have hope that just some rough directory caching may work.

**Comment by rdallman** [comment]
the test images were all pretty small ( < 60MB each) but opted to just pre-pull them and then if docker hub is dead that can fail, see https://github.com/fnproject/fn/pull/539/commits/327f4a9585f259c4cf8a9d5f22b4892915b211ea

swagger image is still pretty big, we could probably shave some time off ci builds by caching it. mysql and postgres are big, too. i looked into shitty work arounds for caching images and they only let you cache files in your project directory. boo. so anyway, I give up until the time comes if/when we change CI platforms.
