### ISSUE TITLE
Automatically register backends in fnlb within Kubernetes

### ISSUE THREAD

**Issue by zootalures** [fnproject/fn#553]
When fnlbs are run in a k8s cluster they the backends should be determined by the active set of fn nodes in the cluster as configured by k8s. 

Adding new nodes that run the fnservice should be automatically registered with all available LBs in a given period fo time. 

Removed nodes should be automatically deregistered from the lb.

**Comment by rdallman** [comment]
I think there are a lot of ways to skin the cat, but one idea is that we could actually have a 'k8s' backend to get the list of nodes (in `fnlb` terms: a k8s`Grouper`), that could be configurable with the k8s master address and some tag to look for to determine that a node is an `fn` server. It also seems easy to add to k8s hooks and use the existing API [backed by a db] to add `fn` nodes when they activate / deactivate.

**Comment by jan-g** [comment]
(Picking this up as part of #531)

**Comment by jan-g** [comment]
https://github.com/fnproject/fn/pull/563

In particular, https://github.com/fnproject/fn/blob/8abbe570484623204b5b146911997d2ebb808703/fnlb/README.md "running under Kubernetes".

I've built and pushed up ioctl/fnlb that's built from this if you want to give it a try; it won't work outside of a k8s container. (The allGrouper functionality remains in place as a default.)

**Comment by zootalures** [comment]
closing,
