### ISSUE TITLE
Use two distinct DB connection for read and write ops

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#558]
Use two distinct DB connection for read and write ops
=======================================
In Fn deployment when it fn servers use MySQL as database where MySQL presented as group replication cluster with MySQL router sitting ontop there's possibility to use different connections for reading and writing to the DB.

MySQL router
--------------
[MySQL router](https://dev.mysql.com/doc/mysql-router/2.1/en/) is a per-application query router that exposes two ports for reading and writing ops (default ports: 6446, 6447). 

Pros
----
The benefit of such feature is that we can spread our requests among two different connections (and their internal pools).

Cons
-----
This is MySQL-specific feature. Would require certain workarounds for existing MySQL driver.

**Comment by carimura** [comment]
IMO from a high level it doesn't hurt to have mysql-specific features built into the Fn mysql driver. Doesn't pollute existing core or other db drivers.

**Comment by rdallman** [comment]
is splitting ports strictly required in the mysql router? I don't think this poses a concern for us at the moment at all. all our db drivers right now are just `sqlx` with very minimal db-specific code, not that we need to adhere to this, but honestly we don't need any of the fancy features of pg or mysql for our workload which is super simple and it would be nice if our db drivers reflected that. specifically, if we do #482 we will have a very very low write rate and splitting writes to another instance doesn't offer us much benefit at all (read-heavy workload). 

imo all we need is some kind of redundancy (many ways to do this now) from mysql, just for fault tolerance. once we get into prod we'll have a better idea of what adjustments we need to make for our workload. this seems like we can add it without requiring any code changes really (just ops changes).

**Comment by denismakogon** [comment]
So, port splitting is not necessary, the MySQL router on port 6446 accepts both read and write, but it's recommended to use 6447 port for reads only.

I do agree that DB driver is simple and DB-feature-agnostic, but not sure if that is something we should be proud of. Indeed we're not doing something very heavy on reads or writes, data schemas are pretty flat, we don't have joins or whatever.

Note for those who gonna deploy Fn with the MySQL group replication, it is recommended to deploy 1 router per Fn node.

**Comment by rdallman** [comment]
gonna close this, a more general purpose issue discussing mysql clustering strategies could link to this, not sure this is worth discussion in itself (and targeted as feature req)
