### ISSUE TITLE
Calls v1 paginated API does not return more than 100 objects

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#560]
I have Fn cluster that ran about 2.5K calls:
 - node 1 
```
{"Queue":0,"Running":0,"Complete":516,"Failed":0,"FunctionStatsMap":{"/test-fdk-python":{"Queue":0,"Running":0,"Complete":516,"Failed":0}}}
```
 - node 2 
```
{"Queue":0,"Running":0,"Complete":42,"Failed":0,"FunctionStatsMap":{"/test-fdk-python":{"Queue":0,"Running":0,"Complete":42,"Failed":0}}}
```
- node 3 
```
{"Queue":0,"Running":0,"Complete":1917,"Failed":0,"FunctionStatsMap":{"/test-fdk-python":{"Queue":0,"Running":0,"Complete":1917,"Failed":0}}}
```
But when i'm trying to list all calls by setting number of objects per page equal to 3000, API returns only 100.
```
fn calls list ab-test --per-page 300 | grep Status | wc -l
     100
```

**Comment by rdallman** [comment]
this is intentionally capped to 100 in the code.

**Comment by rdallman** [comment]
or, please provide an action item here as this is not directly a bug itself without some opinion on how it 'should' work and the tradeoff implications of changing how it works

**Comment by denismakogon** [comment]
I want to know how can I get 3K calls all-in-one response or how can I get the number of successful or errored calls within the certain timeframe? At this particular moment as a user I have to do reverse iteration among calls because on API request I get only N last calls. So, the pagination API is not really clear how to work with that, I'm sure that we have any doc explaining how pagination API works and specific reason why we limit the number of object to 100.

**Comment by rdallman** [comment]
reason to have pagination is simply reduce load on db (specifically, long running read queries can tie up the transaction engine & `select *` without limit on not-cached data is not very nice to db caches and subsequent queries; likely many more similar concrete reasons). 100 is a magic number. 1000 could be ok, maybe. 10000 seems like too many. but in any case, users have to implement paging no matter the amount we pick as the per page max, so it doesn't seem like it matters a whole lot as long as we have something reasonable.  

here's our docs: https://github.com/fnproject/fn/blob/master/docs/definitions.md#pagination -- our docs are a mess, i'm not sure there's really anywhere we could put them where a user would be expected to run into them, but the swagger API is up to date with the parameters (half of which were used in the example given). 

> I want to know how can I get 3K calls all-in-one response or how can I get the number of successful or errored calls within the certain timeframe?  At this particular moment as a user I have to do reverse iteration among calls because on API request I get only N last calls.

paging answers this. swagger has docs for this. filter by time is possible. the filtering by status is not hooked up at the moment. the pagination api seems pretty clear on this.

**Comment by denismakogon** [comment]
Okay, this does look like bad UX with Fn CLI, it does not provide next cursor, that's why it's kinda hard to work with calls with CLI.

**Comment by rdallman** [comment]
yea, the cli probably needs to return it. the cli maybe should take an arg like `-n 3000` and then could internally do the pagination to get 3000 calls, without the client having to interact with it, or possibly `-all`, though we want to discourage that really (limit to 24h or something). in general I would hope that people use client libraries to interact with `fn` and not the CLI for doing heavy lifting (for tasks like this). I can't think of a good reason for a dev to sit there with the cli and inspect each page and only ask for another page if some expectation isn't met, and the shell scripting required to hook up paging is probably a lot less frightening in a user's favorite language rather than a user's favorite shell scripting language.

**Comment by denismakogon** [comment]
Tend to agree, CLI at this moment is the best option, but client libraries are not good at this moment, because they were built with the swagger spec that makes them look like over-complexed HTTP-Fn-specific framework, where people doesn't see HTTP stuff, but more playing with models (client, apps, routes, etc.). Current pagination looks awesome if i would go and build my own http-fn library to talk to Fn because swagger clients don't care about pagination, swagger generator considers our pagination attributes as regular query parameters and doesn't let call some sort of `calls.next` API, so at CLI we have to do things like manual pagination, which is awful, but something that we supposed to be living with.

To the statement that people doesn't use CLI, i thought just as you that not true, but it appeared that CLI is very useful for things like calls and logs, of course in a context of function (or sequence of functions) testing.

**Comment by rdallman** [comment]
swagger clients should all have a parameter for `cursor` to any endpoint that lists things? if this isn't the case, then we need to regenerate our swagger clients or something is terribly wrong with swagger? the API spec has the parameters listed under `GET /apps` at least http://petstore.swagger.io/?url=https://raw.githubusercontent.com/fnproject/fn/master/docs/swagger.yml#/Apps/get_apps -- as linked https://github.com/fnproject/fn/blob/master/docs/definitions.md#pagination it's pretty easy to map onto client bindings, e.g.:

```go
var params apiapps.GetAppsParams
var apps []apiapps.App

for {
  resp, err := client.Apps.GetApps(&params)
  if err != nil {
    return err
  }
  apps = append(apps, resp.Apps)

  if resp.NextCursor == "" {
    break
  }
  params.Cursor = resp.NextCursor
}
```

so pagination with client libraries is possible? you're just saying you don't want to do this and have the CLI return everything (exactly what we implemented paging to avoid)?

forcing users into paging is a pretty common practice, and the code is pretty straightforward. sure, it's convenient for users to be able to grep and count across all calls with a bash incantation, but it's not a whole lot to ask them to use paging to do this, either (sure, our cli needs to expose cursor so they can). 

yea, cli is useful for one off inspection. as for having a decent paging api to use to regularly inspect entire lists of things, i'm not sure of a clean api to do this and don't think forcing users into writing a for loop with client bindings to be the end of the world i guess.

**Comment by carimura** [comment]
can we start with providing a simpler way for the CLI to grab all results? Maybe by returning next cursor as you say? I also work with the CLI quite a bit and needed a better way to get through sets of results. It was on my list of things to play around with and come up with some suggestions.

**Comment by rdallman** [comment]
> can we start with providing a simpler way for the CLI to grab all results?

kind of exactly what we're trying to avoid by having pagination. cli should maybe do last hour by default and easy to change? don't want to default to all, and want to make sure there is _some_ bound that has to be specified (even if the wise cracks put it at midnight, Jan 1 1970). but anyway, there was discussion https://github.com/fnproject/cli/issues/50 / move to CLI issue probably.

**Comment by carimura** [comment]
ya I'm not saying default to all, just an easier way. I haven't played around with it enough but using the cursors was NOT intuitive unfortunately....

**Comment by rdallman** [comment]
with the CLI*
