### ISSUE TITLE
Let Fn gracefully handle exit code when FDK faces unsupported format

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#574]
There's the basic idea: If FDK doesn't know how to handle the incoming request (basically, it doesn't know the protocol) it should fail the whole container with the very specific exit code - if HTTP 501 means that something not implemented, maybe FDK exit code 501 should be the mean the same for Fn?

This idea came up during the discussion of how to handle unknown format for FDKs.
cc @zootalures

**Comment by rdallman** [comment]
hopefully we're dropping this field in the near future
