### ISSUE TITLE
Is there an API to see the messages waiting on the async queue

### ISSUE THREAD

**Issue by sherwoodzern** [fnproject/fn#595]
When using asynchronous invocations the incoming request is placed on the "internal" messaging queue.  Is there a public API to view the messages currently sitting on the queue waiting to be processed?

**Comment by denismakogon** [comment]
You might try `/stats` endpoint to see current functions being started, competed, failed.

**Comment by rdallman** [comment]
beware `/stats` api is in flux and possibly / probably going away as it does no cross cluster aggregation and is relatively useless in a cluster setting, we're shipping these metrics to prom as well and that's the likely best future proof in-road to see metrics. there are some docs here to get grafana / prometheus configured https://github.com/fnproject/fn/tree/master/examples/grafana

**Comment by rdallman** [comment]
gonna close for #155 -- for viewing queues we're very likely not gonna be able to support a peek api (where peek is effectively a dequeue without dequeueing a message), these are notoriously tricky to support over different message queue semantics and we would like to keep things easily 'pluggable'. thanks for filing this.
