### ISSUE TITLE
API for deleting messages off of the internal messaging queue

### ISSUE THREAD

**Issue by sherwoodzern** [fnproject/fn#596]
Will a public API be available to remove messages off of the internal message queue?  This may be important in situations where messages did not get processed in a timely manner and thus are stale messages.

**Comment by rdallman** [comment]
yep. slated https://github.com/fnproject/fn/issues/155, we're re-working some of the messaging stuff at the moment. thanks for raising, gonna close as dupe since cancelling encompasses this and a few other things.
