### ISSUE TITLE
Specifying extension branch when building a custom Fn server with extensions 

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/fn#598]
This is a request too allow an extension's branch name to be specified in `ext.yaml` when building a custom Fn server image with extensions.

The existing feature is documented here
https://github.com/fnproject/fn/blob/master/docs/operating/extending.md

Currently this fetches the source code of the extension by cloning the master branch of the extension. However there is no way to specify any other branch. This means it's not possible use this feature to test changes to an extension until those changes have been merged into the master branch.

**Comment by treeder** [comment]
Working on it here: https://github.com/fnproject/cli/pull/142
