### ISSUE TITLE
async hot request body issue

### ISSUE THREAD

**Issue by skinowski** [fnproject/fn#601]
Async hot request body does not seem to make it into the containers. In async hot case, some http headers are missing.

Compare the following async and sync requests:

`
POST /r/test/foofn HTTP/1.1
Host: localhost:8080
Fn_app_name: test
Fn_call_id: 01C1AGQA7K47WJR00000000000
Fn_format: http
Fn_header_accept: */*
Fn_header_content_length: 8
Fn_header_content_type: application/x-www-form-urlencoded
Fn_header_user_agent: curl/7.54.0
Fn_memory: 128
Fn_method: POST
Fn_param_app: test
Fn_param_route: /foofn
Fn_path: /foofn
Fn_request_url: http://localhost:8080/r/test/foofn
Fn_type: async
`

`
POST /r/test/foofn HTTP/1.1
Host: localhost:8080
Connection: close
Accept: */*
Connection: close
Content-Length: 8
Content-Type: application/x-www-form-urlencoded
Fn_app_name: test
Fn_call_id: 01C1AJ3FMD47WMM00000000000
Fn_format: http
Fn_memory: 128
Fn_method: POST
Fn_param_app: test
Fn_param_route: /foofn
Fn_path: /foofn
Fn_request_url: http://localhost:8080/r/test/foofn
Fn_type: sync
`

**Comment by skinowski** [comment]
(i.e content length is not passed to outer request, but moved to fn_header value - and body never seems to be sent)
fn call (without content-length)  seems to result in body being sent without framing on the client side.

**Comment by denismakogon** [comment]
That's something which still needs to be addressed. For the async path, every HTTP protocol header gets `fn_header_` prefix, this is up to FDKs to handle this case, not sure that FDK that you've used to develop function.
Not sure about `fn call`.

**Comment by rdallman** [comment]
i don't think it's a client side / fdk issue. just for async after we copy in the entire request into a buffer we need to add the content length header and then make sure those headers are plumbed back out properly (possibly 2 things to fix).

**Comment by rdallman** [comment]
related to https://github.com/fnproject/fn/pull/370 -- which strips FN_HEADER (as noted, one issue)
