### ISSUE TITLE
Use app ID's rather than app name as the primary key

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#607]
The main reason behind this is to allow people to change their app names. Currently, since we use app name as the key, we can't really allow anybody to change it because it could break a lot of things. You could imagine the auth system allowing access to an app by name. If we allowed the user to change the app name, then auth would break. This among other things.

* change app name
* support namespaced apps (ie: two users can have same app name)

The user experience would not change, they can still use app name everywhere. 

* [ ] Programmatic access with IDs via API (so if name changes, systems don't need to change)
* [ ] Users should still be able to use app names as they do now, from CLI, curl, etc.

**Comment by treeder** [comment]
Looks like this is a go, discussion: https://fnproject.slack.com/archives/C7FKW83GV/p1514922283000580

**Comment by rdallman** [comment]
helps with https://github.com/fnproject/fn/issues/587

**Comment by denismakogon** [comment]
@treeder I can take care of this if help needed.

**Comment by carimura** [comment]
@denismakogon weren't you working on this one? if so, can you move to "Doing" and assign to yourself? thx.
