### ISSUE TITLE
fn init doesn't set runtime when it guesses it

### ISSUE THREAD

**Issue by johanvos** [fnproject/fn#608]
fn init might guess the runtime, but it doesn't add that to the generated func.yaml:

```
bieke-johan:~/fn/work/go> fn init
Found go function, assuming go runtime.
func.yaml created.
bieke-johan:~/fn/work/go> cat func.yaml 
version: 0.0.1
entrypoint: ./func
```

As a consequence, fn run will fail

`fn init --runtime go`
will add the runtime to the generated func.yaml file, but the Quickstart guide doesn't mention it is required to add the --runtime option.

It might be good to add the guessed runtime to the .yaml file, unless overruled by the --runtime option.

**Comment by johanvos** [comment]
I would suggest adding something like this in cli/init.go line 220
```a.Runtime = helper.Runtime()```

**Comment by delabassee** [comment]
Funnily enough, I was just looking at the same issue!

https://github.com/fnproject/cli/commit/c44ff2bf76013a63f59ef41ea24292a435e1aa6a#diff-33a47ea8c5a16ace99278226b31e7076L234
is where the problem was introduced.

--David

**Comment by treeder** [comment]
Fix here: https://github.com/fnproject/cli/pull/125
