### ISSUE TITLE
How to access other fn serverless service?

### ISSUE THREAD

**Issue by monkingxue** [fnproject/fn#636]
Hi, I am using fn to build a project to persist data by nodejs. I need to invoke fn functions(such as A) and get result in another fn function(such as B), but when I access localhost:8080 in B functions by `fn run`,  it gave me a connect ECONNREFUSED error, I think it because in B container, I cannot open a socket  to listen 8080 port.But how can I access other service use URL? I am confused.

**Comment by denismakogon** [comment]
First of all. The thing you were trying to do is not a real sequencing and here's why. `fn run` doesn't run a function but starts a container and passes data to that, `fn run` doesn't talk to Fn service. So, for your case `fn run` is the wrong choice.

What you have to do is to:
1. Setup your Fn service to accept the connection via the internet (it must run on public IP, so the functions can actually talk to Fn to call other functions).
2. Each function should have Fn API URL in its config (app config suites at its best).

Things that I've mentioned above can be applied to Fn service, but I do recommend to take a look at and USE Fn Flow service https://github.com/fnproject/flow (cc @zootalures) it was build exactly for pipelines and sequencing.

**Comment by monkingxue** [comment]
@denismakogon Thanks for you response! I think the `fn flow` is really cool but when I read the README, I just found the java version. I am using the `fn` to build my micro-services app and I think it's excellent and interesting so much, but I found the docs is not satisfactory, I have to read source code to find what I need, such as the `app.yml` just have `name` field just now but I found `config` field in docs. Sincerely hope this project become more popular and perfect.

**Comment by denismakogon** [comment]
I see, if you think that something is far away from "ideal" I do recommend to file an issue, it's worth it.
I do recommend to spend some time reading Fn blog posts:
1. Fn Intro (https://medium.com/@denismakogon/things-that-you-should-know-about-new-open-source-serverless-platform-fn-e1336cc2b01c)
2. General info on Fn platform: https://medium.com/fnproject

Feel free to join Fn slack (fnproject.slack.com) to get faster responses.

**Comment by treeder** [comment]
@monkingxue instead of run, you should start an fn server `fn start`. Then `fn deploy` your functions to your local server. `fn run` is just for testing, it won't have an addressable endpoint.

**Comment by monkingxue** [comment]
@treeder yeah，I just want to test my service rather than deploy it.

**Comment by treeder** [comment]
I just mean deploying it locally so you can test it. 

* start local Fn server - `fn start`
* deploy your functions locally - `fn deploy`

Keep in mind that on a Mac, for containers to talk to other containers locally, they need to use a special host: `docker.for.mac.localhost`. See this for an example of that in Ruby: https://github.com/treeder/fn-app-example/blob/master/ruby/func.rb

**Comment by rdallman** [comment]
seems resolved, closing this one. feel free to re-open if this isn't the case. thanks!
