### ISSUE TITLE
add metric for log bytes uploaded/downloaded, latency for all log stores

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#646]
the datastore has a metrics datastore wrapper that adds metrics to each datastore call. we need to do the same for the log store since users (and us) may use a separate one from the datastore.

since `InsertLog` and `GetLog` take an `io.Reader`, we shouldn't read it just to count bytes (full copy), I think there are 2 options:

* make an `io.Reader` type that wraps the log `io.Reader` and counts bytes read from this. after the enclosed (real) `InsertLog`/`GetLog` call is completed and has read the `io.Reader`, we can then add a metric for the size of that log that was uploaded. 
* check that type assertion `sizer, ok := log.(interface{ Size() int64 })` passes. we're using a `bytes.Buffer` at present so this check will pass in `InsertLog` and we can get the size from that. this doesn't cover `GetLog`, however the s3 api does expose the length that we could snatch out, but then this is a plumbing problem.

1) seems more robust and preferable. latency is a pretty straight forward span addition. bytes uploaded / downloaded will be useful to see if we hit caps against any log store we might be using (latency will go up but throughput will stay flat).

**Comment by gviedma** [comment]
Fixed by PR https://github.com/fnproject/fn/pull/670
