### ISSUE TITLE
FN_REQUEST_URL not set in hot functions

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/fn#647]
https://github.com/fnproject/fn/blob/master/docs/writing.md states that function implementations may access the environment variable `FN_REQUEST_URL`  which is set to "the full URL for the request"

However this appears the be the case only for cold functions. In hot functions this is unset.

If this is by design, the documentation page above needs to be corrected.

**Comment by rdallman** [comment]
is there a repro case here? possibly related to #370 but it's likely a casing issue of some sort. in hot it likely appears as `Fn_request_url` and not the upper cased version. we do need to pin that down, but i think the surface area is much larger than just this one value if that's the case.

**Comment by skinowski** [comment]
I'll track and fix this.

**Comment by nigeldeakin** [comment]
Here's the hot function in which I discovered the issue:
https://github.com/fnproject/ext-statsapi/blob/master/test/hello-hot-sync-a/hello-hot-sync-a1/func.go
(I'm trying to pass parameters to the function to force it to fail, timeout etc. Works fine on cold functions)

**Comment by skinowski** [comment]
For hot, I think this behavior is normal/intended, no? We launch a hot container with a process with set env variables, but URL will change per invocation, so it's part of HTTP headers, not env variables.

**Comment by skinowski** [comment]
We could update the process env in fdk-go from HTTP request for consistency, but I'm not sure if that's a good idea. @rdallman what do you think?

**Comment by rdallman** [comment]
that's right, it's in 'headers' but not env for hot. the fdk could do it i guess but i think we want to force people to grab them from our 'context' object instead of the environment, anyway, for fdks.

**Comment by denismakogon** [comment]
agreed with everything said above, but there's a difference between request URL for HTTP format and JSON format (see #535). HTTP format writes the full URL with host and port, but JSON writes only the path.

**Comment by treeder** [comment]
Yes, should return the full URL. 

The request URL is in headers for http or the protocol map in json, since it can change every request.

**Comment by skinowski** [comment]
Looking at #535 and going to close this ticket if that's ok.

**Comment by nigeldeakin** [comment]
If this is not a bug, then can
https://github.com/fnproject/fn/blob/master/docs/writing.md
be corrected?

We should also advise users how to pass parameters to hot functions. We give an example of how to pass parameters to cold functions here: https://github.com/fnproject/fn/blob/master/examples/tutorial/params/func.go which suggests we think this is a useful thing to do. So how do users pass parameters to cold functions?

**Comment by skinowski** [comment]
@nigeldeakin #659

**Comment by rdallman** [comment]
@nigeldeakin also #660 has some docs changes, let me know if this makes it more clear where to go about finding `FN_REQUEST_URL` for cold or `Fn_request_url` for hot :)

**Comment by rdallman** [comment]
closing ?

**Comment by nigeldeakin** [comment]
That's helpful. I think we could improve 
https://github.com/fnproject/fn/blob/master/docs/writing.md
a bit more. 

This starts with "We'll just talk about the default input format here" but goes on to talking about http and json as well.

It doesn't mention the relationship between hot/cold functions and function format, especially when using the fdks to allow you to implement a hot function just like a cold function. Is there somewhere which explains this?

It would be helpful if there was a hint about how to get http headers, especially when using a fdk. For example with go-fdk you call `fdk.Context(ctx).Get("headername")`

**Comment by nigeldeakin** [comment]
Created https://github.com/fnproject/fn/pull/668. Not sure how helpful 9or correct) this is, but givenm that I am criticising the docs I thought I should have a go at improving them...

**Comment by rdallman** [comment]
gonna close again, thanks for updating docs. cc @michael-w-williams
