### ISSUE TITLE
remove sleeper, error, hello images from fn repo

### ISSUE THREAD

**Issue by skinowski** [fnproject/fn#656]
fn-test-utils can (should) be able to simulate all of this functionality, therefore
remove/cleanup references to these images and decommission them from fn repo.

**Comment by denismakogon** [comment]
+1 for this, fnproject/error is relatively huge:
```
fnproject/error           latest              3a928b32cc60        3 months ago        55.6MB
```
alpine pg image is 35megs, lol, we definitely need to come up with the only one image for testing.

As side problem, unknown (really) number of images our tests are depending on pollutes local registry blazingly fast, so having 1 tagged image makes a lot more sense. Along with that, the number of functions we made for tests really makes fn repo looks like a dump of stuff we don't really want to store locally or at our own repositories.

**Comment by denismakogon** [comment]
Yeah, agreed. But not sure that that image is the last one lest there. Quick search gave at least one more image to substitute: `fnproject/multi-log` that is used at API tests as well

**Comment by skinowski** [comment]
multi-log is gone... moved to fn-test-utils.
