### ISSUE TITLE
kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1

### ISSUE THREAD

**Issue by prparmar77** [fnproject/fn#686]
I have fn call with Container as Function and after two or three calls of function I get the following error on my console 
Message from syslogd@prparmar-linux at Jan 16 16:33:06 ...
 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1

Has somebody seen this before.

**Comment by zootalures** [comment]
what version of docker and OS are you running?

**Comment by rdallman** [comment]
please report kernel version and docker version. the linked issue on moby is what we are tracking, as well :/ -- in prod workloads would generally see it after a few days of use per server.

**Comment by prparmar77** [comment]
I am running this on Oracle Linux 7
$ uname -a
Linux prparmar-linux 4.1.12-103.7.3.el7uek.x86_64 #2 SMP Tue Oct 10 11:12:18 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@prparmar-linux ~]# docker info
Containers: 41
 Running: 19
 Paused: 0
 Stopped: 22
Images: 47
Server Version: 17.09.1-ol
Storage Driver: devicemapper
 Pool Name: docker-249:2-2326462095-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 697.9GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.147GB
 Data Space Total: 107.4GB
 Data Space Available: 99.23GB
 Metadata Space Used: 8.425MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.139GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /u01/parmar/docker/devicemapper/devicemapper/data
 Metadata loop file: /u01/parmar/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.1.12-103.7.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.22GiB
Name: prparmar-linux
ID: 7NCU:JP3P:ZTLP:Z4GG:XJX6:7YBV:SYRN:CDP7:VWVC:G7DT:WVJW:R7U7
Docker Root Dir: /u01/parmar/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: www-proxy.us.oracle.com:80
Https Proxy: www-proxy.us.oracle.com:80
Username: prparmar
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Just checking if the function fails with error like timeout ,does function based on container does some short of cleaning at back end ,if not would that hang up and cause such problems.I can see that while I create route for apps it has timeout setting and possibly my container was taking longer then default 30 secs and got timeout and later would see this error.This may not be reason but just checking.While calling function it is possible to define the timeout instead of configuration while defining it.

**Comment by skinowski** [comment]
That's a really old kernel (and docker too.) Note that relevant patches went in to kernel:

https://patchwork.kernel.org/patch/9822969/

as well as other changes to that code base. Not sure if Oracle backports those to 4.1.x.

If no objections, we should close this ticket since this is not fn related.

**Comment by prparmar77** [comment]
I will try to upgrade the kernel ,what is the docker version you recommend ?

**Comment by skinowski** [comment]
@prparmar77 we are currently on docker 17.12, but also if you are deploying fn using docker-in-docker (dind) (eg if you are using fnproject/fnserver docker image), then we already ship docker inside that  which is 17.12.

In this case, the warming/error message is a kernel issue.

**Comment by cmg1986** [comment]
@prparmar77 Are you able to resolve issue?

**Comment by Testinglift** [comment]
How to solve this problem? 
my docker info is : 
linux-4ifb:~ # docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.2-ee-8
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3+20160729
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xwbml8ucv6lbqoq371a6y5qlz
 Is Manager: true
 ClusterID: ko99m62ez8gqg56ks29idea2j
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.31.37
 Manager Addresses:
  192.168.31.37:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.21-69-default
Operating System: SUSE Linux Enterprise Server 12 SP2
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796GiB
Name: linux-4ifb
ID: XR52:QXPW:NYL6:7BW5:AC7E:TJC3:IV26:AMJC:XANJ:57XE:IMO6:X3CL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
linux-4ifb:~ #  uname -a
Linux linux-4ifb 4.4.21-69-default #1 SMP Tue Oct 25 10:58:20 UTC 2016 (9464f67) x86_64 x86_64 x86_64 GNU/Linux
