### ISSUE TITLE
Unable to use a private registry with Fn deployed to minikube using fn-helm chart

### ISSUE THREAD

**Issue by venkat50** [fnproject/fn#699]
According https://github.com/fnproject/fn/blob/master/docs/operating/private_registries.md, fn supports use of private registry. Although fn deploy works, fn call always fails to pull the image from the private registry.

**Comment by rdallman** [comment]
this has turned into a series of CLI bugs, may move

**Comment by rdallman** [comment]
the issue as outlined is incorrect wrt fn, the issue as we found out was attempting to address localhost inside of the fn container. moving to #144 since this is just cli bugs, fn server handles private registries fine if they are addressable insofar as this issue goes. thanks for filing
