### ISSUE TITLE
fn installer does not work anymore

### ISSUE THREAD

**Issue by bluezd** [fnproject/fn#753]
For installing the fn :
> curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh

the `install` script does not work as expect due to version=`curl --silent https://api.github.com/repos/fnproject/cli/releases/latest  | grep tag_name | cut -f 2 -d : | cut -f 2 -d '"'` turns out to be empty.

**Comment by skinowski** [comment]
The version determination code seems functional, which os/platform are you on?

If you manually execute the following, do you see any output?

```
curl --silent https://api.github.com/repos/fnproject/cli/releases/latest
```

**Comment by mjg123** [comment]
I sucessfully used the `curl | sh` installer y'day.

**Comment by bluezd** [comment]
I did it on CentOS 7.4.

Now it works as expect. Previously when I tried to open this link https://api.github.com/repos/fnproject/cli/releases/latest I got nothing in the web browser.
