### ISSUE TITLE
Flexible triggers

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#763]
At the moment we support only HTTP requests to trigger functions. A couple more tickets for specific triggers exist:

  -  #446 suggests Kafka events as triggers
  - #21 scheduled (ie time-based) triggers

I think we would benefit from a public discussion around a more generic triggering mechanism.

**Comment by eppleton** [comment]
There could be many useful triggers, just two examples:
 - For iot projects MQTT messages on a specific topic could trigger a function with the message content as payload.
- A general scheduler would be very useful to trigger repeating tasks like backups.

**Comment by treeder** [comment]
Scheduler ticket: https://github.com/fnproject/fn/issues/21

**Comment by kocic11** [comment]
How about triggers from the cloud object storages, where a function is triggered whenever an object is inserted, updated, or deleted?

**Comment by rdallman** [comment]
#1060 ![tumblr_oeycqqq4xm1u501aoo1_400](https://user-images.githubusercontent.com/2935111/41886491-6ffab026-78b1-11e8-904f-981a5b575623.gif)
