### ISSUE TITLE
Private repos do not support more than 3 subfolders

### ISSUE THREAD

**Issue by lenalebt** [fnproject/fn#764]
/kind bug

If you use more than 3 subfolders in a private repo (with autentication) it silently fails with "no authentication". I traced the root of the problem down to this function:

https://github.com/fnproject/fn/blob/f27d47f2dd9520647f8799043bfcb3d121709958/api/agent/drivers/driver.go#L283-L295

There should be a default case for deeper nestings. If you do not want to support cases like this, at least an error log is necessary.

Workaround is to use shorter nestings. However, this can be problematic if e.g. your company forces you to use prefix folders (e.g. per team and/or parent product) that can then compose to longer names.

**Comment by rdallman** [comment]
seems like we just need to `s/case 3:/default:/` or am I missing something?

**Comment by rdallman** [comment]
thanks, this should be fixed now

**Comment by lenalebt** [comment]
thanks for the fast reaction! I will give it a shot tomorrow, but looks promising.
