### ISSUE TITLE
Support for C# support any sooner

### ISSUE THREAD

**Issue by VenkateshSrini** [fnproject/fn#791]
Hi,
Will you providing support for C# language support also? You can effectively package them as .NET core container and deploy them.

Thanks and regards

**Comment by rahamohebbi** [comment]
it might be easy to support .Net core since it is opensource and run on all the platforms. including Linux and Mac. That would be a great language to add to the supported list.

**Comment by denismakogon** [comment]
You can do that at this moment, no need to wait for the FDK. Just make sure your function packaged to the docker image and can accept requests through the STDIN and write response back to the STDOUT.

**Comment by VenkateshSrini** [comment]
Can I get a sample code or some blog links that will help us understand this

**Comment by rdallman** [comment]
hi @VenkateshSrini docs for functions formats are https://github.com/fnproject/fn/blob/master/docs/developers/function-format.md but you could get started just implementing default, it is easiest, just plaintext over STDIN/STDOUT. we have a few fdks, the go one is pretty concise https://github.com/fnproject/fdk-go if you'd like an example to work from to build json format.

**Comment by nemaroller** [comment]
As mentioned, you simply need to Dockerize a dotnet core application. 

Create a new directory on a machine with Docker and dotnet core sdk (this example uses v2.1, you may use dotnetcore sdk 2.0 so long as you make changes in the FROM instructions in the Docker file below):
```
mkdir test1
cd test1
```

Create a simple console app:
`dotnet console new`

Edit the generated Program.cs to match file below:
```
using System;

namespace test1 
{
    public class Program
    {
        static void Main(string[] args)
        {
            if (!Console.IsInputRedirected)
            {
                Console.WriteLine("Input stream not redirected");
                return;
            }

            string input = Console.In.ReadToEnd();

            if (input?.Length == 0)
            {
                Console.WriteLine("Input is zero length or null.");
                return;
            }

            //echo what was passed in back to STDOUT (of course typically you would use Newtson json 
           // Nuget package to parse into a rich object model and execute some functionality)
            Console.WriteLine("Passed to function: " + input);

       }
    }
}

```

Create a  Dockerfile at same level of a cs project file (clean with no built _bin_ or _obj_ directories):
```
FROM microsoft/dotnet:2.1-runtime-alpine AS base  #93mb
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY test1.csproj .
RUN dotnet restore
COPY . .
WORKDIR /src
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "test1.dll"]
```

**Comment by Daniel15** [comment]
I might be interested in building a C# FDK if I get some free time. Is there documentation on the contract that FDKs need to provide, or would looking at an existing one (like the Go one) and porting the same API across  be the best approach?

**Comment by denismakogon** [comment]
@Daniel15 hi! thanks for stepping up, here's the doc you've asked for https://github.com/fnproject/docs/blob/master/fn/develop/fn-format.md

Generally, you are right, try to see how other FDKs implemented. Also, you mind this article quite useful: https://medium.com/fnproject/useful-tips-for-a-new-fdk-development-78f931477c49

**Comment by Daniel15** [comment]
I started working on this! Thanks for the links @denismakogon - Very useful! I'm using those docs plus using the Node.js FDK as a reference, since it seems to have the simplest implementation.

**Comment by Daniel15** [comment]
So here's what I've done so far: https://github.com/Daniel15/fdk-dotnet/

I think I've implemented everything listed in https://github.com/fnproject/docs/blob/master/fn/develop/fn-format.md. It listens to a UNIX socket and handles HTTP requests. 

What I need help with is learning how to actually test it with Fn. I assume I need to create a Dockerfile then set some flag in the `func.yaml` to tell it to use it as a "hot function" rather than just using stdin/stdout, however I don't see anything documented at https://github.com/fnproject/docs/blob/master/fn/develop/func-file.md. How do I do this?

I guess I could eventually submit a PR to add it as a template in the CLI?

**Comment by Daniel15** [comment]
I got a basic .NET Core FDK working! Docs are here: https://github.com/Daniel15/fdk-dotnet. Let me know if you have any questions.

I'll see if I can work out how to add it as a template in the CLI... For now you need to manually create a C# project, the Dockerfile, and the func.yaml file.

**Comment by denismakogon** [comment]
you can start with init image concept we have for such cases, see https://medium.com/fnproject/even-wider-language-support-in-fn-with-init-images-a7a1b3135a6e

**Comment by Daniel15** [comment]
@denismakogon How are the build steps defined with init images? For example I tried the one in that Medium article (`fn init --init-image=mjg123/java-init`) and when you build it, it knows to run Maven. Is that knowledge still hardcoded into the Fn CLI, as the generated `func.yaml` uses `runtime: java`?

**Comment by denismakogon** [comment]
Well, build steps for java code is built-in into Fn CLI, true. However, Fn CLI also recognizes Dockerfiles. So, all you have to do is to write your own dockerfile and Fn will use that to build an image.

**Comment by Daniel15** [comment]
Right, thanks. My instructions for fdk-dotnet involve manually creating a Dockerfile at the moment. I'll bundle all of that into an init image soon. 

We can likely close this issue now, given my work on the .NET FDK?

**Comment by rdallman** [comment]
we should likely document community supported versions of the fdk in docs somewhere, while we're here? cc @michael-w-williams - thanks for the great work on this.

**Comment by Daniel15** [comment]
> we should likely document community supported versions of the fdk in docs somewhere

I was going to try write a C# tutorial for the site, once I package everything up into an init image.

**Comment by denismakogon** [comment]
@Daniel15 we also have Medium blog, so, would be nice to have your (future) post available there as well, ask @carimura when you'll have something to post.

Meanwhile, @rdallman are we ready to accept new FDKs under Fn umbrella?

**Comment by michael-w-williams** [comment]
We have a fairly standard format for the tutorials now (see the Node.js or Python tutorials) see https://github.com/fnproject/tutorials. So you can create your own, or you can go the Medium route and have me create the tutorials. Just let me know.

**Comment by denismakogon** [comment]
I like the first idea: we do have identical tutorials for various langs we support, so @Daniel15 can we ask you to write your own using one of the existing ones (pick one you like). Later we'd sort out how to turn it into a medium post.

**Comment by rdallman** [comment]
I think I was aiming a little lower, with a link to https://github.com/Daniel15/fdk-dotnet somewhere around [here](https://github.com/fnproject/docs/blob/master/fn/develop/fdks.md#officially-supported-fdks) saying 'community supported FDK' or some such, to make these kinds of things easier to find for users. open question what to do about CLI runtime, I think tutorial is perhaps optional for non officially supported fdks -- though, it would be great, and a blog + tutorial would be over the moon

**Comment by michael-w-williams** [comment]
@rdallman That's sounds good to me. We just add the subheading to that page when the FDK is ready.

**Comment by Daniel15** [comment]
Init image works great!
```
fn init --init-image daniel15/fn-dotnet-init
```

I'll try to submit a tutorial for the site soon. 😃

**Comment by carimura** [comment]
nice @Daniel15 !

**Comment by Daniel15** [comment]
I think this can be closed now. C# tutorial is up: https://fnproject.io/tutorials/csharp/intro/

**Comment by rdallman** [comment]
sweet, thanks!
