### ISSUE TITLE
Proposal: Splitting functions from routes

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#817]
While talking with @vshiva , the concept of functions being separate from routes came up and it got me thinking a bit. 

Currently, a `route` is both a function definition and an HTTP route to that function. But what about when you don't want or need an HTTP route to the function?  

A `function` needs the container image reference, format, memory, timeout, etc. It doesn't care about HTTP or what protocol is being used to call it, it's only dependency is a Docker registry. 

A `route` as it is right now needs things like: path, image name, some HTTP specific things like content-type. If we separate functions, then it would need a reference to a function which isn't simply a Docker image URL. 

What's the benefit?  Well as @vshiva pointed out, say you have a UI that lets you tie things together: "when X happens, run this function with X's event data". How that's hooked together behind the scenes doesn't really matter to the user, could be via a message queue, could be a webhook. 

This got me thinking of the decades old "function hub" conversations (cc @carimura), but perhaps more of a "function registry". In it's simplest form, it would just be a way to CRUD a function object with the things above. Then when we create routes, we give it the function URL which is a reference into the registry. This could be a separate API in itself, but probably build it into Fn initially.

**Comment by denismakogon** [comment]
> Currently, a route is both a function definition and an HTTP route to that function. But what about when you don't want or need an HTTP route to the function?

This statement implies to Triggers API. So, we have apps, functions, and we have API to define the triggers, say I want to create an HTTP trigger to my function. It really makes sense to start this type of the discussion. Also, we already have the type of the event in JSON protocol which is defaulted to `http`, so having the Triggers API really makes sense.

> A route as it is right now needs things like: path, image name, some HTTP specific things like content-type

So, in future, i would like to turn the route to a function into a trigger type in terms of HTTP triggering. It would need to have a reference to the function and an HTTP path attribute, event the route config would no longer make sense because of the configuration really belongs to the function rather than to a route.

**Comment by treeder** [comment]
The required config would belong to the function (ie: it defines it's own input), but the actual values should be somewhere else, defined by the user who's using the function. The app level config still makes sense, maybe the route level config does too. If it's using the example above where there's no route, then maybe config should be defined in the trigger?

**Comment by carimura** [comment]
yes I've been struggling a bit with our coupling of routes and functions. The market tends to think of things as functions and triggers ala the major providers as well as many of the other frameworks. Denis mentions this above.

I'm 100% behind splitting the two apart.

**Comment by denismakogon** [comment]
> If it's using the example above where there's no route, then maybe config should be defined in the trigger?

How do you see the trigger config, what that would be for? So, the app config is a global thing for functions, function's config is unique things to itself. I do see a need to leave headers but strip out config because it has nothing to do with a route itself (this is what we have right now) but useful for the function.

But on the other side, assume i want to trigger a function with MQ event, i need to tell the Fn how to connect to the MQ, so trigger config may be useful.

**Comment by rdallman** [comment]
> But on the other side, assume i want to trigger a function with MQ event, i need to tell the Fn how to connect to the MQ, so trigger config may be useful.

I think the intent of trigger config was to move the map[string]string of `route.Config` to `trigger.Config`, not the configuration of the trigger itself, but rather, the configuration passed to the function at execution time.

trigger configs, as interpreted otherwise, should probably not exist in fn but really we should have interfaces for various streams of events and each of those can configure itself. I have a proposal in the works on this, though it's been sidelined until migrations work [for me]. I do think we need to change the eventing model of fn to something more robust than simply http events and our own async bus. Loosely based on https://github.com/apache/incubator-openwhisk/blob/master/docs/feeds.md as openwhisk seems to have done a great job here for definitions for things like kafka, however, it does not seem to have a very good answer around the 'push-based' model which I think we need to support as well. I also don't think this necessary precludes splitting them entirely apart, as we have it now essentially each function's identity is a default route and 'it works' but we need additional ways to say call function X when I pull a message from a topic, too, without having to thread through the http frontend.

**Comment by shaunsmith** [comment]
Implementation details aside, separating a function from the invocation mechanism clearly makes sense.  I always assumed we would be adding additional mechanisms as we moved forward.

**Comment by zootalures** [comment]
+1 from me
Couple of thoughts: 

I don't  think this should/needs to make any commitments about who owns the link between a function and its source - and I think eventually both "source owns link to fn" and "fn owns link to source" are likely and possible. 

e.g. 
* For local/simple HTTP gateway makes sense to orchestrate this from fn  - adding an HTTP trigger in func.yaml implies that Fn takes responsibility for hooking it up to it's (the current) HTTP gateway
* for more complex (non FN) gateway makes sense to specify a fn ID/ref in the config
* for <some other event broking stack> it's that plaforms stack to solve

Where a function is not published, I suggest we look at an authenticated API call pattern to send events directly to functions (e.g. a model based on current raw JSON), ideally one that supports streaming and back pressure. 

So, if you agree with above this makes sense in lots of ways for me: 

* We can keep the current "simple" HTTP gateway model (everything we have now works - good simple/first experience ) 
* making a function public is an explicit choice (no strange oddness around authed/unauthed access to the single HTTP endpoint) 
* Stream sources are left as something that can either be solved within (e.g. Async calls) or outside the platform (e.g. Kafka Connect adapter)

**Comment by zootalures** [comment]
Thinking about it, can somebody provide me with a concrete/real use case where somebody would need to attach two triggers to the same function? 

I can't think of one.

**Comment by jan-g** [comment]
Examples drawn from, say, CD might arguably be the same trigger with different parameters. 
If i have multiple sources for those events i may want to hand out credentials infividually (or manage loggong/audit for those separately).


-- Excuse typos. Phone screens don't make great ketbroads. 

-------- Original message --------

**Comment by rdallman** [comment]
If I run a social network and have a function that resizes an image to a configurable size and outputs that image:

* it's likely that there are multiple different types of images. say, profile photos, which may need smaller thumbnails drawn as well as user uploaded photos which may want to keep varying sizes of (for mobile, desktop, etc.)
* it's likely that as a storage backend these images are not all going to be stored in the same spot to do post-processing from (though, this isn't impossible, it seems unwise at a certain scale..), but I would like to trigger the drawing of the various image sizes needed for each image after the user uploads it into my storage system (say some s3 store). this means when there is a new user and they upload their first photo, the system needs to create a bucket to put these photos and attach a trigger onto that bucket w/ the photo resize function.
* it follows that: the same function can be used to do resizing across all of the various images (woo!), but I will need to attach it to each user's photo bucket (and most likely wire up another function to store the post-processed images somewhere handy)

I think that works as an example, but i'm only 1/2 a cup in today.

**Comment by carimura** [comment]
Or any case where multiple teams reuse the same function but give it its input in a a different way? (ie one team uses Kafka while another just wants webhook)?

**Comment by vshiva** [comment]
>Thinking about it, can somebody provide me with a concrete/real use case where somebody would need to attach two triggers to the same function?

Use cases akin to Biz logic re-use
For example, 
Function that can generate invoice which can be invoked in an offline mode due to a event in a queue or a user clicking a button that says generate a invoice now. ( Which is a HTTP Trigger)

This gives us the notion of Functions as a collection of library which can be composed to do a specific business flow by higher level services/tools .

**Comment by treeder** [comment]
Here's some more details on how this could work. 

## Objects

This breaks Route and Function apart. Routes depend on functions, but not the other way around. 

```go
type Function struct {
        ID string
	// repo-host/Namespace/Name:Tag make up the fully qualified name
	Namespace string
	Name      string `json:"name" db:"name"`
	Memory      uint64          `json:"memory" db:"memory"`
	CPUs        MilliCPUs       `json:"cpus" db:"cpus"` // hopefully this is just a hint?
	Type        string          `json:"type" db:"type"`
	Format      string          `json:"format" db:"format"`
	Timeout     int32           `json:"timeout" db:"timeout"`
	IdleTimeout int32           `json:"idle_timeout" db:"idle_timeout"` // ?
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
}

type FunctionVersion struct {
        //  FunctionID reference to Function
        FunctionID string
        // Tag/Version is the version tag of a specific build
        Tag/Version string 
        // The Docker image for this build.
	Image       string          `json:"image" db:"image"`
        // QUESTION: Update the other params for each version or keep them all at the top level?
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
}

type Route struct {
	// The grouping of routes into an app is specific to this type of trigger
	AppName string `json:"app_name" db:"app_name"`
	Path    string `json:"path" db:"path"`
	// Function a fully qualified function name referencing a function in a repository, similar to a Docker image. eg: `funchub.fnproject.io/jimbo/somefunc:1.2.3`
	Function string `json:"function" db:"function"`
	// Config is required by the function, but set in the trigger, ie: the caller.
	Config Config `json:"config,omitempty" db:"config"`
	// Annotations trigger specific?
	Annotations Annotations     `json:"annotations,omitempty" db:"annotations"`
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
	// Trigger specific
	Headers Headers `json:"headers,omitempty" db:"headers"`
}
```

## Deploying

`fn deploy` could work the same to a user, but we build, push, update the `function` object then the `route` object. One extra step.

**Comment by rdallman** [comment]
is a 'route' a first class citizen or is it a 'trigger' that happens to be an 'http trigger' where we have something along the lines of 'annotations' to have trigger specific stuff (for http: headers, path)? this would be more easily extensible (2 birds), but I could see a case for routes being first class too I guess.

no grouping of functions? both seem potentially useful (by app), there are likely subsets of functions that are related vs having a giant pool of functions and having to determine their relationships from triggers or keeping an excel sheet or something.

should function have id and version and be able to point lookup past versions at a certain id? otherwise, how to see history for a certain function? are we imposing a version format so that these could be guessed or otherwise listed?

(thanks for spec, a great start)

**Comment by carimura** [comment]
There doesn't seem to be a standard language yet for this stuff. AWS uses "event sources", Azure uses triggers, OpenWhisk uses triggers (although they call funcs `actions` so....)

I vote for Triggers being first class.

**Comment by rdallman** [comment]
Am going to try to calcify some of the material from this thread into something cohesive to pick over. One thing that sticks out is management of the routing table itself being a part of fn, as well as fn owning the triggers & their configurations. I think it may be easier for fn server not to own these at all, only a set of functions (perhaps under an app/namespace/both), and let triggers do their own configuration where they simply push events to fn and fn exposes a minimal surface area to post events (an http endpoint and a grpc endpoint?) and get a response. we can expose from `fn start` an fn that embeds a gateway (which would be similar to fnlb in nature, but with a routes api, and that isn't directly a proxy but also translates current http event format to a [json] concrete event format), that has an api for the routing table in it -- this may sound confusing, I think it should be straightforward and may make more sense once fleshed out -- anyway, it would give similar behavior to what we have now for the OSS 'getting started' story to keep that easy, but be much more flexible to more complex installs. the critical steps here seem to be extracting function and event out, hope to have an api document as well as a design document to work off of. the basic idea being that a trigger is capable of doing its own event generation, transformation to an fn event and invocation against fn, where e.g. for http it translates url paths to a function id. pre-empting feedback of general idea ^ - open. 

imo we should wait to add versioning and namespacing and cloud events format as this is a pretty big shift in its own right. 

low hanging fruit questions:

* are apps sets of functions?
* are apps sets of routes?
* spending some time traversing the nulb stuff to figure out requirements there, it seems that exposing a grpc endpoint to submit events is enough there? a protobuf spec of our 'event' format seems easy enough to maintain alongside json.

**Comment by rdallman** [comment]
thanks for replies. immediate one that sticks out is:

> So, Fn should have an API endpoint that describes available triggers (http, kafka, grpc, mqtt, etc.) and there should be an API to build an association between the function and the trigger (user can create 2 grpc paths to call the function, user wants to call a function by pushing the message into 2 different topics and so on).

intuitively it seems like a trigger is the one that glues some thing like a queue or a route to a function, not fn server itself. it's hard to think about making a generic binding that works for every trigger type that would be nice to work with, and it also doesn't seem like fn server necessarily cares about this association, if it simply consumes events and outputs them. the thinking is that each trigger has its own way of mapping its specific ingest points onto functions, and the api could be there; for http, this could be a url path, for instance (as it is now). to the user, if we by default have an embedded gateway that has this `url path -> function` mapping, we keep the behavior we have now, but the route mapping is pushed into the gateway, and not in fn server itself (as now). anyway, seems odd to have fn server store triggers and mappings, and the ux might get pretty bad trying to do it generically. thoughts?

**Comment by rdallman** [comment]
> Trigger interface bothers me most, it doesn't look good to have a single process that exposes GRCP interface, HTTP interface (maybe with GRPC since both using http, don't know), MQ interface.

the hard line is when we want to start optimizing and do things like the remote slot thing, just having an 'invoke event' endpoint isn't sufficient in itself, we need to expose capacity information and possibly configure fn to behave a certain way.  for other kinds of triggers like the MQ trigger, I think we have some options; an MQ trigger could be baked into fn itself and invoke events directly against the agent instead of going through the exposed invoke path. we need to think about cases like implementing events off of an object store, is this trigger built into the object store and hitting our invoke endpoint remotely or is it queueing events against something and fn is polling that event queue?

agree that as a platform we need 'MGMT API for creating apps, functions, function-to-trigger bindings.' and this not necessarily being in fn server.

**Comment by rdallman** [comment]
Additional food for thought, do we want to have triggers that allow a certain trigger to invoke 2 functions? this would make sense to have an API to manage, and muddles at least what I had thought a 'trigger' was defined as (a concrete thing that invokes functions, e.g. API gateway, kafka connector, etc). to steal openwhisk terms, what I think we have been calling a 'trigger' is a 'feed'. and a 'feed' invokes 'triggers'. and a 'trigger' may call multiple 'actions', where an 'action' is what we have been calling a 'function'. this flow is kind of complicated to grasp, but it is pretty robust once you get the hang of it. do people like that? I suppose we could start off with the bare minimum of simply having an 'invoke function' endpoint, and later we could add 'triggers' in that capacity. and start calling things like API gateway a feed or some such :)

**Comment by rdallman** [comment]
>  and start calling things like API gateway a feed or some such

vessels? it adds extra corn to the 'docker' vernacular

**Comment by carimura** [comment]
relevant changes in Kubeless 0.5.0: https://github.com/kubeless/kubeless/releases/tag/v0.5.0

```
Breaking change: The command kubeless route has been replaced with kubeless trigger http. This will create a new Ingress rule to expose a function outside the cluster. You can now also specify a path to deploy your function. More info here

Breaking change: Function Triggers have now their own Custom Resources. The same function can now be triggered from several event sources using a single Function deployment. That means that it is required to create a specific Custom Resource to trigger functions using Kafka messages or with a scheduled cron task. There are new commands available to do so, check kubeless trigger --help to discover these commands. Architecture details can be found here.
```

**Comment by rdallman** [comment]
their api spec for events looks to implement ["Cloud Events"](https://github.com/cloudevents/spec/blob/master/spec.md) and their triggers are similar to openwhisk. thinking that's the direction we should go, same concepts as openwhisk but slightly different implementation (they have runtimes, some other stuff around triggers is weird).

**Comment by treeder** [comment]
OK, here's an updated proposal:

## Functions

Functions are standalone entities that have only one dependency, a Docker image. They will have some URI to reference it, eg: `fnregistry.fnproject.io/NAMESPACE/FUNCTION:VERSION` 

### Models

```go
type Function struct {
        ID string
	// repo-host/Namespace/Name:Tag make up the fully qualified name
	Namespace string
	Name      string `json:"name" db:"name"`
	Memory      uint64          `json:"memory" db:"memory"`
	CPUs        MilliCPUs       `json:"cpus" db:"cpus"` // hopefully this is just a hint?
	Type        string          `json:"type" db:"type"`
	Format      string          `json:"format" db:"format"`
	Timeout     int32           `json:"timeout" db:"timeout"`
	IdleTimeout int32           `json:"idle_timeout" db:"idle_timeout"` // ?
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
}

type FunctionVersion struct {
        //  FunctionID reference to Function
        FunctionID string
        // Tag/Version is the version tag of a specific build
        Tag/Version string 
        // The Docker image for this build.
	Image       string          `json:"image" db:"image"`
        // QUESTION: Update the other params for each version or keep them all at the top level?
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
}
```

### CLI interactions

We continue to have a `func.yaml` for functions that defines the metadata for the models above. The these are the commands used for raw functions. 

```sh
fn build
fn run
fn push # new command that bumps, builds, pushes image, updates function object and version
```

## Triggers

Triggers replace our current routes model.  Each trigger associates itself with a single function. Support http out of the box, new types of triggers can be added with extensions. 

### Models

```go
type Trigger struct {
	// The grouping of routes into an app is specific to this type of trigger
	AppID string `json:"app_id" db:"app_id"`
	// Function a fully qualified function name referencing a function in a repository. eg: `funchub.fnproject.io/jimbo/somefunc:1.2.3`
	Function string `json:"function" db:"function"`
	// Config is required by the function, but set in the trigger, ie: the caller.
	Config Config `json:"config,omitempty" db:"config"`
	// Annotations config for environment function will be running in?
	Annotations Annotations     `json:"annotations,omitempty" db:"annotations"`
	CreatedAt   strfmt.DateTime `json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   strfmt.DateTime `json:"updated_at,omitempty" db:"updated_at"`
        // Type of trigger, eg: `http` (default), `timer/scheduler`, etc. 
        Type string 
	// Trigger specific metadata
	TriggerConfig map[string]string `json:"trigger_config,omitempty" db:"trigger_config"`
}
```

### Routes (the default trigger type)

This will have some extra items in TriggerConfig (just using Go here to be consistent, but it would be an arbitrary map). 

```go
Path    string
Headers Headers
```

### CLI Interactions

We create a new `trigger.yaml` file that defines the trigger information for the models above. A directory can have a `trigger.yaml` and a `func.yaml` if you'd like to keep them together. 

```sh
fn deploy # fn push + update trigger
fn <verb> triggers # for dealing with triggers directly, similar to routes right now
```

## Apps

Similar to apps relationship to routes right now, but will be a collection of triggers instead, typically an http route, but can be any type of triggers add via extensions.

```
App ->* triggers -> functions
```

**Comment by rdallman** [comment]
> Triggers replace our current routes model. Each trigger associates itself with a single function. Support http out of the box, new types of triggers can be added with extensions.

it seems common to have a mapping of this where a trigger can invoke multiple functions (openwhisk, kubeless, at least). triggers seem to be simply this mapping in most interpretations, not specifying some type of 'trigger' that they are, where the definition of 'trigger' being used would be more of a 'stream' that invokes 'triggers' which simply map to functions (this allows multiple different triggers to invoke different combinations of functions). obviously, we can call things whatever we want, but we need to define terms and such. openwhisk docs on triggers are https://console.bluemix.net/docs/openwhisk/openwhisk_triggers_rules.html#openwhisk_triggers and this model seems useful. these are _not_ the actual thing that invokes triggers (e.g. an http router), as implied.

can we skip version for 1.0? let's get a reasonable data model first.

moving routes API to the router? (which we can embed)

concept of app or grouping of functions/triggers makes sense, but still seems kind of hazy. proposed has triggers that have app, to bundle together functions at the trigger level (and implies functions don't exist on app?). at this point, app is basically a trigger specific grouping and kind of goes away in fn. not sure what we want, clarifying.

**Comment by treeder** [comment]
> at this point, app is basically a trigger specific grouping and kind of goes away in fn. not sure what we want, clarifying.

What do you mean this goes away in Fn?

And let's not blindly follow OpenWhisk, should avoid complexity all costs and their `rules` look essentially like `workflows` which should not be a core part of this. 

Always KISS.

**Comment by rdallman** [comment]
> What do you mean this goes away in Fn?

simple question is: are apps a grouping of triggers, or a grouping of functions?

**Comment by rdallman** [comment]
or both?*

**Comment by denismakogon** [comment]
@treeder thanks for the update. However, i'd like to change what you've proposed here.
I'm totally good with a function model (and its version), but i do see triggers as standalone objects (users should be capable to list triggers through the Fn API), so the `Trigger` model that you've posted does seem to be a trigger-to-function mapping (association between a function and the trigger). Moreover, one function can have more than one trigger at the same time.

Also, isn't annotations are for the metadata? Why should the trigger have an annotation and trigger-config at the same time? If we're talking about routes thing, so that should go to the annotation mapping.

@rdallman answering your question, an application (in the context of its current definition) is a group of functions (if each function has a trigger then we'd consider the application as a set of trigger-to-function mappings because of the functions without a trigger is useless).

**Comment by treeder** [comment]
> simple question is: are apps a grouping of triggers, or a grouping of functions?

I'm proposing it's a grouping of triggers. And since triggers need a function to do anything, it's kind of both. A function can be used with multiple triggers. If we get into workflow down the road, a trigger could fire off a workflow instead of a function (similar to OpenWhisk rules/step functions), but I'd say we leave that out of 1.0.

Let's think about a few common triggers:

1. http
1. timer/scheduler
1. a message queue (kafka, redis, etc)

Those triggers probably cover nearly all cases (or am I missing anything?). We'll assume events from infrastructure or other SaaS apps will be using one of these (1 or 3).

When defining an application, it may consist entirely of http triggers (ie: an API). But you may need some periodic functions so you have a few scheduled functions. And you may listen for events from infrastructure so you have some `mq triggers` too. It's the triggers that define what the application does.

**Comment by treeder** [comment]
Sorry, changed it to "trigger types", better?

**Comment by rdallman** [comment]
one thing, i don't think we should have to tie triggers to trigger types. to me, i think that this is part of the [event](https://github.com/cloudevents/spec/blob/master/spec.md) and when e.g. an http router invokes a trigger, in the event it puts 'event-type: my-http-router'. this makes triggers more flexible, at a minimum so much as a user won't have to define multiple identical triggers for each uh, event source (or trigger type, as you say).

**Comment by rdallman** [comment]
done #1060
