### ISSUE TITLE
Namespacing in URLs

### ISSUE THREAD

**Issue by treeder** [fnproject/fn#819]
The out of the box experience has no namespacing, but after you add authentication, there's probably a lot of people that would want that reflected in the URL (GitHub style). eg: `/ns/{namespace}/r/{func}`. This also applies to the API, would add another layer, eg: `/v1/ns/{namespace}/apps`. 

So do we make this part of base experience?  If so, the default when working locally could just fill it in with a dummy value, like: `/ns/local/r/{func}`

**Comment by carimura** [comment]
Think this makes sense. many sites don't even require the /ns/ as it's always just the first value. idk if that could/should be the case here.

**Comment by zootalures** [comment]
Yah we can discuss on slack - @rdallman and @vshiva  and I discussed a couple of options that can work for the use case we have in mind  without needing this 

If that sticks then whether this feature gets added is based on its own merits

**Comment by jan-g** [comment]
I particularly like exposing this on the API side. There are a number of ways in which middleware might rewrite requests (much like the current DNS extension) and this gives an abstraction that can be surfaced at the API layer to express those. Then the API can sit at a different URL to the invocation point.

This kind of approach offers one avenue to model tenancy as a first-class thing, too (although there may be other ways to reflect that in the API).

**Comment by rdallman** [comment]
we nixed this as the sentiment was 'why we don't need this look we're doing it this other way without first class support and the world hasn't fallen into a black hole' -- we could probably still afford to do this and it's probably going to come up again, but closing for now, we could at least doc the 'other way' maybe for potential white label / multi tenant consumers
