### ISSUE TITLE
json protocol leaving bytes in its wake

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#827]
I am not sure if this is an issue with fdk-go or with fn, both are possible. if it turns up to be an fdk-go issue, we can move this there (easy enough to verify that, pardon me for not doing that).

repro (ensure CLI is on tip):

```
$ fn start &
$ mkdir dawg
$ cd dawg
$ fn init --runtime go
$ fn deploy --app yo --local
$ curl -sSL localhost:8080/r/yo/dawg
{"msg":"Hello world"}
```

so the function works (and is hot, it's json). but the logs on fn server will appear:

```
time="2018-03-09T02:25:19Z" level=info msg="starting call" action="server.handleFunctionCall)-fm" app=myapp container_id=01C849796S47WKC00000000000 id=01C8497CEG47WKE00000000000 route=/dawg
time="2018-03-09T02:25:19Z" level=info msg="hot function terminating" app=yo cpus= error="Excess data in stream" format=json id=01C849796S47WKC00000000000 idle_timeout=30 image="dawg:0.0.2" memory=128 route=/dawg
time="2018-03-09T02:25:19Z" level=info msg="hot function terminated" app=yo cpus= error="context canceled" format=json id=01C849796S47WKC00000000000 idle_timeout=30 image="dawg:0.0.2" memory=128 route=/dawg
```

i.e. the hot function terminates immediately after the first request.

changing the format to http:

```
$ fn routes update yo dawg --format http
$ curl -sSL localhost:8080/r/yo/dawg
{"msg":"Hello world"}
```

and there's no such logs about the hot function terminating instantly, so it seems like it's a json protocol issue somewhere in the fdk-go or in fn itself. the behavior to check for clear pipes is relatively new and I don't recall any issues with input containing extra bytes prior, so this seems a little weird.

I have a feeling our json objects are gratuitously delimited. i need a neti pot, a tea and an 8 hour nap about now though, thank you kind soul for solving this :)

**Comment by skinowski** [comment]
#830 fixes this.
