### ISSUE TITLE
Conventions around authnz

### ISSUE THREAD

**Issue by jan-g** [fnproject/fn#842]
For any kind of pluggable authentication layer (implemented through a middleware interceptor), do we want principal details to show up under a predictable, conventional name (or names) attached to the request? (Eg, USER, PRINCIPAL, AUTH, FN_AUTH, ...?)

For authorization decisions, the potential scope of how these are specified (in a function* config) will depend upon the implementation - however, I wonder if there's still room to say, "find your authz policy attached to the FOO configuration parameter".

As a user, it'd be nice if my functions could depend upon a consistent approach for this - even if the actual details of the authnz configuration depended upon the platform that I was deploying to.

* "function" here meaning app, route, namespace, what-have-you.

**Comment by zootalures** [comment]
I’m closing this as I think we are covering it elsewhere
