### ISSUE TITLE
Extension mechanism should allow extensions to be cleanly shutdown

### ISSUE THREAD

**Issue by gviedma** [fnproject/fn#850]
We are missing a mechanism for extensions to perform cleanup/shutdown operations as part of the server coordinated shutdown. The server should go through all plugins and shut them down prior to shutting itself down. In the meantime, it should not accept new requests. I propose extending the Extension interface with a new method _Shutdown_ as follows:

```
type Extension interface {
	Name() string
	Setup(s ExtServer) error
        // orderly shutdown of plugins
        Shutdown(s ExtServer) error
}
```

**Comment by hhexo** [comment]
There's also the opposite problem, i.e. an extension failing and causing the system to shut down. This could be helped by what I've added in #834: using that mechanism extensions could register their own contexts (say, if they're running servers that can be cancelled) and the main thread will wait on those. Maybe we need more than that though.

**Comment by gviedma** [comment]
Closing for now since we have a few workarounds.
