### ISSUE TITLE
add the ability to "bring your own agent" for fn configured in hybrid mode

### ISSUE THREAD

**Issue by reclaro** [fnproject/fn#871]
At the moment there is the option to have hybrid API which allows splitting runners node from the API itself. To do that there is the definition of a hybrid client which implements the agent.DataAccess interface.
It would be useful to enable the load of the hybrid agent via an extension mechanism (or something similar) so as it would be possible to "bring your own agent".
There are some use cases where that could be really useful, a simple one would be, for example, the ability to pass extra parameters to the fn API using custom HTTP headers.
We could have the option to use a custom hybrid agent and if not specified fall back to the default hybrid agent we use now.

**Comment by rdallman** [comment]
this is in place, I believe https://github.com/fnproject/fn/blob/master/api/server/server.go#L344 ?

**Comment by reclaro** [comment]
Thanks @rdallman  for your answer. I think I messed up the terms here. What I was thinking is to be able to define a new hybrid client (for example here https://github.com/fnproject/fn/blob/master/api/server/server.go#L402), which is the struct that implements the agent.DataAccess interface (https://github.com/fnproject/fn/blob/master/api/agent/data_access.go) as we have a neat interface already defined it could be handy to have a way to plug a custom implementation for it.

**Comment by rdallman** [comment]
got it. I think it could be done by using `WithAgent` instead of `WithAgentFromEnvironment`, `WithAgentFromEnvironment` seems to do too much (and have useful bits) and is a bit of a mismatch with our other configuration. worth tinkering with

**Comment by hhexo** [comment]
Since we merged #872 you should be able to pass an alternative hybrid client as a DataAccess to the LBAgent. Is this enough?
