### ISSUE TITLE
Container contract: HTTP server in container instead of STDIN/OUT

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#896]
Pulled this out of a conversation in slack:

> How hard is it for us to move off of stdin/stdout in fn? I'm referring to amending our fdks to support listen/accept tcp model instead of stdin/stdout. IMHO, a busy service should not run on stdout/stdin. which strategically ties us to 1 request at a time. Also docker muxes/demuxes stdio, which is a head-of-line blocking + bottleneck there. With tcp listen/accept model, we can potentially run more than 1 req at a time on a container. But we'd have to limit customer contract.. How feasible is this? Similar to discussions on dropping cold format, can we do another leap and do this as well?

> Most high level recent languages have built-in (or easy to add) web server/ sock server. So, it becomes bring your own web server.

> This would open up the possibility of k8s managing function containers as well

> much more usable code compared to stdin/out... take that function code and make it a server... run as vm, etc.

> With /dev/tcp support the bash fdk grows by about a dozen lines to support this :-)

**Comment by mjg123** [comment]
Open question from @carimura : 

> how would BYOD get its input? and are we considering others running a service (not just OCI service)?

**Comment by skinowski** [comment]
IMHO, I think we should take #785 even further. Let's say we agreed on json, we should also move off of stdin/stdout and switch to listen/accept tcp socket instead. A few reasons:

1) stdin/stdout in docker is processed by dockerd/containerd and has mux/demux applied to it. It has head-of-line blocking and processing bottleneck.
2) stdin/stdout does not scale. (Unless we pipeline json requests through docker mux/demux.)
3) serving json as a web server in a container/function is more usable code. (you can use a web server anywhere.)

which becomes BYOW, bring your own web server (or tcp server.)

We can support it in fdks, or ask customers to implement a web server. Here's a ruby version:

https://github.com/fnproject/fn/blob/5f9518e400a7d4190ca8a64aa1b988154f86abba/examples/appfunc/rfunc/func.rb

Some related work before: https://github.com/fnproject/fn/pull/713 , but I'm not sure how to go about the transition. System wide option? Per route option? Or agree on this overlay/communication and hard switch? etc.

**Comment by rdallman** [comment]
> which becomes BYOW, bring your own web server (or tcp server.)

fdk could make an opinion on this in each lang, as well, and then it's not necessarily BYOW, just import the fdk.

**Comment by rdallman** [comment]
> System wide option? Per route option? Or agree on this overlay/communication and hard switch? etc.

i guess if we reduce all formats to this, then a lot of code dies, but to ship it maybe just an additional format for now? "jsoncats" format? there's a lot of decisions around dropping all the formats/cold/etc. we could keep separately and wait to rip the band aid off

**Comment by treeder** [comment]
The problem with all of this and BYOW is that you're bringing your own web server and your function is no longer a lightweight function. And at that point, why even bother using a FaaS at all?

**Comment by denismakogon** [comment]
@treeder agreed, this is what Azure does with [their runtime](https://medium.com/@juanpdantur/azure-functions-on-a-docker-container-7e76872c40cf). The only two benefit I can see here, no FDKs, native concurrency, but it makes serverless useless in general, so there are obvious limits when serverless function turns into the lightweight web server.

**Comment by gviedma** [comment]
Also if we start supporting concurrent requests, in the most naive implementation this would require the function developer to have to worry about synchronization, which in my mind was one of the key simplications that serverless less brings to the programming model.

**Comment by skinowski** [comment]
I'm not following the argument why this is against serverless/faas. Google/AWS seems to provide a handler for example, they are doing exactly the same thing by providing a handler over likely a web (tcp/grpc) server of their own. We'd be providing best of both worlds: concurrency **and** if you don't want to use fdk (which would use a web server), then customers can implement a web server on their own. Both support for BYOD with additional requirements, but this is a model that actually scales.

A web server may have more applications, eg. move a vm or actual server into faas or vice-versa, and has more mobility compared to stdin/stdout. In comparison, how many enterprise workloads have we seen using stdin/stdout?

I recall very recently in Fn slack someone wanted to move their python app, but was thrown off by one request at a time restriction. Not surprisingly this was an app already handling concurrency, with DB connection pool, etc. He said;

"@tolga, thanks for that description. I think if we ended up adopting Fn at our studio we would need to implement our own way of doing the concurrent server approach. Not everything can spin up to a ready state in sub-second time, and it seems like too much overhead to be spinning them up on concurrent access. We would end up having to increase the idle timeout alot to keep all these instances warm so they can keep servicing load."

and 

"Is it better to have 1000 instances running with 1000 database connections?"

**Comment by rdallman** [comment]
to @gviedma 's point I think the hardest thing is going to be controlling concurrency and resources around changing to having a concurrent request per container model. in the new model we change from something where it's a __function__ gets X amount of resources, for cpu, ram, disk, etc. and if we move to having concurrent requests in a container at a time it's much harder to grasp resource utilization from a user perspective and nigh impossible for us to give the previous per function resource semantics, and the semantics would be something like a __container__ gets X amount of resources, for cpu, ram, disk, etc. and there's then likely some separate api to set concurrency on a container itself. we could default this to 1 and get the exact semantics we have now, where we wait for a response, and then look at adding an option to let this tick up to some N at a users wishes, to handle the case @skinowski brings up from a user the other day. this is maybe a good trade off, we've had similar conversations around this before and it could be treated as a kind of 'power user' feature where we let users shoot themselves in the foot with it if they want, but out of the box we have the same behavior we have now. we could even keep the shutdown on timeout behavior like we have now to effectively disallow user requests that go over the timeout to muddle the state of the container for subsequent requests, and maybe that's a pill we can swallow until we figure out something better.

**Comment by mjg123** [comment]
Nothing in this suggestion makes the user *need* to handle concurrent requests. `max concurrency` is a thing most FaaS I've seen tend to support, and we could still hard-code it to 1 if we don't want to spook people.

Regarding this being somehow anti-serverless, I don't really get that.  Seems to still support the principles in the serverless manifesto. "Why even bother using FaaS at all?" - No infrastructure visible to the user, transparent scaling, not paying for idle, etc etc.

**Comment by skinowski** [comment]
@gviedma Synchronization is a good point. I agree with you that this adds complexity, but also note that we do provide CPU resource to these functions. So, we are basically telling operators/users that they can use multiple CPUs. In addition, functions if they are implicitly or explicitly forking threads already need synchronization in our eco-system. (eg. if you try to access previous request or stdin/stdout in a go routine for example, you can be executing parallel to another go routine handling next request.)

**Comment by skinowski** [comment]
There's also a few technical reasons in fn agent we'd want to do this... For example, in stdin/stdout model, what do you do if your request timed out? How do you ensure next request will go through stdin/stdout? Can you keep those pipes clean between requests? How do you handle a response that is too big? And still process next request? Today, in most of these cases, we have to kill the hot container since we cannot recover. Web/tcp servers/clients already have solved these problems.

**Comment by shaunsmith** [comment]
I agree with @treeder's earlier comment asking why even both to use FaaS if you require developers to take on so much responsibility and complexity.  I love the Fn experience over the typical Heroku-style cloud native app which requires you to use an embedded web container. The whole point of FaaS is the ability to deploy small simple chunks of functionality that don't require an embedded container--the platform is the "container".  So if the platform is lacks functionality that users need let's focus on those things.  If you don't like the FaaS model then you have lots of other deployment choices out there--many of which are also serverless, to @mjg123's point, but aren't FaaS.

**Comment by skinowski** [comment]
related: https://github.com/fnproject/fdk-node/issues/5

Another difficult issue due to stdout/stderr contract.

**Comment by skinowski** [comment]
And you constantly have to worry about function code itself or the libraries that it pulls in could write something to stdout and corrupt the output. This will kill the hot container. Compare this to processing on a per request socket. It's more robust and we can probably get rid of significant amount of Fdk code that we have support. nodejs, ruby fdks are overly complex due to custom parsing. Modern web handler approach, where most of these languages have already built in http/tcp service support, can take that down to a few lines of code. See my example post above (Travis's ruby example.)

**Comment by rdallman** [comment]
so I think we can close this one now with uds stuff
