### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when FN_API_URL is not set 

### ISSUE THREAD

**Issue by amyroh** [fnproject/fn#907]
From OCI, if FN_API_URL is not correctly set, `fn deploy` will fail with `panic: runtime error: invalid memory address or nil pointer dereference`.  The error isn't descriptive to what the underlying issue is.  `fn deploy` should first check and make sure the environment variable is correctly set.   

Updating route /register using image amyroh/register:0.0.4...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x911731]

goroutine 1 [running]:
main.(*routesCmd).putRoute(0xc420523778, 0xc4200fc6e0, 0x7ffe9d8a676c, 0x5, 0xc4204a0b90, 0x9, 0xc42017a700, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/routes.go:441 +0x2b1
main.(*deploycmd).updateRoute(0xc4200a5630, 0xc4200fc6e0, 0x7ffe9d8a676c, 0x5, 0xc4202c45a0, 0xc4202c45a0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:272 +0x228
main.(*deploycmd).deployFunc(0xc4200a5630, 0xc4200fc6e0, 0x7ffe9d8a676c, 0x5, 0xc4200200a4, 0x15, 0xc42041c700, 0x1f, 0xc4202c45a0, 0xc420523908, ...)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:250 +0x32f
main.(*deploycmd).deploySingle(0xc4200a5630, 0xc4200fc6e0, 0x7ffe9d8a676c, 0x5, 0x0, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:153 +0x1a8
main.(*deploycmd).deploy(0xc4200a5630, 0xc4200fc6e0, 0x0, 0x1)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:122 +0x100
main.(*deploycmd).(main.deploy)-fm(0xc4200fc6e0, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:27 +0x34
github.com/fnproject/cli/vendor/github.com/urfave/cli.HandleAction(0x9922a0, 0xc420502e90, 0xc4200fc6e0, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
main.prepareCmdArgsValidation.func1(0xc4200fc6e0, 0x0, 0xc4200fc6e0)
	/home/circleci/go/src/github.com/fnproject/cli/main.go:125 +0x260
github.com/fnproject/cli/vendor/github.com/urfave/cli.HandleAction(0x9922a0, 0xc420491980, 0xc4200fc6e0, 0xc420078d00, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/fnproject/cli/vendor/github.com/urfave/cli.Command.Run(0xa63092, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa8839c, 0x54, 0x0, ...)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/fnproject/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4203e71e0, 0xc4200a6040, 0x4, 0x4, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/home/circleci/go/src/github.com/fnproject/cli/main.go:133 +0x4f

**Comment by rdallman** [comment]
it's the dinky error handling of the cli it looks like, those swagger errors are a pain. it's a nil `e.Payload.Error.Message` that conforms to a swagger error we generate but is somehow not parseable.

gonna tear into this, thanks for filing the bug.
