### ISSUE TITLE
multiple instances of node func.js get deployed to docker

### ISSUE THREAD

**Issue by c094728** [fnproject/fn#915]
I'm running the sample function project setup
fn init --runtime node myproject
I retrieve the url at http://localhost:8080/r/myproject/myproject
If I pause for a while and reload the page, another instance shows up in docker ps.
These keep growing every time I pause for a while and reload
Note:
I had to stringify the results for the hello world example or it just displays [Object]
The init should have created it using stringify automatically.
return JSON.stringify(response);

**Comment by denismakogon** [comment]
> If I pause for a while and reload the page, another instance shows up in docker ps

This is how hot format works in Fn, function dies as soon as it will reach out the idle timeout (one of the key concepts of the serverless - never pay for idle).

> I had to stringify the results for the hello world example or it just displays

You should do that by yourself because FDK-node doesn't know how to serialize your object.

**Comment by c094728** [comment]
Thank you.  So where is the idle timeout defined?   I have 10 instances of the same container showing up in docker, all in Paused state and they have been there for over an hour.  And it still creates more if I reload the browser.

**Comment by c094728** [comment]
I'm still not understanding.   I understand that a cold function will start a new container for each request.  But why are they not going away after being called,  The seem to go to paused status and remain there.  If manually I run docker unpause then the container goes away.   They won't show up forever in paused state will they?

**Comment by denismakogon** [comment]
So, here's what Fn does: you call the function, Fn starts the container, your function processes the request, sends the response, Fn pauses the container for the time of the idle timeout (which is defaulted to 30 seconds), once idle timeout appeared - container dies.

Why are containers not going away? Because the function you've created from the `fn init` uses hot format by default, not the cold one.

> They won't show up forever in the paused state will they?

No, once the idle timeout happens, it's gone.

**Comment by c094728** [comment]
I thought cold function was the default.  How do I change it to be a cold function.  If I defined a hot function then why is it not reusing the same container for each request and instead loading a new instance.  (if there is a delay between requests).  And they seem to never go away.

**Comment by denismakogon** [comment]
> How do I change it to be a cold function?
set the format to `default` (use `fn routes update` cmd).

Fn will reuse the same container unless the request got delayed, if that delayed it will start a new container.

**Comment by c094728** [comment]
Thanks.  Sorry for all the questions but I'm new to fn.   It's strange that a property name of "format" is used to determine whether it's a hot or cold function.   So format of "default" is cold and format of json is hot.  That's confusing.   I tried it with default and now I see no instances in docker and they get loaded each time I refresh the browser so it's slower.   That makes sense.   But when I change it back to json,  now I can load in quick succession and it re-uses the same container that stays loaded.   However if I pause a while and reload, it loads a new instance into docker but the old one is still there.  Why wouldn't it continue to use the same instance since it seems to still be loaded and paused?  What happens to the old one?  Does it never get used again?  If not then why doesn't it get removed?

**Comment by denismakogon** [comment]
Can you elaborate what you mean by saying "if I pause a while and reload"?

**Comment by c094728** [comment]
If I reload the browser in quick succession I only see the one instance of docker.  But if I pause for about 10 seconds and then reload, the browser loads slowly and now I see another instance in docker.

**Comment by c094728** [comment]
Also I am seeing these messages on the fn console
time="2018-04-04T18:00:27Z" level=error msg="error removing container" container=01CA8WZEXMNG8G00GZJ000000M error="API error (500): {\"message\":\"Could not kill running container b48fb22f76e7f30623835889baccdc06bc9d937eee8da319af078309f0d75d63, cannot remove - Container b48fb22f76e7f30623835889baccdc06bc9d937eee8da319af078309f0d75d63 is paused. Unpause the container before stopping or killing\"}\n"

**Comment by skinowski** [comment]
Sounds like a docker bug. What version of docker are you using? I've seen this in older versions which refused to remove a paused container.

**Comment by c094728** [comment]
docker version
Client:
 Version:      17.06.2-ol
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   d02b7ab
 Built:        Fri Oct  6 00:02:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ol
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   d02b7ab
 Built:        Fri Oct  6 00:03:48 2017
 OS/Arch:      linux/amd64

**Comment by skinowski** [comment]
ah, another OL docker version that doesn't handle this.. Hmm, you can either upgrade docker, or
as a workaround for now, define this:

```
export FN_FREEZE_IDLE_MSECS=-1
```

**Comment by c094728** [comment]
The FN_FREEZE_IDLE_MSECS=-1  setting did not seem to have any affect.  I still cannot kill a paused container.   Upgrade to what?   I'm on Oracle Linux 7.4 running in virtualbox on windows and I thought 17.06.2-ol was the latest version of docker for that.

**Comment by c094728** [comment]
I installed 17.10.0-ce version of docker and it seems to be working correctly now.  The container gets removed after about 30 seconds so I see either one or no instances running at any time
I really appreciate your help

**Comment by skinowski** [comment]
Np, could you also post what os version you are using? eg /etc/redhat-release? Is this oracle linux 7.4?

**Comment by skinowski** [comment]
Oh, saw your post now. Ok, closing this...
