### ISSUE TITLE
Problem running headless chrome using puppeteer in FN

### ISSUE THREAD

**Issue by c094728** [fnproject/fn#922]
I'm trying to run with puppeteer node.js module to retrieve a web page using headless chrome
It fails to execute with
 Error: Failed to launch chrome! spawn /function/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome ENOENT

Here is my code. 
var fdk=require('@fnproject/fdk');
const puppeteer = require('puppeteer');

fdk.handle(function(inp){
  try{
  const makeRequest = async () => {
  const browser = await puppeteer.launch();
   const page = await browser.newPage();
   await page.goto('https://example.com');
   var bodyHTML = await page.evaluate(() => document.body.innerHTML);
   await browser.close();
   return bodyHTML;
}

  makeRequest().then((result) => {
   return result;
	})
} catch(e){
	return e + ' ' + inp;
	}
}
)

**Comment by zootalures** [comment]
Could you share your func.yaml and build process? 

Are you running npm inside fn build  or on your host?  

if you running npm install prior to fn build then  fn will use node_modules from your build dir -  (e.g. on mac) you may end up with inconsistent binary deps in your node_modules

If you can try removing node_modules and running fn build again (this will run npm install on linux inside the container)

**Comment by c094728** [comment]
I deleted the node_modules and ran fn build followed by  fn run.   It got the same error
Here is my func.yaml

name: crawl
version: 0.0.48
runtime: node
entrypoint: node func.js
format: json

**Comment by c094728** [comment]
What is is your base image fnproject/node:dev ?  Can I just use your Dockerfile above and replace base image with something like node:8 ?

**Comment by zootalures** [comment]
Anything going to stderr should be stored in fn logs 

(fn log get <appname> last)

**Comment by c094728** [comment]
fn log is needing a call-id.  I don't see a call-id on the fn console.  I see in ID but using that doesn't return anything.  where is the actual log file?

  It shows this when I send a request

time="2018-04-23T16:07:07Z" level=info msg="Hot function launcher starting hot container" action="server.handleFunctionCall)-fm" app=crawl app_id=01CBRSDD6XNG8G00GZJ0000001 currentStats="{[0 1 0 3] [0 1 0 0 0 3]}" id=01CBSKDV8DNG8G00GZJ0000001 isNeeded=true route=/crawl
time="2018-04-23T16:07:10Z" level=info msg="starting call" action="server.handleFunctionCall)-fm" app=crawl app_id=01CBRSDD6XNG8G00GZJ0000001 container_id=01CBSM4F9ANG8G00GZJ0000008 id=01CBSM4F99NG8G00GZJ0000007 route=/crawl
time="2018-04-23T16:07:11Z" level=error msg="api error" action="server.handleFunctionCall)-fm" app=crawl code=502 error="invalid json response from function err: invalid character 'r' looking for beginning of value" id=01CBSM4F99NG8G00GZJ0000007 route=/crawl
time="2018-04-23T16:07:11Z" level=info msg="hot function terminating" app_id=01CBRSDD6XNG8G00GZJ0000001 cpus= error="invalid json response from function err: invalid character 'r' looking for beginning of value" format=json id=01CBSM4F9ANG8G00GZJ0000008 idle_timeout=30 image="crawl:0.0.60" memory=128 route=/crawl
time="2018-04-23T16:07:11Z" level=info msg="hot function terminated" app_id=01CBRSDD6XNG8G00GZJ0000001 cpus= error="context canceled" format=json id=01CBSM4F9ANG8G00GZJ0000008 idle_timeout=30 image="crawl:0.0.60" memory=128 route=/crawl

**Comment by denismakogon** [comment]
@c094728 you can get the call ID in HTTP response headers if you calling the sync function, if you're using an async function you'd get the response in the following format:
```json
{"call_id":"...."}
```

**Comment by denismakogon** [comment]
@c094728 `default` format means that whatever goes to STDOUT you'll get in the response body. However, `default` format is not a resource efficient, starts a container per request. I recommend sticking with JSON or HTTP format. There has to an example how to make your function written in Node work with those formats. Despite that, i strongly recommend to use Node FDK - https://github.com/fnproject/fdk-node for any node function.

**Comment by c094728** [comment]
Attached is my project minus the node_modules which made it to bit to attach.
If you deploy this and post  {"url":"http://testing-ground.scraping.pro"}
It will use puppeteer to retrieve that page and display info about the components of the page.
When I have the format set to default,  It runs all the way through and returns everything logged.
If I change format to be json It returns a json error and I get nothing in the logs.  I am returning a hard coded json string so it shouldn't be getting an error but this is what I get.
{
    "error": {
        "message": "invalid json response from function err: invalid character 'e' in literal null (expecting 'u')"
    }
}

If someone can try running this I would greatly appreciate it if they could let me know what might be wrong.   


[crawl.zip](https://github.com/fnproject/fn/files/1940327/crawl.zip)

**Comment by c094728** [comment]
The main problem I had, after getting the image working was that the statements console.log(...) or console.info(...) will break the json response.   Any logging needs to be console.error() for it to go to the log file.

**Comment by c094728** [comment]
Question about timeouts.  My node.js process may need to run for longer than 2 minutes and that is the maximum timeout your settings allow.   Can functions return a response and continue to run asyncrounously?   Does the timeout kill the running function?

**Comment by denismakogon** [comment]
If your function is sync - 120 seconds is the max time you can get from Fn.

> Can functions return a response and continue to run asynchronously?

No, once the function returns the response it freezes until next event.

> Does the timeout kill the running function?

It doesn't kill but pauses the container, so your function freezes.

**Comment by c094728** [comment]
freezes?  So when the next request comes in my function picks up where it left off and now there are two running?

**Comment by c094728** [comment]
If I change it to async, can I create a function method that will return status if you pass in the call_id ?

**Comment by denismakogon** [comment]
that is not guaranteed, it is not recommended to start background or threaded process without any proper synchronisation just before sending the response.

Your function will freeze only in case if you've sent the response, not before that. If your function times out - it dies.

**Comment by denismakogon** [comment]
if you change your function to be async it will run in detached mode, you would not get the response from that, however, the timeout will increase significantly up to 3600 seconds.

**Comment by c094728** [comment]
I tried it with async.  I can't seem to view any logs until it completes.   Is there a way to view the stderr pipe while it's running?   docker logs command give me "configured logging driver does not support reading"

**Comment by denismakogon** [comment]
At this particular moment, no. Only when you function complete it’s execution.

**Comment by c094728** [comment]
Regarding stdout, if I need to exec shell child_process I need to make sure nothing gets written to stdout and everything is piped to stderr?   That needs to be in bold red letters at the top of this project.  It would have saved me a lot of grief. 😆

**Comment by denismakogon** [comment]
As long as you do correct IO pipe binding and reading from exec your program will remain safe and would not break protocol framing.

**Comment by c094728** [comment]
I opened this other issue.  Can anyone explain?
https://github.com/fnproject/fdk-node/issues/12

**Comment by rdallman** [comment]
think this is resolved? thanks, re-open if needed
