### ISSUE TITLE
Routes - Updating function doesn't work

### ISSUE THREAD

**Issue by kocic11** [fnproject/fn#943]
Trying to use the curl to update a function doesn't work.

The following command fails:
curl -H "Content-Type: application/json" -X POST -d '{
    "route": {
        "memory": 100,
        "cpus": "0.2",
        "type": "async"
    }
}' http://xxx.xxx.xxx.xxx:8080/v1/apps/myapp/routes/hello-async

with the following error:
{"error":{"message":"Path not found: /v1/apps/myapp/routes/hello-async"}}

When I put the same link in the browser it returns the following:
{"message":"Successfully loaded route","route":{"app_id":"01CAREB13JNG8G00GZJ0000001","path":"/hello-async","image":"xxx/hello-go:0.0.24","memory":100,"cpus":"200m","type":"async","format":"default","timeout":30,"idle_timeout":30,"created_at":"2018-04-10T18:52:53.254Z","updated_at":"2018-04-10T18:52:53.254Z"}}

Please advise.

**Comment by rdallman** [comment]
the second one is a GET request it looks from the response: 'loaded route' is from GET

**Comment by rdallman** [comment]
if you want to create against the url that contains the route name, you may use `PUT` instead of `POST`

**Comment by rdallman** [comment]
for `POST` you would need to add a field for `"path":"hello-async"` and post against `/v2/apps/myapp/routes`

going to close, re-open if this is broken (we have tests, pretty sure we're ok on this one). thanks for giving this a whirl

**Comment by kocic11** [comment]
Just to make it clear, I am trying to update the existing function.

The first command is from the example provided at fn/docs/operating/routes.md. The second command shows the path actually exists.

If I understood you correctly, the suggestion is to run the following command:
curl -H "Content-Type: application/json" -X POST -d '{
    "route": {
	"path":"/hello-async",
	"memory": 100,
        "cpus": "0.2",
        "type": "async"
    }
}' http://xxx.xxx.xxx.xxx:8080/v1/apps/myapp/routes

It returns the following error:
{"error":{"message":"Missing route Image"}}

And if I do add the image and run the following command:
curl -H "Content-Type: application/json" -X POST -d '{
    "route": {
	"path":"/hello-async",
	"image":"xxx/hello-go:0.0.24",
	"memory": 100,
        "cpus": "0.2",
        "type": "async"
    }
}' http://xxx.xxx.xxx.xxx:8080/v1/apps/myapp/routes

it returns the following error:
{"error":{"message":"Route already exists"}}

Maybe you could provide an example that updates the existing function.

**Comment by rdallman** [comment]
yep, try using PUT, e.g.:

```
curl -H "Content-Type: application/json" -X PUT -d '{
"route": {
"image":"xxx/hello-go:0.0.24",
"memory": 100,
"cpus": "0.2",
"type": "async"
}
}' http://xxx.xxx.xxx.xxx:8080/v1/apps/myapp/routes/hello-async
```

**Comment by kocic11** [comment]
No error returned, but the function was not updated.

**Comment by kocic11** [comment]
My bad, it actually worked. I had to change the path from /v1/apps/myapp/routes to v1/apps/myapp/routes/hello-async. 

Just for others, here is the example that actually worked:
curl -H "Content-Type: application/json" -X PUT -d '{
    "route": {
	"path":"/hello-async",
	"image":"xxx/hello-go:0.0.24",
	"memory": 300,
        "cpus": "0.2",
        "type": "async"
    }
} 'http://xxx.xxx.xxx.xxx:8080/v1/apps/myapp/routes/hello-async

Perhaps someone could change the examples from POST to PUT.

Thanks again!

**Comment by rdallman** [comment]
will do! would you mind pasting a link to the examples you were following? want to make sure we are fixing the right ones, they're a bit spread out atm. thanks!

**Comment by kocic11** [comment]
Here is the link: 
Updating function
https://github.com/fnproject/fn/blob/master/docs/operating/routes.md#updating-function
