### ISSUE TITLE
Lb failing with "Enqueue not implemented. Panicking" message

### ISSUE THREAD

**Issue by kocic11** [fnproject/fn#944]
Followed example [Running load-balanced fn against a pool of runners](https://github.com/fnproject/fn/blob/master/docs/operating/runner_pools.md) and created 2 runners, api, and lb servers.

When executing an async function call the lb exits with the following error:
time="2018-04-17T19:27:49Z" level=fatal msg="Enqueue not implemented. Panicking."

Synchronous call succeeds:
time="2018-04-17T19:27:35Z" level=info msg="Call finished successfully: 01CBAH75F4NG8G01RZJ0000001"

Please advise

**Comment by rdallman** [comment]
yep, we are not implementing async for hybrid for the immediate future (and this may go away altogether in its current capacity, but tbd). sorry that we didn't clearly document this. we're working to make a good sync experience at the moment. thanks for trying this out!
