### ISSUE TITLE
Need proper way to filter calls on Fn side instead of doing that on client side

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#946]
## problem
At this moment there are only a few available parameters we can use to filter calls:
 - app
 - path
 - timestamp (from-, to-time)

I can see that there's a need to get more filtering options like:
 - status
 - error (complete match or partial)

There might me methods available by underlying call store (sql, s3), however, may not be available.

## solution
TBD

**Comment by rdallman** [comment]
close for #1055 ?
