### ISSUE TITLE
async function response turns log store into an async call persisted store

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#953]
## problem
When you create and call a sync function you'll get the response immediately.
However, if you'd turn that function into an async one, whatever function will write back to stdout will end up in logs.

## steps to reproduce
1. create a function:
```bash
fn init --runtime go && fn deploy
```
2. call function:
```bash
fn call <app> <path>
```
3. Make it async:
```bash
fn routes update <app> <path> --type async
```
4. call function:
```bash
fn call <app> <path> --display-call-id
```
5. check call logs:
```bash
fn calls get <app> <call-id>
```
You'll see that depending on the protocol call log will include a response frame.

## question

Is there any reason to intentionally make the log store to become a persisted store for async results?

**Comment by rdallman** [comment]
yes, you would lose headers, for one. 

this is pretty straightforward once we have cloud events.

**Comment by denismakogon** [comment]
I mean, why should we store the response of the async function? It makes Fn's log store a result storage.

**Comment by rdallman** [comment]
not sure it's worth discussing, async is gonna get killed.

**Comment by denismakogon** [comment]
okay.
