### ISSUE TITLE
Is fn.db fn.mq required for fn to run?

### ISSUE THREAD

**Issue by c094728** [fnproject/fn#962]
I was wondering if I can safely delete the data directory if I'm not using a database.  They are checked into source control and seem to get modified randomly.  Do these get created when you start up fn server?

Also this link references function.db but It is named fn.db on my system.
https://github.com/fnproject/fn/blob/master/docs/operating/databases/README.md#sqlite3-default

**Comment by denismakogon** [comment]
going to close, this particular area covered by [operational docs](https://github.com/fnproject/fn/tree/master/docs/operating).
