### ISSUE TITLE
Support --no-build and --path options to fn cli to create multiple routes for the same function

### ISSUE THREAD

**Issue by venkat50** [fnproject/fn#963]
fn deploy already supports --no-bump but appears to build anyway. While testing the local deploy, an easy way to create multiple routes is by modifying "path" in func.yaml before fn deploy. 

Using this feature, I was able to extend [toupper sample](https://github.com/venkat50/tutorials/blob/master/ContainerAsFunction/README.md) to support tolower by reversing the transformation.

**Comment by rdallman** [comment]
likely this will be much improved in the cli soon now that #1045 has landed, will leave this open to track. thanks

**Comment by venkat50** [comment]
I was able implement this usecase using using triggers. A follow-up issue is that to add the additional triggers, I did not see "add" option to trigger or app. Please let me know if I need to open a separate issue.
