### ISSUE TITLE
Node fdk function hangs

### ISSUE THREAD

**Issue by c094728** [fnproject/fn#969]
I'm having a problem getting my puppeteer project to run as a function.
I can log into the docker container that was generated by fn build and run it manually using node command line and it runs and completes in about 30 seconds.
But when I call it as a function passing the same parameters it hangs up and eventually times out after an hour.     I don't know how to debug it since it works fine in node but not as a function.
The app crawls a web site and downloads the pages, zips them up and then uploads them.  When run as a function it never finishes crawling the site and I can't tell why it's hanging up because I can't see the log unless I kill it or wait for it to time out.  After I kill it the log shows that it saved half a dozen files before it hung but there are no errors reported.  Any tips to debugging this?  I can share the project if you want it.

**Comment by denismakogon** [comment]
Sharing code is useful. However, timeout can be caused by your function that doesn’t write any response to Fn, even if that is an async function, it must send formatted protocol frame to Fn as a proof of completed request processing.

**Comment by c094728** [comment]
What is definition of "formatted protocol frame"?  I added 
return {'success':'true'}
but it still hangs.  I don't think it is getting to the return statement if the logs are accurate after I kill it.

**Comment by c094728** [comment]
[crawl.zip](https://github.com/fnproject/fn/files/1968513/crawl.zip)
my project is attached.
This command should run to completion
echo -n '{"url":"https://sitecake.com/demo/live/5aea03415f964/sitecake.php",  "basepath": "perfecto/fntest",  "owner": "don.kleppinger@test.com",  "repository": "selfpublish.junk",  "collectionid": "222",  "artifactid": "111",  "debug": false,  "debugOnePage":false }' | fn --verbose run

**Comment by c094728** [comment]
You will probably have to remove the proxy-server parameter from the puppeteer launch statement to make it work.  Also I changed the url above because the other one was down.   The shell commands that happen at the end probably won't work but it should at least finish and return an error.

**Comment by denismakogon** [comment]
Would you mind to build docker image and send me a link to that?
As well as put code somewhere on github or bitbucket?

**Comment by c094728** [comment]
You can pull from here.  The Dockerfile will pull the image from repo
https://github.com/c094728/crawl.git

**Comment by c094728** [comment]
The problem might be that I'm returning a Promise to my json response and not a json response.   I can't figure out how to return the value when my code uses promises because to get the result it has to be inside a .then function and the original promise has already been returned.   I can wait using async and await but async function still returns a promise.   Does fdk support using promises?

**Comment by c094728** [comment]
I originally had a bug and it was returning undefined instead of the promised but it still hung after I fixed that.   But it seems the problem was just too little memory.  I Added the memory setting into the func,.js to 1GB instead of the default of 128mb and now it runs to completion in a timely manner.   It was just memory bound.

Question:  When a request finishes and the container goes into a paused state and then another request comes in.  Is that request able to see anything written to the file system by the 1st request.  i.e. do I need to clean up my state before exiting?

**Comment by denismakogon** [comment]
You can clean up only when request comes in and your handler takes its place and right before sending the response. You can’t run any code as soon as you ship the response, you function gets paused.

**Comment by rdallman** [comment]
seems resolved. thanks!
