### ISSUE TITLE
Fn Project - Nodejs - function returns fail - Error in function: SyntaxError: Unexpected token q in JSON at position 39

### ISSUE THREAD

**Issue by vinvantest** [fnproject/fn#976]
Hi, 

I have a simple nodejs function that returns JSON. I guess the documentation needs update on nodejs page too on how to use input, ctx objects. But first the issue - the function runs as expected but on return of JSON object it fails. Some JSON.parse error.

//--- Error dump
Step 9/9 : ENTRYPOINT ["node", "func.js"]
 ---> Running in 3b0d9e7e8884
Removing intermediate container 3b0d9e7e8884
 ---> 336fb9ed431b
Successfully built 336fb9ed431b
Successfully tagged landstats:0.0.4

ctx = {"config":{"properties":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"38679dba4ab2","NPM_CONFIG_LOGLEVEL":"info","NODE_VERSION":"8.4.0","YARN_VERSION":"0.27.5","HOME":"/root"}},"payload":{"call_id":"12345678901234567890123456","content_type":"application/json","deadline":"2018-05-07T15:45:44+10:00","body":"{\"uid\":\"6Dnb2nfA7FRVBjsAT7d8tHGH8kH2\", quater1StartDate: \"01-01-201\", quater4EndDate:\"01-03-2018\" }","protocol":{"type":"http","method":"POST","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}},"format":"json","path":"/hello","memory":0,"app_name":"myapp","type":"sync"},"_proto":{"payload":{"type":"http","method":"POST","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}},"out":{"status_code":200,"headers":{}}},"_ctxout":{"content_type":"application/json"}}
input = {"uid":"6Dnb2nfA7FRVBjsAT7d8tHGH8kH2", quater1StartDate: "01-01-201", quater4EndDate:"01-03-2018" }
method = POST
Inside handlePOST()
Returning object
Returned from POST {"error":"Forbidden!"}
Error in function: SyntaxError: Unexpected token q in JSON at position 39
    at JSON.parse (<anonymous>)
    at extractRequestBody (/function/node_modules/@fnproject/fdk/fn-fdk.js:38:17)
    at /function/node_modules/@fnproject/fdk/fn-fdk.js:130:17
    at Promise (<anonymous>)
    at Parser.parser.onValue (/function/node_modules/@fnproject/fdk/fn-fdk.js:127:5)
    at Parser.proto.emit (/function/node_modules/jsonparse/jsonparse.js:337:8)
    at Parser.proto.pop (/function/node_modules/jsonparse/jsonparse.js:332:8)
    at Parser.parser.pop (/function/node_modules/@fnproject/fdk/fn-fdk.js:105:10)
    at Parser.proto.onToken (/function/node_modules/jsonparse/jsonparse.js:402:12)
    at Parser.proto.write (/function/node_modules/jsonparse/jsonparse.js:135:34)

// ---------- fn command to call
echo -n '{"uid":"123", quater1StartDate: "01-01-201", quater4EndDate:"01-03-2018" }' | fn --verbose run

//------ func.js file

function handlePOST (input, ctx) {
  // Do something with the request
  console.error('Inside handlePOST()');
  ctx.protocol.statusCode = 403;
  console.error('Returning object');
  return { 'error' : 'Forbidden!' };
}

fdk.handle(function(input, ctx)
{
  console.error('ctx = '+ JSON.stringify(ctx));
  console.error('input = '+ JSON.stringify(input)); 
//<--- Note: input is undefined where as documentation example indicates input will populated.
  console.error(ctx.paylod.body = '+ctx.payload.body);
  console.error('method = '+ctx.payload.protocol.method);
  switch (ctx.payload.protocol.method)
  {
    case 'GET':
      return handleGET(input, ctx);//handleOriginAndAuth(input, ctx);
      break;
    case 'PUT':
      return handlePUT(input, ctx);
      break;
    case 'POST':
      return handlePOST(input, ctx);
      break;
    case 'DELETE':
      return handleDELETE(input, ctx);
      break;
    case 'OPTIONS':
      return handleOPTIONS(input, ctx);
      break;
    default:
      ctx.protocol.statusCode = 500;
      return { error: 'Something blew up!' };
      break;
  }

});

**Comment by denismakogon** [comment]
Have specified method you use? `fn run —method`?
From the error response, it clear that your function returns invalid JSON.

**Comment by denismakogon** [comment]
Your defualt response seems to be wrong:
`{ error: 'Something blew up!' }`
But has to be:
`{ 'error': 'Something blew up!' };`

**Comment by vinvantest** [comment]
Hi, didn't work with -method ... same error. also tried to change the JSON returned to suggested i.e. 'error : ' ss'. same error



function handleGET (input, ctx) {
  // Do something with the PUT request
  console.error('Inside handleGET()');
  ctx.protocol.statusCode = 403;
  console.error('Returning object');
  return { 'error' : 'Forbidden!' };
}

$ echo -n '{"uid":"6Dnb2nfA7FRVBjsAT7d8tHGH8kH2", quater1StartDate: "01-01-201", quater4EndDate:"01-03-2018" }' | fn --verbose  run -method GET
Building image landstats:0.0.4
Sending build context to Docker daemon  124.4kB
Step 1/9 : FROM fnproject/node:dev as build-stage
 ---> 016382f39a51
Step 2/9 : WORKDIR /function
 ---> Using cache
 ---> f6a6efe74c7e
Step 3/9 : ADD package.json /function/
 ---> Using cache
 ---> 87e728530023
Step 4/9 : RUN npm install
 ---> Using cache
 ---> 95babad1c119
Step 5/9 : FROM fnproject/node
 ---> 016382f39a51
Step 6/9 : WORKDIR /function
 ---> Using cache
 ---> f6a6efe74c7e
Step 7/9 : ADD . /function/
 ---> fb1cf8b31e2a
Step 8/9 : COPY --from=build-stage /function/node_modules/ /function/node_modules/
 ---> 42d7df1ca467
Step 9/9 : ENTRYPOINT ["node", "func.js"]
 ---> Running in b7c3d81a4194
Removing intermediate container b7c3d81a4194
 ---> 4072ea543337
Successfully built 4072ea543337
Successfully tagged landstats:0.0.4

ctx = {"config":{"properties":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"94229b5cb445","NPM_CONFIG_LOGLEVEL":"info","NODE_VERSION":"8.4.0","YARN_VERSION":"0.27.5","HOME":"/root"}},"payload":{"call_id":"12345678901234567890123456","content_type":"application/json","deadline":"2018-05-07T16:10:49+10:00","body":"{\"uid\":\"6Dnb2nfA7FRVBjsAT7d8tHGH8kH2\", quater1StartDate: \"01-01-201\", quater4EndDate:\"01-03-2018\" }","protocol":{"type":"http","method":"GET","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}},"type":"sync","format":"json","path":"/hello","memory":0,"app_name":"myapp"},"_proto":{"payload":{"type":"http","method":"GET","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}},"out":{"status_code":200,"headers":{}}},"_ctxout":{"content_type":"application/json"}}
input = {"uid":"6Dnb2nfA7FRVBjsAT7d8tHGH8kH2", quater1StartDate: "01-01-201", quater4EndDate:"01-03-2018" }
method = GET
Inside handleGET()
Returning object
Error in function: SyntaxError: Unexpected token q in JSON at position 39
    at JSON.parse (<anonymous>)
    at extractRequestBody (/function/node_modules/@fnproject/fdk/fn-fdk.js:38:17)
    at /function/node_modules/@fnproject/fdk/fn-fdk.js:130:17
    at Promise (<anonymous>)
    at Parser.parser.onValue (/function/node_modules/@fnproject/fdk/fn-fdk.js:127:5)
    at Parser.proto.emit (/function/node_modules/jsonparse/jsonparse.js:337:8)
    at Parser.proto.pop (/function/node_modules/jsonparse/jsonparse.js:332:8)
    at Parser.parser.pop (/function/node_modules/@fnproject/fdk/fn-fdk.js:105:10)
    at Parser.proto.onToken (/function/node_modules/jsonparse/jsonparse.js:402:12)
    at Parser.proto.write (/function/node_modules/jsonparse/jsonparse.js:135:34)
Exception in function--consult logs for detailsVinayaks-MBP:landstats vinayakvanarse$

**Comment by vinvantest** [comment]
another interesting error

trying to access ctx.body

it throws same JSON parse error

Here the code --

  // Do something with the GET request
   console.error('Inside serer.get(launchStats()) = '+ctx.body);
   var input = JSON.parse(ctx.body);
   console.error('input.uid = ' + input.uid);
   console.error('input.quater1StartDate = ' + input.quater1StartDate);
   console.error('input.quater4EndDate = ' + input.quater4EndDate);

   var routingUid = input.uid;
   var quater1StartDate = input.quater1StartDate;
   var quater4EndDate = input.quater4EndDate;

**Comment by denismakogon** [comment]
See my comments in Slack: https://fnproject.slack.com/archives/C6FL02Q02/p1525678394000277?thread_ts=1525674382.000214&cid=C6FL02Q02

**Comment by vinvantest** [comment]
thanks for the help. it worked. 2 things I was doing wrong. 1. eco command with -n flag ... and trying to get input from ctx

**Comment by denismakogon** [comment]
I'm glad was able to help you to solve problems you've faced with. If you have anything else, feel free to ping me in slack (@denismakogon)
