### ISSUE TITLE
Problem with call objects availability and persistency

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#979]
## problem area

Imagine pretty dummy use case - developer mentioned a "bad image" that is not available on the registry. So, when i submit a call the only thing I get - call ID, so, any attempts to get call state would just fail because call ID is not getting persisted at all.

Unfortunately, there's no way to discover the source of a problem using calls API for such particular cases (make function `sync` will show you most of problems with images, but not the case).

## how to solve the problem

First of all, create call object as soon as call submitted (see the related issue: #978). If there's a problem with related docker images that agent can't pull, Fn must persist call object in `error` state with the corresponding error.

## side note

There might be more problems that must be reported to a caller through calls API, such as:
 - `Too busy` is not reported to the caller
 - image not found

what else?

**Comment by rdallman** [comment]
there is an issue somewhere documenting that certain behaviors cause an async call to attempt to be invoked forever. again, async getting ripped out of core.

**Comment by rdallman** [comment]
triaging to #281

**Comment by rdallman** [comment]
triaging to #1055
