### ISSUE TITLE
Switch to bbolt since bolt is no longer maintained

### ISSUE THREAD

**Issue by everflux** [fnproject/fn#990]
The author of of the bolt database states that the project is no longer maintained and that users should consider switching to bbolt instead. Repo of bbolt is https://github.com/coreos/bbolt

**Comment by rdallman** [comment]
thanks for the issue. to be clear, the author states:

> Unfortunately I no longer have the time or energy to continue this work. Bolt is in a stable state and has years of successful production use. As such, I feel that leaving it in its current state is the most prudent course of action.

we do not recommend boltdb for production installations of fn simply for the reason that it's embedded and not accessible by multiple fn servers. bolt is stable for us, especially for our needs with it (a nice 'getting started' story), and this isn't a priority to switch to bbolt as we don't need the feature set it offers over bolt in any case. That being said, if a PR opened that added support for bbolt we would be happy to adopt it in bolt's stead or alongside it if this was something someone was interested in. cheers
