### ISSUE TITLE
Process crashing with panic

### ISSUE THREAD

**Issue by steveww** [fnproject/fn#999]
Deployed to GKE with helm chart. Pod entered crash back off with the following log:

fnlb | May 15, 2018, 12:31:34 PM | /go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:56 +0x20e
-- | -- | --
fnlb | May 15, 2018, 12:31:34 PM | created by github.com/fnproject/fn/fnlb/lb.NewK8sStore
fnlb | May 15, 2018, 12:31:34 PM | /go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:144 +0xb5e
fnlb | May 15, 2018, 12:31:34 PM | github.com/fnproject/fn/fnlb/lb.(*k8sStore).watch(0xc4202baa20, 0xc4201f43b0, 0x7, 0x7ffefd94564a, 0x20, 0x50)
fnlb | May 15, 2018, 12:31:34 PM | goroutine 5 [running]:
fnlb | May 15, 2018, 12:31:34 PM |  
fnlb | May 15, 2018, 12:31:34 PM | panic: unknown (get pods)

**Comment by yuval-k** [comment]
I'm getting a similar error:
```
panic: unknown (get pods)

goroutine 6 [running]:
github.com/fnproject/fn/fnlb/lb.(*k8sStore).watch(0xc42028bb60, 0xc4202ac190, 0x7, 0x7fffbf609611, 0x21, 0x50)
	/go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:144 +0xb5e
created by github.com/fnproject/fn/fnlb/lb.NewK8sStore
	/go/src/github.com/fnproject/fn/fnlb/lb/k8s_store.go:56 +0x20e
```

kube version: 
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yuval-k** [comment]
Apparently the latest minikube has RBAC on by default, so deploying with `--set rbac.enabled=true` solves it for me

**Comment by steveww** [comment]
I confirm that the --set brace.enabled=true worked for me on GKE.
I suggest an update to the README.md to mention this.
